### ISSUE TITLE
space after words

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#103]
Should text be entered with a space at the end of the word (as done by Eugenia and me) or without (as done by Massimo and Nafisa)? i.e. 
ለሰብአ ፡ ገላቲያ ፡  or
ለሰብአ፡ ገላቲያ፡  
it certainly should be standardised

**Comment by thea-m** [comment]
The decision could then be added to the Text Transcription in the Guidelines:
https://github.com/SChAth/ScAthiop/wiki/guidelines#text-transcription

I suppose we should opt for the second version, without space ለሰብአ፡ ገላቲያ፡

**Comment by eu-genia** [comment]
without space of course (if i had a space i was wrong!)
