### ISSUE TITLE
apparatus 

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#108]
greek-ethiopic apparatus for parallels in BNF manuscripts

**Comment by PietroLiuzzo** [comment]
@thea-m please could you provide a list of the manuscripts needing this?

**Comment by thea-m** [comment]
BNFet33 (currently only Geez in the body as separate items)
BNFet53 (Apparatus not yet added)
Apparatus without Greek also in BNFet50 (Apparatus partly added as separate items) and BNFet51 (Apparatus not yet added)

**Comment by PietroLiuzzo** [comment]
for the case of BNFet33 and 32 I think we can leave the information within BNFet33 as in the catalogue and encode it as follows not to loose the information provided. 

````xml
<app type="variants" from="#Mt1" loc="18">
   <lem resp="PRS10747Zotenbe" wit="BNFet33">ዕንስት፡</lem>
   <rdg resp="PRS10747Zotenbe" wit="BNFet32">እንዘባ፡ ውስተ፡ ማኅፀና፡</rdg>
   <rdg resp="PRS10747Zotenbe" xml:lang="grc">ἐν γαστρὶ ἔχουσα</rdg>
</app>
````
This is valid informatio also for BNFet32 equally and could be copied over.
this says all we can and implies that the Mt1 div in the transcription is added. As an edition of the text, in this case Mattew is carried out in a Work record this apparatus might be carried over and altered accordingly. 

I will now proceed to complete the encoding for these two and provide a preview for this elements.

to be noted is that it would be nice for the greek to say with a  `@source` from which edition does the greek text come, although.  

to avoid the resp repetition, we could also do like this

````xml
<app type="variants" from="#Mt1" loc="18">
      <lem wit="BNFet33">ዕንስት፡</lem>
      <rdg  wit="BNFet32">እንዘባ፡ ውስተ፡ ማኅፀና፡</rdg>
      <rdg xml:lang="grc">ἐν γαστρὶ ἔχουσα</rdg>
      <wit><persName ref="PRS10747Zotenbe"/></wit>
</app>
````

**Comment by PietroLiuzzo** [comment]
in BNFet33 is now possible to see this content displayed as apparatus

**Comment by PietroLiuzzo** [comment]
after discussion of this first example with @thea-m the first of the options above seams to be the most sensible. to complete an example we will also take the lines Mt 1, 18-25 from the Zuurmond edition and add this text to the LIT2709Matthew record. In this case nevertheless I will encode the apparatus inside the text and not in a separate div apparatus. also omission, choices, etc. will be printed in apparatus in the edition. on this regard we need to discuss the way the text with apparatus is displayed.

**Comment by PietroLiuzzo** [comment]
see http://betamasaheft.aai.uni-hamburg.de/works/LIT3122Galaw/text and  https://github.com/SChAth/ScAthiop/wiki/guidelines#critical-apparatus
