### ISSUE TITLE
relations documentation

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#111]
We need better documentation and guidance to use relations and refs. if somebody has been active in a place should there be a ref in one of the two entities or a relation between the two in both? 

also a list of the available relations with definitions should be added to the guidelines

**Comment by PietroLiuzzo** [comment]
generally relations should provide synthetic and meaningfull connection between different records: place-person, work-manuscript, institution-person etc.

for places it has been discussed that 

* administrative position will not be modelled explicitly as a relation
   * the graph of relations for the item will not dispaly this
   * the general graph of relations will instead convert each of this in a isLocatedIn relation


* for relations definitions come from established ontologies for a future linked data serialization. Therefore:
    * we should limit the number of relation names to be minted for our own project. if in none of the ontologies in use there is a proper value there might be two ways to deal with that.
   1. perhaps we need more than one statement. for example a cousin could be just a cousin, but could also be expressed as the son of the sister of a mother. 
   2. we need a new relation name because the relation cannot be expressed by multiple statements.

**Comment by PietroLiuzzo** [comment]
It is now irrelevant where the relations are recorded. so if a cataloguer needs or want to enter relations between works should be able to do this. this is not shown in the xslt preview but works in the app using xquery. A good example of this situation is that of translators, as discussed with @sologebre.

a translator is an author of a work which is a translation.
the ideal way to record this relation is to use two relations, 

@active=PRS1234theTranslator 
@name=saws:isAttributedAuthorOf 
@passive=LIT1234theTranslation 

the other with 

@active=LIT1234theTranslation 
@name=saws:isTranslationOf 
@passive=LIT1235theTranslatedWork

which can stay in the same record. As always, the value of active and passive can be a link to an external resource. thus, if this is the translation say of a syriac text in syriaca.org, LIT1235 can be simply the stable uri of the relevant resource in Syriaca.org. If a full record is not available in a reliable resource online, than we might have in our work record and use for a pointer.

If none of this is possible, for example because only the fact that this is translation is known, but we don't now from which tradition, then we have a bm:isAuthorOfEthiopicTranslation in the relation list. to be used sparingly.

**Comment by PietroLiuzzo** [comment]
@eu-genia suggests instead to avoid in Works and Persons the authors / translators relations and use instead only author element in the `titleStmt`s of Work records. This is also a sensible solution. it does not allow people to enter the information as they find it in an explicit relation mode, but involves the need for them to open the work record file and edit it. it is indeed very useful for the clavis which will have to do less lookout and searching within the relations. more careful consideration of the two options for documentation in guidelines is needed.

**Comment by PietroLiuzzo** [comment]
LIT1462GadlaH
for the moment doubled also in PRS8387SalamaI

**Comment by eu-genia** [comment]
my idea was to try and not double information as much as possible. so e.g. when describing a ms i say that it was copied by PRS1234, under a work i say that it may be authored by PRS1234, under an institution i mention that it was founded or headed by PRS1234 etc etc, and i do not add these relations any more under PRS1234, as they are printed there

**Comment by eu-genia** [comment]
so when i describe a work and say that LIT1234 is authored by PRS9999 (the original) and LIT1234EthiopicVersion is translated (author role translator?) by PRS1234 and revised by PRS5678 etc etc; and LIT5678 was originally authored by PRS1234 - then on viewing the PRS1234 I see LIT1234 in the list of works he translated and LIT5678 in the list of works he authored (and then have eventually the institutions he founded, etc etc etc)
i think that authorship etc is primarily an attribute important for the Clavis so should always be in some way stated in the Work file
