### ISSUE TITLE
additions xml:id "a" or "e"

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#113]
The guidelines currently say on additions:
@xml:id will use “a” and a consecutive number. In case of other contents (varia) this will have an id with “e”.
Could we add a clearer definition? Is "a" used only for additions from the same time as the writing of the manuscript?

**Comment by MassimoVilla** [comment]
The distinction between additions (or better _additiones_) and _Varia_ comes from Ethio-SPaRe guidelines.
Additiones are very often later than the writing of the main text, they mark the secondary life of the manuscript as the latter is used as a repository of documentary information. They are usually written in a different hand than that of the main text. Additiones typically are: donation notes, ownership notes, purchase notes, land grants inventory lists of books and items, genealogies, foundation charters, commission notes, short poems, records of official character. 

Under _Varia_, Ethio-SPaRe used to list the following phenomena, which simply concern the copying process or are more trivial:
- the title of the work written on the front board or cover, sometimes with blue or black paint or ink;
- the internal number of the book in the monastic library;
- the midpoint in the "Psalms of David";
- the presence of stamps of the owning institution;
- the scribe reduced the size of his handwriting to accommodate the end of the line (fols. ...).
- the scribe used compressed script, sometimes to accommodate lines written over erasure (fols. ...).
- Part of the line is taken up or taken down (e.g., in the Psalters), fols. ....
- Glosses written in the margins of fols. ....
- the so-called _tämälläs_-sign, in the shape of a cross (as +), or  two perpendicular lines (as ┴ or├), indicating the place where the omissions (written in the upper or lower margin), belong: fols. __.
- Omitted letters, words, lines or passages inserted interlineally, in the margins, at the beginning of the lines (fols. ...).
- Erasures and corrections written over erasures (in the main hand or in a recent hand): fols. ....
- Erasures marked with thin black and red lines (fols. ...).
- Corrections immediately indicated by the scribe through thin series of dashes above and below the letter of the words (fols. ...).
- Spaces for rubricated names left unfilled (fols. ...).
- Unfilled spaces marked with thin black lines (fols. ...).
- Cues for the rubricator written in the margin (e.g., small numbers), fols. ...
- Erased names, names secondarily written over erased names, often in the supplication formulas.
- monthly or daily readings are usually indicated by writing the names of the months and weekdays in the upper margin of the fol., sometimes within frames.
- Pen trials, notes crudely written in pencil or pen;
- devotional images sewn between some fols.
- scribbles and doodles.

**Comment by PietroLiuzzo** [comment]
@MassimoVilla could I add this to the guidelines?

**Comment by thea-m** [comment]
Thank you!

**Comment by MassimoVilla** [comment]
Of course you can add it. You can caopypaste it as it  is, I can edit it later.
