### ISSUE TITLE
creations of records of works

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#114]
cp. the new guidelines for works: 
https://github.com/SChAth/ScAthiop/wiki/guidelinesWork

We need to discuss clear guidelines for deciding when to create records for works (and parts of works, different recensions etc.)
 A proposition is to create a new record for every different version, recensions o.ä. and to express the diverse relations between the records with relation elements.  This should be clearer and leave space for more differing opinions than to try to express the relations within one single record.

**Comment by MassimoVilla** [comment]
I agree with Thea's proposition, but we should leave one "unmarked" record for all those unspecified witnesses of a text: the cataloguers sometimes do not indicate  which recension a given text belongs to. So, for instance, we have to create four records for Gadla Takla Hāymānot: one for the Dabra Libānos recension, one for the Waldebba recension, one for the Hayq recension, and finally one for all those instances where an satisfying description is not provided in the catalogues.

**Comment by PietroLiuzzo** [comment]
could the unspecified directly be linked to the non specific work record?

**Comment by MassimoVilla** [comment]
Of course. I think that the specified witnesses should also be somehow linked (via the sub-records of the recension) to the general work record, so that when browsing within the general record (e.g., Gadla Takla Hāymānot with all sub-recensions) a user would be able to see _all_ witnesses, both the unspecified ones and those belonging to the specific versions of the work.

**Comment by PietroLiuzzo** [comment]
copied this to requirements

**Comment by thea-m** [comment]
Another example to be discussed is the Wǝddāse Māryām, which @MassimoVilla and I have treated differently (see BNFet9 and Bladd16225). Currently, there are in the record of Bladd16225 different records for the readings for each of the days of the week while in BNFet9 I referred to the work record, where the days of the week are shown as <div> in the body.  
(This was the work which inspired the following paragraph from the guidelines:
A further example: a text which is made of parts which can occur in different orders within different manuscripts. This will have 1 Work record, describing the ideal or majoritarian, or standard sequence, while each witness (Manuscript) will contain the specific order of the parts in it. )

**Comment by MassimoVilla** [comment]
Thank you @thea-m for this warning. I probably missed the paragraph in the guidelines and the specific discussion (as well as treatment of the Ms items in BNFet9). Please confirm me whether Thea's treatment is the proper one.

The same should apply to the Maṣḥafa gǝṣṣāwe (BLadd16249) and its 13 monthly work records that I have just created on the drive.

**Comment by PietroLiuzzo** [comment]
confirmed 💯 . I believe this was modified after your work on that file @MassimoVilla ,  so the issue here is actually the still _liquid_ form of the guidelines. probably when you looked there the paragraph simply did not yet exist! This involves now some reworking, but it will settle with time.

**Comment by MassimoVilla** [comment]
No problem indeed! Better now than after two or three similar MSS. Thank you both for your prompt advices.

**Comment by PietroLiuzzo** [comment]
@thea-m @MassimoVilla is this now satisfactorily documented in the guidelines? if so, could you please close the issue?
