### ISSUE TITLE
kw, gw, ḫw and qw

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#118]
the way this is done now in xml is invalid. we introduce a semantic information for a rendering one. we should instead use appropriate glyphs for each of these

**Comment by eu-genia** [comment]
unfortunately no single glyph exists - we could consider using ʷ (modified w 02B7) for all labiovelars

**Comment by PietroLiuzzo** [comment]
I have updated the guidelines accordingly as this seams a neat solution. I will also add this to codetemplates, so please tomorrow morning all update codetemplates in oxygen.
