### ISSUE TITLE
work overview

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#120]
Cf issue #114:
I was wondering whether we could make a small overview somewhere about the already described works which maybe weren't obvious in the way they were treated (i.e. the Weddase Maryam example, where someone creating a new description without knowing of the existing ones probably wouldn't come to the same result...And it had taken me quite some time to figure out the Gospels-tituli etc embedments, which could have been done very quickly had I started with the right example to follow). It's probable that similar cases will come up in the future. 
Maybe we could just add a remark to the Google spreadsheet with a reference to a ms record where the work in question has already been described, whenever we feel that it could be helpful for other cataloguers.

**Comment by MassimoVilla** [comment]
One question to @thea-m (I hope it is not off topic here): have you already described a Maṣḥafa gǝnzat? I am doing it right now and I would like to avoid double treatments of the same work, as previously arisen.

**Comment by thea-m** [comment]
No, I haven't. Could you add your manuscript to the spreadsheet so that I'll be able to refer to it easily if i'll describe a Maṣḥafa gǝnzat?

**Comment by MassimoVilla** [comment]
Perfect, I have done it. Unfortunately I don't think that MS is a good example to be taken as a reference. The description made by the cataloguer does not fit properly the Ethio-SPaRe descriptions. Perhaps the cataloguer did not recognize subparts of the work currently known under different titles.

**Comment by PietroLiuzzo** [comment]
I would suggest adding these examples to the guidelines with links to the records. the app can already show witnesses, should it also selected related works (contains/isPartOf/isTranslationOf, etc.)?

**Comment by PietroLiuzzo** [comment]
coming back to @thea-m first message. is this now solved? re-reading it makes me wonder although. if I am describing a mss and I link to a work which has already been described, don't I see immediately opening that file that it has been described? why should I start again with a new description?

**Comment by PietroLiuzzo** [comment]
#72

**Comment by thea-m** [comment]
I think it is solved, @MassimoVilla ?

**Comment by MassimoVilla** [comment]
Yes, I think so
