### ISSUE TITLE
Missing syllables in the transcription table in the guidelines?

### ISSUE THREAD

**Issue by FrancescaPanini** [SChAth/ScAthiop#124]
In the transcription table in the guidelines there are only 26 sillables/ fidel for which the transcription is indicated. Is it possible to add the missing ones, please?

**Comment by PietroLiuzzo** [comment]
yes, my competence of geez is not enough to add such list. perhaps @sologebre could reply with a list of the letters which are missing there and their translitteration? I would then be happy to update the table accordingly

**Comment by eu-genia** [comment]
Labiovelars: 
ቈ qʷa
ኈ ḫʷa
ኰ kʷa
ጐ gʷa

Affricates:
ቨ va
ቸ ča
ጀ ǧa
ጨ č̣a 
 ቐ q̲a
ኸ ḵa

Palatalized:
ሸ ša
ኘ ña
ዠ ža

**Comment by eu-genia** [comment]
(with the exception of labiovelars, present in Ge'ez, the others may only occur in Amharic/Tigrinya)

**Comment by eu-genia** [comment]
and, @PietroLiuzzo - when you update the table in the guidelines, please remove "IN PRACTICE: render it with ʿA, ʿa" etc etc - this is not for the guidelines but for the automatic conversion
