### ISSUE TITLE
Institutions as place records

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#125]
There are many place records that are in fact of institutions (monasteries and churches). Should we continue using these records or create new institution records for them? The later would seem logical and was already suggested by  @PietroLiuzzo if I remember correctly. Is there maybe a way of automatically creating an institution record for those place records in the spreadsheet which have the identifiers church or monastery?
There might be an issue then of changing references in files, but this should be manageable.

**Comment by PietroLiuzzo** [comment]
theoretically all monastries and churches in places have also a parallel in Institutions. the two lists have different origins, Places comes from EA indexes, while the Institutions list is an export of the records in EthioSpare for institutions. 

I would suggest to proceed as follows: 
1. if the institution record does not exist, create one and assign an id.
1. leave the place record there, check the already existing references to this place . This can be done either with xpath in Oxygen or on the website looking at related entities.
1. modify those references that actually point to an institution and not to a place, if any.

with regard to automatically creating an institution record for all churches and monastries in Places: is it true that all those with no exception are also institutions holding manuscripts?

**Comment by PietroLiuzzo** [comment]
moving answer to guidelines
