### ISSUE TITLE
Zotero Bibliography Guidelines

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#128]
Zotero Bibliography Guidelines
-	When adding titles to the EthioStudies Group bibliography please make sure you follow the simple rules:

1. 	Make sure that the entry is not there already. And make sure that you choose the correct publication type (Journal article, Encyclopedia article, etc.).
2. 	The titles must be quoted in full (not abbreviated), in the way they appear on the frontispiece. All diacritics must be preserved.
3. 	The names of all authors, editors and translators must be provided - in full and as they appear on the book. Make sure that you enter editors as editors and authors as authors, not e.g. editors as authors in the mask. All diacritics must be preserved. For titles in oriental languages please provide the scientific transcription.
4. 	In a multi-volume publication, each volume is a separate entry, DO NOT merge volumes in one entry. Same is valid for article series. Each separately printed piece is a separate Zotero entry. Each volume gets a SEPARATE TAG.
5.     In case of multiple reprints: always provide and primarily quote the first version. Note that e.g. with CSCO the older series volumes are not printed with Peeters in Louvain, and have different series numbers – the original series numbers (Ser. II, **), publication place (most often Parisiis), publisher and year must be provided. All later reprints (Louvain, in the 1960s, with the usual CSCO/SAe numbers) are separate, additional, Zotero entries.
6. 	If you import citations from an online source (e.g. worldcat.org or JSTOR) make sure that they are correctly imported and complete, Never import from specific library catalogues as you may inherit too many mistakes and you risk to import a compilation created only in that specific library and actually not existing elsewhere. Do not import any library-specific data like shelfmarks, buildings, etc.
7. 	Always provide the series (full title) and the series number when they exist. For series+subseries combinations, the subseries has to go with the series number (e.g. Series: Corpus Scriptorium Christianorum Orientalium, Series Number: 552, Scriptores Aethiopici, 101).
8. 	Always provide the place of the publisher – in the FORM THEY APPEAR ON THE COVER – i.e. for old books e.g. “Lugduni Batavorum” and NOT “Leiden”
9. 	Always provide the publisher in the form he appears on the cover (e.g. “Ex officina Danielis & Abrahami à Gaesbeeck” and not simply “Daniel & Abraham” as modern catalogues may list)
10. 	Most books can be found in HLCES/AAI/Stabi – check the physical books. Some older books can be found on Googlebooks and/or Archives, and articles on JSTOR and other repositories. In cases when the publication is available online add URL/DOI in Zotero mask.
11. 	For related publications (translations, reprints, etc): you can establish relations with Zotero. 
12.  For quoting in publications of the HLCES: use the Hiob Ludolf Centre for Ethiopian Studies style provided in Zotero repository ([https://www.zotero.org/styles?q=hiob%20](url)) – when you export your bibliography with this style make sure it corresponds to the appearance foreseen by the guidelines (e.g. here: [https://www.aai.uni-hamburg.de/en/comst/publications/bulletin.html](url)) - if not, maybe something is entered wrongly.

**Comment by PietroLiuzzo** [comment]
adding this to guidelines
