### ISSUE TITLE
handling of similar manuscript with listBibl type mss

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#135]
the current solution involves the use for similar manuscript of a list Bibl containg references to manuscripts. 

This seams to me now superfluous, as the same could be done with `ref` elements as described in the guidelines without breaking anything else. 

This affects only one file currently in the manuscript repo and 3 in persons, because I can modify all the ES files can be modified harmlessly

I will then relax the rule about "corresp in bibl only into listBibl type mss, so that it is fully usable

please @eu-genia tell me if you see anything against this change.

**Comment by eu-genia** [comment]
yes i think you are right, in the persons these are links to where the persons are mentioned in the mss, not useful as the info can be taken from the mss records; in the ms again it is rather about the text

**Comment by eu-genia** [comment]
we still possibly may need listBibl of mss type on other occasions...

**Comment by PietroLiuzzo** [comment]
I am only going to remove the rule which says corresp is to be used only there and I will update the guidelines about lists of related mss
