### ISSUE TITLE
Mss titles

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#148]
What should be the standard for the titles of ms records? The normalized titles of the works contained in the ms? Common English translations?
In the case of mss with a great number of works (e.g. several small prayers), should every single item be written in the title or could they be summarized for instance as "Prayers"?

**Comment by PietroLiuzzo** [comment]
My take on this is that the title in titleStmt for a MS works as a better filename then the necessary id. so it should be anything that describes briefly and unambiguously the contents. perhaps then a half way between prayers and all the titles...

**Comment by thea-m** [comment]
From meeting: Titles will be added only in transliteration, if there are too many items which can reasonably be grouped together, this will be done
