### ISSUE TITLE
Foliation in Ethio-SPaRe conversion

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#149]
Notes on foliation, sometimes present in E-S mss 
e.g. http://mycms-vs03.rrz.uni-hamburg.de/domlib/receive/domlib_document_00000432 

>  	Fol. 139 mistakenly numbered as 140. Henceforth the erroneous folio numbering continues up to the end of the Ms.

Were lost on conversion, should go into the `foliation` tag

**Comment by PietroLiuzzo** [comment]
#166

**Comment by PietroLiuzzo** [comment]
#79
