### ISSUE TITLE
people mentioned in particDesc 

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#152]
From the guidelines:
To specify important people related to the manuscript we will use a particDesc with a list of pointers to names with a specific role. Allowed value of role here are

```
donor
scribe
other
...
```

Who are the people who should be mentioned here? Only those who are in a direct relation to the manuscript as the scribe or donor or also people mentioned in the manuscript (donors of objects, subjects of administrative notes or condemnations etc?)
Since everyone mentioned in the manuscript is anyway referenced and searchable, a restrictive approach could be reasonable

**Comment by MassimoVilla** [comment]
I have used so far a restrictive approach: only donors/owners and scribes of the MS itself.

**Comment by thea-m** [comment]
Added to guidelines: 
Here it is enough to enumerate the scribe, owner, donor and patron, not everyone mentioned in the manuscript.
Please close if this is fine @eu-genia

**Comment by thea-m** [comment]
This seems actually not to be in accordance with the TEI guidelines:

"All the person elements referenced by a particular document set should be collected together within a listPerson element, located in the TEI header. "

Should we change our guidelines then?

**Comment by PietroLiuzzo** [comment]
True, but we use that into our project for a different reason and we introduced it during the process of transformation of ES record where these information are stored in separate database fields. if the donor, scribe, etc. are always also mentioned elsewhere, this portion of the file could be simply omitted. The listing in the proper TEI file, can then be done from such data. or am I missing something of the issue ?

**Comment by thea-m** [comment]
They are not always mentioned with their role names, i.e. in a Donation Note "X donated the manuscript to Z". It is not encoded at all who is the donor and the receiver. 
We could of course change the guidelines in order to ensure to always encode the role somewhere.

If all persNames would be extracted, wouldn't it be confusing to possibly have the names of kings used in datings, or of Biblical persons alongside with scribes, donors etc.?

If differing from TEI guidelines is no problem, we could just leave it we had agreed upon.

@DenisNosnitsin1970 had also a case where there was no information in the catalogue but the name of the scribe, which I proposed to him to simply add into `<listPers>` (IVvostochn614 - though upon looking at it again this could maybe be added together with the information "the name of the scribe erased, but still can be assumed" from `<condition>` into an addition "extra")

**Comment by thea-m** [comment]
From discussion with @PietroLiuzzo: 
In the future, the role should be added to the PersName where relevant in the description and then doesn't need to be repeated in <listPers>. If there is no sensible place within the description, then this information can also be encoded in <listPers>.
Old files can be left as they are. 
(Information as "The name of the scribe has been erased" actually belongs to the text, which we don't have for now. So it will stay as extra in additions.)

**Comment by thea-m** [comment]
Added to guidelines
https://github.com/SChAth/ScAthiop/wiki/guidelines#profile-description
https://github.com/SChAth/ScAthiop/wiki/guidelines#in-text-placename-and-persname
