### ISSUE TITLE
Books without Authors

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#153]
Entries in Zotero that don't have an author (such as bm:Abushaker1962 or bm:1993Mashafa) are shown logically in the preview with only their date, i.e. 1962 or 1993. Could this be done differently? Or should the Zotero entries be made differently? (Similar for entries without a date, bm:TasfaQandil)
Is there a Zotero guideline for this case?

**Comment by thea-m** [comment]
(Editor for bm:1993Mashafa found, but the question remains)

**Comment by eu-genia** [comment]
maybe it would be better anyway if in the visualization we see the references in full and not abbreviated to name-year

**Comment by eu-genia** [comment]
at least for Modus baptizandi... I would put Tasfa Seyon / Petrus as the author

**Comment by eu-genia** [comment]
(i have now corrected the Modus baptizandi adding the full title, correcting the name to Aethiops (not Aethyops) and adding a link and a reprint)

**Comment by thea-m** [comment]
Thank you, as a matter of fact, what is the guideline for authors whose names have several versions? The form appearing on the cover? Can variants be given? for instance Assemani, known today usually as Assemani but Assemanus on his books

**Comment by eu-genia** [comment]
we have to give it a think... the best would be both but in which order...

**Comment by PietroLiuzzo** [comment]
The rendering of the bibliographic citation is very basic for now it takes author and year and if author is not present looks for editor only. I would not in any case modify the zotero entry to fit the software behavior. We can print the full entry using Eugenia's style, or you can specify what to do with entries without a author/editor and year and I will modify the transformation to return the desired citation pointer.

**Comment by eu-genia** [comment]
i would print the full citation

**Comment by PietroLiuzzo** [comment]
this is the current app and preview behaviour

**Comment by eu-genia** [comment]
the question remains for us how to deal with persons going under various names in Zotero: for the moment the best rule to follow seems to provide the name as it is given on the cover/frontispiece of a specific book; it is however then difficult to sort/identify the references belonging to the same author if a different name form/transcription/nickname have been used. should we add a second spelling in Zotero as if it were a "contributor" e.g.? would not show in citation but at least one could search and filter inside Zotero. or do we always add a bracket if we know that the main variant is different?

**Comment by thea-m** [comment]
Could alternate names be added as tags?
