### ISSUE TITLE
blank leaves locus

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#154]
Can blank leaves be indicated with a locus?
Currently the information can only be entered like this:
 <measure unit="leaf" type="blank">4</measure>ff.: 44, 47, 65, 66

**Comment by thea-m** [comment]
`<measure unit="leaf" type="blank">4</measure>ff.: 44, 47, 65, 66`

**Comment by PietroLiuzzo** [comment]
yes, you can always use locus instead of ff. watch out for the whitespace.
