### ISSUE TITLE
msItem or addition?

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#155]
If a proper work with its own ID has been added later to a manuscript, should it be an addition or a msItem by a different later hand? 
For an Example, BNFet71:
 https://archive.org/stream/manuscritsorient00bibl#page/78/mode/2up

**Comment by eu-genia** [comment]
you mean the inserted fol. 106? This is a composite manuscript - since the folium was inserted at a later time it is another msPart

**Comment by thea-m** [comment]
Thank you! And I also meant all the works added later (listed by Zotenberg under a-i)

**Comment by eu-genia** [comment]
ah ok these are additiones/guest texts but most should have their work ID (not the lists of fruit of course)

**Comment by thea-m** [comment]
Ok, I had written them like this, could  it stay so?:
   ```
  <item xml:id="a11">
                  <locus from="117r"/>
                  <desc type="PoemSalam"><title type="Complete" ref="LIT2756RepCh40"/></desc>
                  <q xml:lang="gez">
                    <note>The following is the incipit:</note>
                    <lb/>ሰላም፡ ለከ፡ መምሕረ፡ ሃይማኖት፡ ዮሐንስ፡ ወምዑዝ፡ ምግባር፡ እምኮል።
                    <lb/>ከመ፡ ኮነ፡ ሥጋ፡ መድኀኒነ፡ ቃል።
                    <lb/>ዘጸሐፍከ፡ ውስተ፡ ወንጌል።
                  </q>
                </item>
```

Maybe we could add a type to desc for

**Comment by thea-m** [comment]
a type of desc for complete works that don't happen to be a salām

**Comment by eu-genia** [comment]
I think we can use something generic like "GuestText"

**Comment by thea-m** [comment]
I created the file, @PietroLiuzzo can add it later

**Comment by thea-m** [comment]
Added to guidelines
@MassimoVilla

**Comment by PietroLiuzzo** [comment]
Could I please have also a definition of GuestText to add in the schema in order to avoid the use of generic terms when there could be a more specific one? @thea-m @eu-genia

**Comment by eu-genia** [comment]
the question is if we can foresee all possible specific texts that can be added... it can be a single psalm, a malk-hymn, another poetic composition, a miracle fragment, someone's genealogy... of course we could try to have a full repertory of all possible text-types that may possibly circulate... i was thinking of creating GuestText and then after a while looking through all GuestTexts to see if one can create specific categories. but maybe we should do the other way around.

**Comment by PietroLiuzzo** [comment]
this issue was already discussed and sorted. GuestText is among the values and will have a definition within the completion of #175
