### ISSUE TITLE
langUsage German

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#156]
We need to add German to the languages of langUsage

**Comment by eu-genia** [comment]
you can use "de"

**Comment by thea-m** [comment]
Could we maybe add automatically   `<langUsage></langUsage>` including all the languages which are regularly used (Geez, Amharic, Latin, Arabic, French, Italian, Coptic, Syriac, German, Greek...?) to all files? Since it doesn't matter if there are more languages there than are used in the file, but would save time on adding individual languages and remove the risk of using languages in the file but forgetting to define them

**Comment by PietroLiuzzo** [comment]
We could, but then you would have to delete each time the wrong information, which could be more or less the same amount of work. I could add a code template to add language statements, if that makes it easier. you could then add the whole xml line in one click from the list of codetemplates. let me know if that would do.
