### ISSUE TITLE
Composite mss, inserted parts

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#158]
How can we encode the case in which a part of a manuscript has been inserted into another, possibly into the middle of a work? The question is to clearly show the insertion while also showing the connection between the two parts separated by it. 
In ethiospare, this case has been noted like this:

I) Täˀamrä Maryam "Miracles of Mary" (fols. 1ra-29vb, 34ra-39rb)
I-1) Mäṣḥafä śərˁat, Introductory rite of al-Muˁallaqah (fols. 1ara-6ra)
I-2) Introductory exhortation and hymns (fols. 6ra-9ra)
I-3) ˀƎsäggəd läki wä-ˀəweddəsäki... "I worship Thee..." (fol. 9ra-vb)
**I-4a) Täˀamrä Maryam "Miracles of Mary": 31 miracles (fols. 11ra-29vb), incomplete
II) Mälkəˀa sänbätä krəstiyan “Image of the Sabbath of Christians” (fols. 32ra-33ra)
I-4b) Täˀamrä Maryam "Miracles of Mary": 5 miracles (fols. 34ra-39rb)**
III) Täˀamrä ˀIyäsus "Miracles of Jesus" (fols. 39rb-42ra)

Can we reproduce this kind of notation? 
A suggestion by @MassimoVilla was to note them as p1.1, p1.2 and p2 (the inserted part), where p2 would in the file come after p1.2 even though it actually is located between p1.1 and p1.2

**Comment by PietroLiuzzo** [comment]
my two cents, and please forgive my terminology: 

if the unit where the newer one has been inserted is not broken, does it constitute two parts? I would not always consider a break in the text sequence as a break between codicological units.

I would understand that there are two physical parts only here, and only the locus changes. 

p1.4 fols. 11ra-29vb, 34ra-39rb
p2. fols. 32ra-33ra


are the items in this list numbered I-1, I-2 actually other parts or msItems in the msPart?  in case there is no physical break, but the II text is inserted, then the same would apply to msItems.

btw: what is at 30ra-31vb?

**Comment by eu-genia** [comment]
Pietro is absolutely right here: this is a composite ms
But it is not composed as he thinks

I guess this is MHG-021

E-S describes it correctly (in its way): 
<I(11; s.l.: 1, stub after 10/fols. 1r-10v)> – II(10/fols. 11r-20v) – III(9; s.l.: 1, stub after 9/fols. 21r-29v) – <IV(13; s.l.: 4, stub after 10/fols. 30r-42v)>

meaning there is one unit with quire 1, another unit with quires 2 and 3 and one more with 4

it has to be controlled with the images

E-S descriptions sometimes skip pages ;) I have had this also in other mss also f. 10

**Comment by eu-genia** [comment]
have checked the ms

first unit 1-10
f. 10 is blank, it is the last leaf of the first unit

second unit ff. 11-29

third unit ff. 30-42 - no physical breaks here
the first bifolium was originally blank (end leaves of the third unit)
f. 30r is blank
on ff. 30v-31a a guest text is inserted (listed in E-S among additions, correctly)
f. 31v is blank 
ff. 32r-33r has the text on the sabbath (34 r is actually half leaf half stub)
f. 33v is blank
f. 34r the miracles of mary continue SAME HAND AS THE SABBATH text


so in this case the E-S description is fully correct, the question of Dorothea is not really applicable here. We have here three manuscripts put together, two of them, the first and the third, have different sets of the miracles of Mary.

**Comment by eu-genia** [comment]
@thea-m @MassimoVilla

**Comment by thea-m** [comment]
Thank you very much for the detailed clarification, my example wasn't wisely chosen. 

My question had arised from BNF eth 107
https://archive.org/stream/manuscritsorient00bibl#page/98/mode/2up

and the inserted fol . 106  in BNF eth 71, which had been mentioned in issue 155.
https://archive.org/stream/manuscritsorient00bibl#page/78/mode/2up

Of course Zotenberg doen't give all the information present in Ethiospare, so should I encode this considering that the insertion hasn't broken the older unit (which would be one msPart with two loci), as Pietro suggested?

**Comment by eu-genia** [comment]
dear Dorothea, as I believe I already commented elsewhere: an inserted folio is clearly an additional codicological unit. it is different from an inserted text. there were no inserted folios in the Ethio-SPaRe example you had. so you have one mspart without the insertion and the second mspart with 1 inserted folio.

**Comment by eu-genia** [comment]
this is what Pietro suggested, two distinct msparts, one with two loci, and one with one

**Comment by thea-m** [comment]
Added to guidelines

**Comment by MassimoVilla** [comment]
The first codicological unit of ms BAVet15 is a Psalter, whose internal arrangement is not (as usual) the 151 Psalms (= LIT2000Mazmur) and the 15 canticles (Moses I, Moses II, Moses III, Hannah, Hezekiah, Manasseh, and so on).
Instead, here we have:
- Psalms 1-30, then three canticles (Moses I, II, III), then readings and prayers for the third hour;
- again, Psalms 31-60, three canticles (Hannah, Hezekiah, Manasseh), then readings and prayers for the sixth hour;
- Psalms 61-90, three canticles, then readings and prayers for the ninth hour;
- Psalms 91-120, three canticles, then readings and prayers for the twelfth hour;
- Psalms 121-151, then the last three canticles.

How can we encode this textual arrangement, which intersects location and internal structure of the text?
If I strictly follow the actual location of the texts 12 canticles would not be nested as subparts of LIT1828Mahale, i.e. Maḥālǝya nabiyāt.

**Comment by thea-m** [comment]
A way to follow the actual location while keeping all canticles nested within LIT1828Mahale would be to change the LIT1828Mahale record from containing the canticles in relations to listing them as textparts. Then LIT1828Mahale could be encoded here in the same way as the psalms. 
Do single canticles occur independently (outside their original respective places in the Bible of course)? In our records so far not it seems

**Comment by MassimoVilla** [comment]
I do not think they occur independently. So, it seems reasonable to "downgrade" the single canticles to textparts and correct the Ms records already existing. I can fix it.

**Comment by PietroLiuzzo** [comment]
this sounds to me like previous cases where we have done like this. so +1. just note that the theoretically normal order should be in the LIT file, whereas the Mss should have the parts listed as they appear with reference to the sub id in the LIT file.
