### ISSUE TITLE
works composed of several extracts

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#160]
From discussion with @MassimoVilla on works composed of several extracts (Haymanota Abaw)
There are some issues to discuss:
- In keeping with the guidelines, we are creating now textparts within the work record for each extract, which we'll refer to in the manuscript record under rubric (before the discussion on the creation of work records, individual records had been created for all extracts)
- extracted from the EAE index, there are already records for some of those works. If this is a work which exists in Ethiopic literature only as an extract in Haymanota abaw (for example, Against Eunomius by Basil), should this work record be kept as an abstract record and be referred to in the Haymanota abaw record? Or should it be deleted since it isn't really an independent work in Ethiopic literature? 
- If we delete these abstract records, information on authorship, original versions etc. will be entered as relations corresponding to the textpart in question in  the Haymanota abaw record (which will become quite enormous)

A similar case to be discussed would be the synaxar, are there others ?

What do you think?  @eu-genia @PietroLiuzzo

**Comment by eu-genia** [comment]
following up on today's discussion:
- only texts with independent circulation get first level IDs, all other are textparts
- if a textpart has an individual circulation in other traditions this should be said under the textpart: multuple titles can be inserted, with bibliography linking to the IDs of these titles, relations for the authors of the titles, etc.
- the existing records inherited from the EAE index that do not have independent circulation in Ethiopic should be deleted, but their IDs should remain in the Google Spreadsheet, struck out with a comment specifying the new derived ID added

**Comment by eu-genia** [comment]
- if a part of a text also has an independent circulation - it gets an independent first-level ID/record
- texpart divs should also be created for these texts, with a corresp link, in order to show the full content of a collection in correct order

**Comment by PietroLiuzzo** [comment]
copied to guidelines, please check and correct there directly.
