### ISSUE TITLE
ms previously unknown

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#165]
for a manuscript previously unknown in the ES-->BM conversion we created a false bibl containing the string Ms. previously unknown, which was fine then to preserve this information. However this is no bibliographic information and should find another place and be marked with reference to the ES edition as first publication or reproduce this bit of information in a more appropriate way. The text of this note assumes the understanding of "before the ES project" which is not explicit enough IMHO. 

would you be happy with not having at all the listBibl[@type='secondary'] in the `additional` and assuming that if this occurs in a ES record a label should be added in preview which offers a more detailed message like "Manuscript first catalogued by the Ethio-SPaRe project on [date] by [name]"?

another perhaps better alternative could be making a zotero bibliographic record for the ES database and using that in the listBibl as publication reference as this in BM is actually a second edition of those records.

@DenisNosnitsin1970 @eu-genia please let me know what you think about this.

**Comment by PietroLiuzzo** [comment]
@eu-genia  said OK. 

Action: replace the bibl in ES records with the pointer to the zotero tag as in record created by Eugenia

**Comment by eu-genia** [comment]
bm:EthioSpare
