### ISSUE TITLE
Portions of text inserted interlineally

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#170]
While transcribing quotations, incipits and other excerpts we might find (omitted) letters, words, lines or passages written interlineally. 
For instance,
ቃል፡ ዘ<ማ>ርቆስ፡ ፼ወ፯፻ where ማ is "suprascriptum", i.e., inserted interlineally.
How can we tag these portions of text? I can't find a suitable solution in the guidelines.

**Comment by PietroLiuzzo** [comment]
Dear all, please use TEI markup according to TEI guidelines for all these instances. 

We can then distill elements which you have used with examples in our guidelines for future project reference.

in this case I would suggest 

````xml
ቃል፡ ዘ<add place="inline"><supplied reason="omitted">ማ</supplied></add>ርቆስ፡ ፼ወ፯፻

````
If this corresponds to the phenomenon, I will add it to the guidelines and provide support to represent this supplied text with @reason omitted within <>

**Comment by MassimoVilla** [comment]
it perfectly fits the phenomenon

**Comment by PietroLiuzzo** [comment]
or perhaps this can be simply described as text added above the line?? 

ቃል፡ ዘ<add place="above">ማ</add>ርቆስ፡ ፼ወ፯፻
