### ISSUE TITLE
religious orders

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#171]
How can we encode information about a person's spiritual/insitutional affiliation?
Such as XY walda Takla Hāymānot, where Takla Hāymānot indicates the order the monk belongs to, not really the person Takla Hāymānot himself. 
The cases I had until now were monks belonging to the orders of Takla Hāymānot, Sāmuʾel of Waldəbbā or ʾEwosṭātewos.
 Could we maybe encode this as an institution, where we would the clarify in the institution record that not one single physical place is meant (and also add a relation to the founder)?

**Comment by PietroLiuzzo** [comment]
perhaps better a personGrp record for the order of the monks and then link the persons with a relation to the personGrp?

**Comment by thea-m** [comment]
Thank you! I wasn't aware of this possibility. Should we then write the relation in the group record (as in the guidelines) or maybe better in the individual persons' records (in analogy to the author-work relationship)?

**Comment by PietroLiuzzo** [comment]
@eu-genia what do you think?

**Comment by eu-genia** [comment]
personGrp is good, I think relations should go with the individuals.  saws:isMemberOf?

**Comment by PietroLiuzzo** [comment]
added to guidelines
