### ISSUE TITLE
Engravings

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#172]
Available values of @types for decorations are:

- frame
- miniature

I think we should add **engraving**, especially for those MSS produced in European institutions, e.g., now in the Vatican Library.

**Comment by MassimoVilla** [comment]
I have edited the guidelines with the new available value

**Comment by PietroLiuzzo** [comment]
well spotted. decoNote/@type takes an open list of values for which the schema had 24 suggestions. this were not listed in the guidelines! I have added them to the guidelines and added engraving in the schema
