### ISSUE TITLE
Work / 1

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#18]
forse nello schema c’è ma non nel template e non so dove mettere?
quel che ti avevo scritto:
 
per il modello works forse ci servono ancora tipi o simile per vari rapporti fra testi (antecedent, recension, parallel version, part of) – p.e. non so il libro genesi è parte di pentateuco che è parte dell’ottateuco che è parte dell’antico testamento che è parte della bibbia – che avranno ciascuno un proprio ID, che ne dici? come posso poi nei works fissare le date (data di composizione, data di traduzione) e luoghi (luogo di composizione, di traduzione, ecc.)? scusami sono cose che escono fuori appena comincio a cercare di descrivere qualcosa...

**Comment by PietroLiuzzo** [comment]
@eu-genia  Penso che la prima parte della domanda sia ora risolta con l'uso di relation in listBibl.
per le date userei origDate, descrivendo e markando quel che riguarda la datazione dell'opera. se questi nodi anche a te paiono sciolti, per piacere chiudi la issue. grazie!

**Comment by PietroLiuzzo** [comment]
#27 
#16

**Comment by eu-genia** [comment]
possiamo avere una tipologia standartizzata per le date di
- composizione
- traduzione
- revisione/recensione?

**Comment by PietroLiuzzo** [comment]
si. da usare in `date` ?

**Comment by eu-genia** [comment]
direi date e origDate
