### ISSUE TITLE
Guidelines for places

### ISSUE THREAD

**Issue by FrancescaPanini** [SChAth/ScAthiop#185]
The guidelines for places need updating especially with regard to the structure of the placeName at the beginning and the structure to define the geographic location: please refer to LOC1311AksumS for what I think might be a good example.

I also think it would be useful to point out the difference between:
- LOC6569Tegray (Tǝgrāy historical province) vs LOC5932Tegray (contemporary regional state)
- LOC6568Amhara (ʾAmhārā historical province) vs LOC1426Amhara (contemporary regional state)
- LOC3577Gondar (Gondar town) vs LOC6554GondarineK (Gondarine Kingdom)

Thanks

**Comment by PietroLiuzzo** [comment]
#188
