### ISSUE TITLE
Use of GeoNames IDs for "secondary" place records

### ISSUE THREAD

**Issue by FrancescaPanini** [SChAth/ScAthiop#197]
Dear all,
some time ago there was an issue regarding the use of existing external sources for places such as USA, UK, Italy, Paris, etc., i.e. places we refer to in the records but do not "deserve" to be dealt with in this context.

It was suggested that we used external sources such as GeoNames from which info can be automatically pulled.

I gave it a go and I think it is a good solution although some consideration is probably required. I proceded in this way:
1) For places that were mentioned in records but that did not have a LOC file, I simply assigned an ID taken from GeoNames, eg. Berlin is gn:2950159. This ID can be used everytime Berlin needs to be referred to. The IDs I took from GeoNames so far are saved on the Excel doc in Drives.

2) For places that had already an empty LOC file, I took the ID from GeoNames and used it both in the main LOC file with a @sameAs attribute and in the other records that refer to that place. See LOC2085Cairo and the ID gn:360630 as an example. 

I think this work around is useful because we probably have no interest in filling up records for Berlin, Cairo, etc.

Two points deserve attention, I think:
1) How to get the place ID from GeoNames? In GeoNames, you need to run a search and, when you get the list of results, you need to click on the small balloon-like symbol which is next to the place name (NOT on the place name itself): a pop-up window will appear and the ID number is displayed in blue. You need to take the number and add "gn:" in front when you use it in the mark-up. 

2) I came across political entities such as Egypt, France or even Italy that may deserve further attention: the GeoNames record refers to contemporary Egypt, while in our records we may refer to 6th cent. Egypt. Equally, GeoNames refers to the French Republic or the Italian Republic, while our records refer to the no longer existing respective monarchies. For now, I intentionally did not split these records as I did instead for Tǝgrāy (historical vs national state have two separate LOC entries) because I think that that this distinction is not fundamental in this case, but I appreciate your view on this.

If this way to proceed is agreeable, this will probably need to be reflected in the guidelines. 

I hope this makes sense,
Thanks
Francesca

**Comment by eu-genia** [comment]
It shall be important for all toponyms to serialize relations - even if we do not fill the records we still shall need to be able to view e.g. all persons who lived etc in Berlin, or all mss collections in Berlin, or Egypt, or Cairo. Egypt for us, if we speak of it as historical region, is of central importance - e.g. all heads of Eth. Church until recently were Egyptian, so it shall be referred to often. So I would be for LOC entries for all (OK to add GeoLink ID just as we add VIAF ID)

**Comment by PietroLiuzzo** [comment]
syriaca uses a TEI model for attestation and existence which we could simplify and use. Here an example from Damascus. 

```xml
<event type="attestation" xml:id="attestation66-1" notBefore="1224" notAfter="1228" source="#bib66-8" syriaca-computed-start="1224-01-01" syriaca-computed-end="1228-01-01">
<p xml:lang="en">
Attestation of name
<foreign xml:lang="ar">دِمَشق</foreign>
in the
<title xml:lang="en" level="m">Muʿjam al-buldān</title>
of
<persName>Yāqūt al-Ḥamawī</persName>
.
</p>
<link target="#name66-5 #attestation66-1"/>
</event>
<state type="existence" from="-0700" to="2013" syriaca-computed-end="2013-01-01">
<precision match="@from" notAfter="-0700"/>
<precision match="@to" notBefore="2013" syriaca-computed-start="2013-01-01"/>
</state>
<idno type="URI">http://syriaca.org/place/66</idno>
<idno type="URI">http://pleiades.stoa.org/places/678106</idno>
<idno type="URI">http://en.wikipedia.org/wiki/Damascus</idno>
<idno type="URI">http://dbpedia.org/resource/Damascus</idno>
<idno type="URI">
http://www.csc.org.il/db/browse.aspx?db=SB&sL=D&sK=Damascus&sT=keywords
</idno>
```

**Comment by thea-m** [comment]
Example from BnF Éth 153:
` ex <placeName ref="gn:6269131">Anglia</placeName> reverso` 
currently becomes "ex England reverso" in the Preview. Even when the visualisation will be changed to show "Anglia", the mark up will not be accurate, as gn:6269131 refers to the current political entity "England", but the text refers to 17th century England.

**Comment by FrancescaPanini** [comment]
Hallo,
just a note to say that the first round of replacement with GeoNames IDs mainly for contemporary places and for places outside of Ethiopia/ Eritrea has been completed. In the spreadsheet there is now a column with the GeoNames IDs for these places. This was also a first attempt and there will be most certainly some inconsistencies to fix. We are now looking at a solution for historical places on the basis of Syriaca.

Thanks
Francesca

**Comment by PietroLiuzzo** [comment]
#485
