### ISSUE TITLE
information about the scribe etc. 

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#200]
Sometimes there is information about the scribe, donor etc. without the actual quotation being copied in the catalogue. How should this be written? I have so far added it as an "extra" in the additions, i.e.: 

```xml

  <item xml:id="e1">
                  <locus target="#43v #62r #95r"/>
                  <desc>This manuscript part was written by <persName ref="PRS9197Taklase"/> 
of the <persName ref="PRS11232HouseSam"/>
                    for the abbot <persName ref="PRS9170TaklaIy"/>.</desc>
                </item>
```

(i.e. BnF et 134 or 136: https://archive.org/stream/manuscritsorient00bibl#page/204/mode/2up)

(This is also how we added the information "the name of the original owner has been erased and replaced with XY" as has been done in Ethiospare)

If there is no locus or extra information at all, it would be enough to add the relevant information in the `<listPerson>` .

**Comment by PietroLiuzzo** [comment]
Yes, please, add roles for persNames if they are not stated elsewhere. 
the deletion of a name, could be much better encoded in the text transcription. as we don't yet have that, this will have to stay as an indication of the phenomenon. Once there will be such transcription, the file could be updated accordingly.
