### ISSUE TITLE
"extra" information from the catalogues

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#202]
There are many informations in Zotenberg's catalogue which don't directly belong to our project's scope. Should we add this information, and if so, where?

- Especially lengthy descriptions and quotations from Arabic manuscripts (I have mostly skipped these until now, but since they are present in the catalogue I would prefer to encode them). 
i.e.: BNFet 134 https://archive.org/stream/manuscritsorient00bibl#page/200/mode/2up

- Somewhat related: Summaries of works. These could be added in the abstract of work records, but would be quite lengthy. 
i.e.: BnF et 136 https://archive.org/stream/manuscritsorient00bibl#page/202/mode/2up

- There are also many bibliographic references to the works in other traditions (i.e. Acta Sanctorum), obviously 17th-19th century. I have so far added these to the work record, since 1) they don't really belong to information about the ms itself 2) I'm reluctant to lose information present in the catalogue. That way, however, it is not encoded that this bibliographic reference comes from Zotenberg's catalogue.

**Comment by MassimoVilla** [comment]
From discussion with @thea-m , the problem also arises of witnesses in other traditions.
Zotenberg often refers to Arabic or Greek witnesses to works contained in the manuscripts catalogued.  In some instances witnesses of parallel traditions might be somehow relevant and worthy of mention in the work record.
Provided that we do not want to create MSS records of other traditions (which is definitely beyond BM), the question is how/where to refer to them.
We might temporarily add the information as unmarked content in the short summary/abstract of the work, just not to lose that info.

**Comment by PietroLiuzzo** [comment]
There is no problem to refer to a known manuscript outside the collection. if there is a copy online somewhere, enter a ref or a witness with a ref to that manuscript

<ref type="mss" corresp="https://w3id.org/vhmml/readingRoom/view/133001">

https://github.com/SChAth/ScAthiop/wiki/guidelinesWork#witnesses

witnesses can be then described into the element with as much information as you want. I would deem important to enter a relevant reference to the manuscript.

fictitious example:
````xml
<sourceDesc>
            <listWit>
               <witness type="external" corresp="Man Ar 12345">
Man Ar. 12345 cointains this and that 
and is a valuable source of information</witness>
            </listWit>
         </sourceDesc>
````
if a further marking for such witness is needed, we can certainly have it. For example we could have a @type for each tradition.

**Comment by thea-m** [comment]
Updated manuscript and work guidelines after meeting:
- descriptions of Arabic manuscripts should not be copied
- summaries should be copied to the abstract of the work record
- bibliographic references should be added to the work record
