### ISSUE TITLE
Chant modes

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#203]
From discussion with @DenisNosnitsin1970 
It would be desirable to be able to encode the modes of chants, for example Dəggwā hymns (i.e. gəʿəz, ʾarārāy), so that it would also be possible to search for this information. Could this be done?
(I suppose that this information would belong to the text, not the manuscript description - but can we find a way for now, for cases in which we have this information?)

**Comment by PietroLiuzzo** [comment]
@DenisNosnitsin1970 @thea-m would keywords be enough to mark this or is it a deeper type of structure of the text that needs to be retrieved?

**Comment by DenisNosnitsin1970** [comment]
To my opinion, keywords will be enough. 
D.N.


      Von: Pietro Liuzzo <notifications@github.com>
 An: SChAth/ScAthiop <ScAthiop@noreply.github.com> 
CC: DenisNosnitsin1970 <nosnitsin@yahoo.com>; Mention <mention@noreply.github.com>
 Gesendet: 6:50 Donnerstag, 17.November 2016
 Betreff: Re: [SChAth/ScAthiop] Chant modes (#203)
   
@DenisNosnitsin1970 @thea-m would keywords be enough to mark this or is it a deeper type of structure of the text that needs to be retrieved?—

**Comment by thea-m** [comment]
So we need to add gǝʿǝz, ʿǝzǝl and ʾarārāy to the keywords.

**Comment by PietroLiuzzo** [comment]
please add these and organize them properly in taxonomy and in authority-files.
