### ISSUE TITLE
CSCO in Zotero

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#204]
Currently all CSCO works are assigned one tag for both edition and translation, as has been done also in the example in the Zotero guidelines (i.e. bm:Bausi1995Senodos).
It seems reasonable to have separate entries for the edition and translation, which would also make quoting easier.
@eu-genia

**Comment by MassimoVilla** [comment]
I think that having separate tags for the volumes of each CSCO work would also fit our schema, which allows to have separate contents for `<listBibl type>`, i.e. "editions" and "translations" respectively.
In some cases the year of publication also differs between edition and translation.

**Comment by eu-genia** [comment]
yes, sure, you are right, we must split them.

**Comment by thea-m** [comment]
Thank you!
