### ISSUE TITLE
Place types

### ISSUE THREAD

**Issue by FrancescaPanini** [SChAth/ScAthiop#207]
Hello,
working on the place records, I noticed there may be some complexity around the place type categories we use. For instance, how to distinguish in a coherent manner between town and city or the fact that you can use categories like region, province or country in different ways. Ex. how big or important a populated conglomerate must be to be classified as a city? England is not a region like Piedmont while Piedmont is far from being a Regional State like Amhara. 

I found interesting the way GeoNames classifies places, e.g. indipendent political entity (Italy, UK, etc.), first order administrative division (eg. England, Piedmont, Amhara), second order administrative division, seat of a first/ second/ etc. order administrative division, etc. I think this classification has the advantage of being more neutral and less dependent on names like region and province that are used differently in different administrative environments as well as used with narrow and broader meaning.

Thanks
Francesca

**Comment by eu-genia** [comment]
I would probably just use "town" and avoid "city" - in English historically the word "city" actually means there is a cathedral. Everything without a cathedral is a town. 
Independent political entities, as we know, are not stable in time either. Do we create multiple entries for regions that change their independence characteristics across time? California used to be a semi-independent colony of Spain, just as an example. Finland was part of the Russian Empire. There were times when Scotland was not part of UK. I am not sure this really is something that resolves the fuzziness. I think GeoNames do not have any historical approach at all.

**Comment by PietroLiuzzo** [comment]
#485 will resolve this as well.
only for places in ethiopia we will provide such informations in elements `state` and `event`
