### ISSUE TITLE
Entry for Ludolf's Lexicon

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#208]
BNFet153 and BNFet154 (https://archive.org/stream/manuscritsorient00bibl#page/254/mode/2up) are the first edition of Ludolf's Lexicon, interleaved with many additions and corrections by Ludolf and Wansleben. 
They are therefore not strictly speaking Ethiopian manuscripts, but nevertheless of interest. Should entries be created for our project (and if so, should a difference from the other manuscripts be indicated?) ?
@abausi  @eu-genia  @DenisNosnitsin1970  @MassimoVilla

**Comment by abausi** [comment]
I think yes, entries should be created: we normally take care of 
"Aethiopica" in the broader meaning, which also includes items like this.

Many thanks,

A.B.

Il 15.11.2016 09:47, thea-m ha scritto:

**Comment by thea-m** [comment]
Thank you!
