### ISSUE TITLE
Interlinear additions/translations

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#212]
How can we encode information on interlinear text?

I have had so far:
- interlinear corrections or glosses added later (could this be added to "additions" as extra (as stated now in guidelines) with` @rend "interlinear"`)?
- interlinear transcriptions or translations (see BnF Eth 150 and 151 https://archive.org/stream/manuscritsorient00bibl#page/254/mode/2up)
- (I believe we agreed to add interlinear musical notation to `<notatedMusic>` in the description?)

**Comment by PietroLiuzzo** [comment]
These information belong to the text transcription IMHO. what you want to record following Z is that there are such phenomena somewhere, not the phenomena themselves. I would report the sentence of Z about this interlinear and marginal additions in a note or in one or more addition items
