### ISSUE TITLE
<certainty> preview

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#213]
`<certainty>` is currently visualized with a pop up "The certainty about the value of ../@ref is low" (depending on the content, obviously). A visualisation understandable to normal users would be very nice, i.e. value of ../@ref = title in this case

**Comment by PietroLiuzzo** [comment]
@thea-m if you state with `<certainty>` that the @ref is uncertain to some extent, you are saying something more precise than simply that the title is uncertain. I agree that the text of the popup need to be more readable as in many other places, but it is in my opinion a bigger question. One option could be to use the definitions in TEI directly. in this case it would be something like 

     the certainty of the value of the attribute referring to such entity is low

another option could be to define each case in which we use this and stick to that usage only. In this case for example there is a title but it is uncertain what it refers to.
