### ISSUE TITLE
translated names in the catalogues

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#215]
Occasionally the cataloguers translate names, writing for example "Étienne" when the person in question can be assumed to be called ʾƎsṭifānos. Could we find a standardized way to encode this phenomenon in the person records? 

Re-translating the names could be possible, but with a degree of uncertainty, since of course there are possible variants.

For example, a try:

```
<persName xml:id="n1" xml:lang="gez" cert="low">እስጢፋኖስ፡</persName>
<persName xml:lang="gez" type="normalized" corresp="#n1" cert="low">ʾƎsṭifānos</persName>
<persName xml:id="n2" xml:lang="fr" resp="PRS10747Zotenbe">Étienne</persName>
```

**Comment by PietroLiuzzo** [comment]
in almost certain cases, yes, unless it is really uncertain, than we do nothing.
