### ISSUE TITLE
subcollections

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#217]
especially persons and places collections are unusable as such, and should be organized in possibly meaningful subcollections. suggestions which do not hinder the flexibility of typologies are welcome. alphabetic and numeric are off course the two most plausible options.

**Comment by PietroLiuzzo** [comment]
@thea-m suggest numeric

**Comment by thea-m** [comment]
manuscripts slowly starts as well to become quite long (but still usable). Here an organisation into collections or institutions would make sense

**Comment by PietroLiuzzo** [comment]
@thea-m @DenisNosnitsin1970 @MassimoVilla @eu-genia please note that the subcollections structure has changed. Update your repos and watch out for problems you encounter in the app navigation, search, etc. I will now go on with this change also for persons and places

**Comment by PietroLiuzzo** [comment]
the git hook should work properly as you add new collections and subcollections, but please keep it checked and report issues where it should fail. I did not reorganize yet in subcollections the new ES folder, as this can be probably done while updating the files

**Comment by PietroLiuzzo** [comment]
@thea-m @sologebre @FrancescaPanini @eu-genia @MassimoVilla @DenisNosnitsin1970 

Persons, Places, Works collections have now also subcollections of 1000 items more or less each.

Please update your repositories before any new commits.
