### ISSUE TITLE
role information in person records

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#219]
In person records automatically created from spreadsheets (and generally):

I believe it makes sense to change `<occupation>scribe</occupation>` (which is lacking a @type anyway)  to 
`<relation name="saws:hasWritten">`. This would then make  `<relation name="lawd:hasAttestation"> `obsolete.
The information "owner" could similarly be expressed with  ` <relation name="saws:hasOwned">`.
Would it make sense to create a similar relation for commissioners and donors?

Or is all of this obsolete as scribes, owners and commissioners already are marked up with @role in the manuscript records?

**Comment by thea-m** [comment]
somewhat related: do we have a specific `relation `for the relationship between scribe and commissioner?
is this snap:ProfessionalRelationship? 
(I cannot open snap definitions, where can I find them?)

**Comment by thea-m** [comment]
Correction
`<relation name="saws:hasWritten">`  seems inappropriate here as it is defined as "Person hasWritten LinguisticObject Scribe hasAddedMarginalia"
What I meant was more precisely:
isCopierOf

**Comment by PietroLiuzzo** [comment]
the information is already in the manuscripts you don't need to add it, but it is of course nice if you do.
snap:isCopierOf is ok for scribes and shall contain in passive mss ids or subids.
snap:ProfessionalRelationship is ok for scribe=donor rels
I can crawl the records with both 
`<occupation>scribe</occupation>` and `<relation name="lawd:hasAttestation"/>` to change them in `<relation name="snap:isCopierOf" active="THISRECORD" passive="whatisnowinrelation"/>`

**Comment by thea-m** [comment]
snap:isCopierOf is not yet included in the schema

**Comment by PietroLiuzzo** [comment]
**saws**:isCopierOf is now there
