### ISSUE TITLE
error in the spreadsheet

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#220]
PRS11248 exists two times, PRS11248YohannesKama and PRS11248GabraK (probably my mistake).
Should one of them be deleted and a new record be created instead?

**Comment by thea-m** [comment]
Is PRS11248YohannesKama the same as PRS10408Yohanne? @sologebre

**Comment by sologebre** [comment]
No, they are not the same.

**Comment by PietroLiuzzo** [comment]
update the id of one of the two with a new number and make sure references are also update. thanks
