### ISSUE TITLE
spelling in search

### ISSUE THREAD

**Issue by FrancescaPanini** [SChAth/ScAthiop#222]
Hallo,
I would suggest that the search function in the website is enhanced in such a way that some spelling differences are tolerated and the result still comes up. 

Eg: 
If i search for Hayq instead of Ḥayq or Estifanos instead of Ǝsṭifānos, I still get the results.

I think this is handy if one does not have the diacritics or is unsure on the spelling.

Thanks
Francesca

**Comment by PietroLiuzzo** [comment]
see https://github.com/SChAth/ScAthiop/wiki/SRC2

**Comment by PietroLiuzzo** [comment]
https://github.com/SChAth/ScAthiop/wiki/SRC8

**Comment by thea-m** [comment]
It would be especially helpful for the current workflow if a/ā/ä differences were tolerated. 
Since many records are still in EAe transcription, searching with the current transcription does not always lead to the correct result and it takes some time to search again.

**Comment by PietroLiuzzo** [comment]
the new analyzer handles these, thanks to Wolfgang Meier and his work for exist db!
