### ISSUE TITLE
Narrative

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#223]
We have to discuss how to encode narratives: 
Currently the @ref to the Narrative record ID is written in `<title>` as for work records, see for example BLadd16217 or BNFet98.
Is this appropriate or should another way be found, since narrative records are different from work records (and do not really constitute a title)?

(Maybe we also need further specific examples from mss about what constitutes narratives and how to describe them)

**Comment by PietroLiuzzo** [comment]
in my view it is best to encode NAR in the text transcription. however I understand here there is no better way to describe a msItem, but I would avoid title, and perhaps use ref for the same purpose?
