### ISSUE TITLE
works list view improvement

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#225]
display 
- antecedents, 
- parallel versions and recensions
- main parts.

**Comment by PietroLiuzzo** [comment]
@thea-m @MassimoVilla Could you please remind me what relations are used for the three above?

**Comment by thea-m** [comment]
I believe we mainly used
saws:isVersionInAnotherLanguageOf
saws:isVersionOf (for parallel verions)
for main parts you mean the main part of a work? Since we added them as divs, we didn't use relations for this case

**Comment by PietroLiuzzo** [comment]
please check http://betamasaheft.aai.uni-hamburg.de/works/LIT1961Mashaf
under related works and this
http://betamasaheft.aai.uni-hamburg.de/works?ms=BAVet15&dateRange=0%2C2000
or similar queries to check the results.
note some wrongly entered ids link BNFet9#i3 instead of BNFet9#ms_i3

**Comment by PietroLiuzzo** [comment]
http://betamasaheft.aai.uni-hamburg.de/api/BNFet11/ms_i3/title

http://betamasaheft.aai.uni-hamburg.de/api/BNFet11/i3/title

**Comment by PietroLiuzzo** [comment]
missing antecedents for list. what relation do you use for that?

**Comment by thea-m** [comment]
me none until now...

**Comment by PietroLiuzzo** [comment]
ok, please open new issue for future manuscripts needing to be featured somewhere.
