### ISSUE TITLE
A work record for a treatise by Cyril III ibn Laqlaq

### ISSUE THREAD

**Issue by MarcinKrawczuk** [SChAth/ScAthiop#2252]
I would like to create a record for a tratise known as መገጸዊ፡ ቡሩክ፡ which is in fact translation of "Kitāb al-muʻallim wa-al-tilmīdh" by Cyril III ibn Laqlaq preserved i. a. [here](https://w3id.org/vhmml/readingRoom/view/534475). I do not find it in the database. 

@thea-m @DenisNosnitsin1970

**Comment by thea-m** [comment]
I am sure I won't find it anymore than you, but in order to follow the regulations, could you give a bit of the incipit, so I can try? The manuscript's images are not available to me.

**Comment by MarcinKrawczuk** [comment]
Sure, I just thought the link would be enough. 

GG-153 https://gundagunde.digital.utsc.utoronto.ca/islandora/object/gundagunde%3A114356#page/1/mode/2up
GG-161 https://gundagunde.digital.utsc.utoronto.ca/islandora/object/gundagunde%3A62132#page/1/mode/2up
GG-176 https://gundagunde.digital.utsc.utoronto.ca/islandora/object/gundagunde%3A62986#page/1/mode/2up

**Comment by DenisNosnitsin1970** [comment]
It is a rare work, those three GG mss are the only that I know, plus one recent manuscript in Enda Abba Garima.

**Comment by thea-m** [comment]
Yes, it does not seem to exist yet, please go ahead. Thanks!
