### ISSUE TITLE
Do we need a new ID for a prayer to George?

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [SChAth/ScAthiop#2319]
@eu-genia @DenisNosnitsin1970 @thea-m

In the manuscript BMLacq306, there is another short prayer on ff. 93r-v, that I have recorded as p7_i2:

The text is:
ጊዮርጊስ፡ ሰማዕት፡ መስተጋድል፡ በጸሎትከ፡ አንሣእከ፡ ሙታነ፡ ሰአል፡ ወጸሊ፡ በእንቲአነ፡ ኀበ፡ እግዚአብሔር፡ አምላክነ። 
በእደ፡ መድኅን፡ ይዕቀበነ፡ ወይክሥት፡ አዕይንተ፡ አልባቢነ፡ ይምሐረነ፡ መዓልተ፡ ምስሌነ፡ ስሌነ፡ ወሌሊተ፡ ማእከሌነ፡ የሀሉ፡ ምስሌነ። ረዳኤ፡ ይኩነነ፡ ኢትግድፈነ፡ 
ወኢትመንነነ፡ አምላከ፡ ሰላም፡ ተራድአነ። ፫ጊዜ፡ እግዚኦ፡ መሐረነ፡ በል።
Marrassini (bm:Marrassini1986Laurenziana, p. 108) has indicated that piece as "prayer to George". I was not able to find similar text on my own.

Have I overlooked something or do we need a new ID?

**Comment by CarstenHoffmannMarburg** [comment]
LIT4518Hymn is titled "Hymn to Jesus Christ". Did you mean the one in #2317?

**Comment by eu-genia** [comment]
Has CAe Id been created? Can this be closed?

**Comment by CarstenHoffmannMarburg** [comment]
I attributed LIT4518Hymn to this short prayer, but I have doubt, that this was correct. It is just the phrase and attribute to Giyorgis, that is similar: 
BMLacq306: ጊዮርጊስ፡ ሰማዕት፡ መስተጋድል፡ በጸሎትከ፡ አንሣእከ፡ ሙታነ፡ ሰአል፡ ወጸሊ፡ በእንቲአነ፡ ኀበ፡ እግዚአብሔር፡ (f. 93rb = incipit of p7_i2)
BAVet54: ጊዮርጊስ፡ ኀያል፡ ሰማዕተ፡ ክርስቶስ፡ መስተጋድል፡ ዘአንሣ<supplied reason="omitted">እ</supplied>ከ፡ ሙታነ። ሰአል፡ ወጸሊ፡ በእንቲአነ፡ ኀበ፡ እግዚአብሔር። አምላክነ፡ <choice><sic>እግዚእትነ፡</sic> (f. 183 = explicit!)

I think, this similarity is more a coincidence and I would rather change it and encode it as an unidentified text or with a new ID.

Apart from this, I think, it is more useful to give the text of the prayer in a div at the end, but not in a note, as I did here. Since this is the entire text, it must be given in a div in the end, correct?

**Comment by thea-m** [comment]
Yes, if it is the entire text, it can be given in a div. I think it sounds reasonable to create a new record, in which you explain the possible similarities
