### ISSUE TITLE
A work record for a deletion

### ISSUE THREAD

**Issue by MarcinKrawczuk** [SChAth/ScAthiop#2340]
After the discussion (https://github.com/BetaMasaheft/Documentation/issues/2327) it was agreed that LIT2212Questi should be deleted but it's still visible in the app (LIT5193HistoryBenjamin has been modified accordingly. @thea-m

**Comment by thea-m** [comment]
Thank you for noticing! The file is deleted, it must be a syncing problem. @eu-genia could you check?

**Comment by eu-genia** [comment]
deleted in the backend
