### ISSUE TITLE
Prayers in BDLeu10

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#2399]
Here come other three protective prayers in my last scroll, MS BDLeu10. Again, I can find single words in the BM database, but nowhere the texts correspond to those of the following prayers.

1. Prayer for binding the Enemy, mentioning Solomon
Incipit: በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩፡ አምላክ፡ ዘአሠሮ፡ ለጸላኢ፡ በማዕሠረ፡ አሌፍ፡ መደንግፅ፡ ማየ፡ ጠፈረ፡ ሰሎሞን፡ ሎፍሐም፡ ሎፍሐም፡ ሎፍሐም፡ መሐፍሎን፡ መሐፍሎን፡ መሐፍሎን፡ ንምሎስ፡ ንምሎስ፡ ንምሎስ፡

2. Prayer for binding the demons, with magic names
Incipit: በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩፡ አምላክ፡ ጸሎት፡ በእንተ፡ ማዕሠረ፡ አጋንንት፡ አካዕ፡ አካብ፡ ክስብኤል፡ ቤቃ፡ ሴቃ፡ ጼቃ፡ ዮድ፡ አኽያ፡ ሸራኽያ፡ በራኽያ፡ ኤልሻዳይ፡ ጸባዖት፡ አዶናይ፡ አማኑኤል፡ እልመክኑን፡

**Comment by thea-m** [comment]
I also didn't find any existing work record corresponding to these. I would suggest to create one.
