### ISSUE TITLE
work units

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#243]
There needs to be more discussion of preferably specific examples on the definition of textparts, narratives, groups of narrative units, works and collections. 

Examples to be discussed include:
- Sənkəssār
- Gəbra ḥəmāmāt
- Maṣḥafa gənzat
- Dərsāna Mikāʾel
- gadlāt and miracles

see also #190

**Comment by PietroLiuzzo** [comment]
case by case decide if creating a superunit which contains the other LITs.

**Comment by PietroLiuzzo** [comment]
general abstract record needs to contain the relation to the other entities.
