### ISSUE TITLE
@n allowed only once with <locus from="x" to="y"/>

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#252]
According to guidelines, when a line number is given, we also use `@n` together with `locus`. Apparently, `n` is accepted only once, so that the following way of referring to an exact location is not allowed:

`<locus from="128rb" n="10" to="129rb" n="15"/>`

**Comment by PietroLiuzzo** [comment]
I would suggest using two locus elements. <locus from="128rb" n="10"/> <locus to="129rb" n="15"/>

**Comment by PietroLiuzzo** [comment]
asked in TEI-L
