### ISSUE TITLE
works and mss

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#253]
Under Works / Witnesses the mss pointing to the work as msitem should be viewed, otherwise confusing as now only external witnesses are seen e.g. LIT1709Kebran (and this is not a witness to the Ethiopic version, so not the one the Edition is based on)

**Comment by PietroLiuzzo** [comment]
If I understand well, you are speaking of the work view. ok. we had decided to record in the work record the full list, therefore to hand include the references in listWit to avoid encoding confusion. when the analytic view in the new split form will be again available you shall see there the ordered list of ms in our repo containing a reference to the work. We could add a warning message advising to check also that for completeness.

**Comment by eu-genia** [comment]
some more nesting would be helpful, for now the file is broken do not know why :(

**Comment by PietroLiuzzo** [comment]
You can nest as much as you need, there is no limit to the number of listWit nested in one another. each of them can contain witness and listWit. I cannot reproduce the issue. the file validates, transforms in XSLT and also in the app. could you specify what is broken?

**Comment by PietroLiuzzo** [comment]
@eu-genia

**Comment by eu-genia** [comment]
works now
