### ISSUE TITLE
works elements

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#262]
in the works we shall need more elements that must be visualized, see e.g. LIT4275ChronAmdS

```
<extent>
<editionStmt>
<sourceStmt> p (text not printed)


```

**Comment by PietroLiuzzo** [comment]
for  LIT4275ChronAmdS 
* These elements are not in the guidelines, thus they are not handled in the schema anyhow and consequently neither in the visualization and in the indexes. I have added the visualization in the general description. Please let me know where else these information should be displayed. 
* Do update please the guidelines according to the use you wish to make of these elements. 
* Also, please, enter the editors information in editor elements, not as string.

**Comment by eu-genia** [comment]
Have added extent to the guidelines.
I think for extent the word "Extent" should be shown, too. This should be there for all works that there will be the text provided for. 
We also shall need respStmt - this is the place where I would specify who did what, as in

```
<respStmt>
 <resp>proofreading</resp>
 <persName from="1994-02" to="1994-05">Ashley Cross</persName>
 <persName from="1994-06" to="1994-10">Loren Noveck</persName>
</respStmt>

```

I have now added the name sigla to the editors but this is not quite correct as they did not work on the BM record but on the digital text, so should go into the respStmt. if we want to use sigla also for TraCES persons these must be added to the sigla list.

**Comment by eu-genia** [comment]
we shall also need 
`<encodingDesc>`
for some digitally edited texts

**Comment by eu-genia** [comment]
(the visualization of LIT4275ChronAmdS does not work maybe because of all the new elements?)

**Comment by eu-genia** [comment]
(ok it did not work because of the editor sigla absent in our list)

**Comment by PietroLiuzzo** [comment]
isnt it already possible to use these elements? 
how do you want to use them? 
For respStmt, you have now the example above 

```xml
<respStmt>
 <resp>proofreading</resp>
 <persName from="1994-02" to="1994-05">Ashley Cross</persName>
 <persName from="1994-06" to="1994-10">Loren Noveck</persName>
</respStmt>
```

and in LIT4275ChronAmdS 

````xml
<respStmt>
<resp>digitization</resp>
<persName ref="AB" from="1994" to="2004"/>
<persName ref="VP" from="2014" to="2016"/>
</respStmt>
````

I do not think we ever use ref to point to our list of editors. we use that list for the values of @key or @resp. 

I would suggest to use 1 `respStmt` for each responsibility and list the attributions in a persName element with a @key instead of a @ref when we have one or in full when we do not. it remains possible to use @corresp if let's say the responsibility is of Zotenberg or Dillmann or any one person in the collection.

Where would you like these to be displayed in the work view?

**Comment by PietroLiuzzo** [comment]
same for encodingDesc. where do you want this information?

**Comment by PietroLiuzzo** [comment]
I have temporarily displayed `respStmt` beside revisions and citation, while I have added a row before the text transcription which will visualise the `encodingDesc` information

**Comment by PietroLiuzzo** [comment]
in LIT4275ChronAmdS there are no witnesses but in the bibliography you have notes referring to mss. is this work in progress? we have discussed both the connection between bibliography and witnesses (LIT2317Senodo) and the organization of the listWit (LIT1709Kebran). Guidelines do not yet reflect these properly. Could be updated once we have a complete example using these.

**Comment by eu-genia** [comment]
when i put multiple ids in bibl corresp these are not shown

**Comment by PietroLiuzzo** [comment]
I would point to the id of the listWit rather than to each witness if possible.
