### ISSUE TITLE
witnesses and works

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#264]
in witnesses under works we have to distinguish between ms/mss used for the edition and all other possible mss

(BnF Arabe 264 in LIT1709Kebran is not used for the edition, others yes, records not created yet)

**Comment by PietroLiuzzo** [comment]
was in #262

**Comment by PietroLiuzzo** [comment]
I believe the easiest way is to use the nesting of listWit as in the guidelines. I have modified the example mentioned accordingly. the only variation is the use of @rend='edition' for the listWit containing the mss used in this edition. others can be linked using corresp, and bibl of editions can already be linked to witnesses with xml:id (see also LIT2317Senodo). would this be enough?

**Comment by eu-genia** [comment]
we may need more structuring here, now the 'edition' nest is clear but the unnested witness needs an explanation

**Comment by PietroLiuzzo** [comment]
ok. you could either link to a bibl entry or provide explanation directly within listWit, let me know what you decide

**Comment by eu-genia** [comment]
ok will think
the facs link is not visualized at the moment in
`<witness type="external" corresp="BnF Arabe 264" facs="http://archivesetmanuscrits.bnf.fr/ark:/12148/cc89540w/cd0e210"></witness>`

**Comment by eu-genia** [comment]
(the visualization of LIT4275ChronAmdS does not work maybe because of all the new elements?)
