### ISSUE TITLE
Editing LIT1808Litonz: correcting the orthography and adding relations

### ISSUE THREAD

**Issue by LeonardBahr** [SChAth/ScAthiop#2649]
Dear all,

I would like to edit LIT1808Litonz, the record for the litanies of the evening, by

- correcting the orthography from "śark" to "sark", 
- adding a general description (abstract),
- and adding the relations to the two individual litanies of the evening (ref type).

All the best

Leo

**Comment by eu-genia** [comment]
Dear Leo, there is no need to create an issue if you want to enhance an existing record, you just edit and create a pull request, asking reviewers (not assignees).

Just try to pay attention that the record is not being worked on already. In this case you should have probably tagged (not as assignee, but putting an `@` in the text of the issue) @CarstenHoffmannMarburg who would have immediately noticed that this is a record already in a branch being worked on, helping us avoid double work and github branch conflicts to resolve.

Thank you!

> It is a problem when the same record is being simultaneously edited in two branches #1119. If you want to edit LIT1808Litonz it is best if you edit it in the branch [Update-Litanies_no.3_CH_june24](https://github.com/BetaMasaheft/Works/tree/Update-Litanies_no.3_CH_june24), as otherwise you create conflicts.
> 
> Can you move your changes to that branch please? Then we can close this one https://github.com/BetaMasaheft/Works/pull/1203 without merging

**Comment by LeonardBahr** [comment]
Thank you, Eugenia, sorry for that!
