### ISSUE TITLE
Merge PRS14216NobWaldaYasey and PRS7597Nob

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [SChAth/ScAthiop#2650]
@MarcinKrawczuk gave me a note, that PRS14216NobWaldaYasey is very likely to be PRS7597Nob, the abbot of Remā and the spiritual son of Yāsāy (cf. Hammerschmidt1973Tanasee p. 65). I did not notice that, when I created PRS14216NobWaldaYasey, because this was not visible from the record. As far as I understood, Marcin is reworking PRS7597Nob at the moment adding some information to the record. I suggest to add the attestation in Tanasee1 and the name ኖብ፡ ወልደ፡ ያስይ፡ (or ያሳይ፡ ) as n2 and to delete PRS14216NobWaldaYasey in a next pull request (and replace the ID with PRS7597Nob in the ms-record of Tanasee1). 

@eu-genia @karljonaskarlsson

**Comment by eu-genia** [comment]
very good, thank you

**Comment by karljonaskarlsson** [comment]
sounds good!
