### ISSUE TITLE
Kolmodin's qene notebook

### ISSUE THREAD

**Issue by karljonaskarlsson** [SChAth/ScAthiop#2651]
Hello!

As part of the current initiative to encode qǝne on Bm, I would like to encode the following manuscript (a handwritten notebook by Johannes Kolmodin): http://urn.kb.se/resolve?urn=urn:nbn:se:alvin:portal:record-280997.

It is kept at the university library in Uppsala (so the repository already exists); however, it is not part of the O collection, like the manuscripts there, but rather belongs to the archive of documents left by Johannes Kolmodin (Q15.1-Q15.27). The shelfmark "Q 15:24 o" seems to refer unambiguously to this notebook.

I wonder what would be the best way of naming the file. The rest of the files in Uppsala are (arbitrarily) called "UppEt" followed by the number from the shelfmark. Can this be "Kolmodin1"? (There seem to be some other potentially relevant notes in his archive as well, such as a collection of songs and stories in different Ethiopic languages.)

@DenisNosnitsin1970 @nafisa-valieva @eu-genia @CarstenHoffmannMarburg

**Comment by eu-genia** [comment]
If a unique shelfmark exists then use it in the filename preceded by Upp, thank you

**Comment by karljonaskarlsson** [comment]
Ok, perfect, thank you! :)

**Comment by eu-genia** [comment]
Make sure you close all issues you open or get assigned once they are resolved, thank you!
