### ISSUE TITLE
syncing INS0918TZM

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#2656]
The name of INS0918TZM is shown in Fidal
https://betamasaheft.eu/institutions/INS0918TZM/main
![image](https://github.com/user-attachments/assets/01581e74-41d1-4b7e-bb23-bef4d65caba7)

**Comment by eu-genia** [comment]
the changes may take up to 1 hour to show, please wait and only then write me a message; I do not think it is necessary to open an issue for such things
