### ISSUE TITLE
ESam019 not updated

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#2657]
The images of the manuscript are not available, I must have made an error in https://github.com/BetaMasaheft/Manuscripts/pull/2626
Could you help @eu-genia ?

**Comment by eu-genia** [comment]
As you can easily see here https://betamasaheft.eu/manuscripts/ESam019.xml the merge did not go through to the app, the file has not been updated yet

**Comment by eu-genia** [comment]
You can update e g by adding the missing change element and push again
