### ISSUE TITLE
Update LIT1171Awdana

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#2658]
I would like to update the LIT1171Awdana record (ʿAwda nagaśt), which is now very concise, by adding textparts taken from BAVet119, with respective incipits and, where present, also explicits.

None of these texts are present in the database as Work records, with the exception of LIT6042HassabaDemetros, and I cannot confirm that they have independent circulation. This is why I am inclined to add them as `<div type="textpart"/>` of LIT1171Awdana.

Shall I proceed?

**Comment by eu-genia** [comment]
sounds good to me, we can always "upgrade" text parts if we ever come across individual circulation of any of them, thank you!

**Comment by karljonaskarlsson** [comment]
Sounds good to me as well!

**Comment by MassimoVilla** [comment]
In addition to a revision of LIT1171Awdana, new Work records have been created which are not textparts of LIT1171Awdana but independent works attested in BAVet119:

- LIT7107Divination (Treatise on divination), with its own textparts: table1, table2, chapters, kawakebt, mogad, nagar2, negus, nagar4, nagar5
- LIT7108Astronomy (Treatise on astronomy)
- LIT7109Moonrise (On moonrise and moonset) 
- LIT7110Kekros (On the calculation of the kekros, or sixtieth part of the day)
- LIT7111Zodiac (Astrological treatise on the signs of the zodiac)
- LIT7113Horoscopes (Sixteen horoscopes)

**Comment by MassimoVilla** [comment]
I need to open a new branch for further work on divinatory texts, as found in BAVet119. In particular:
- one div inside LIT1171Awdana for a list of names and letters with which portions of the circle are annotated
- one work record for a Table with calendar elements for each year of the 82-year cycle
- one work record for Chart of the winds (incipit:  መስዕ፡ ዝናም፡ አናኵዕ፡ ድምሳሴ፡ ጠል፡)

Shall I proceed?

**Comment by MassimoVilla** [comment]
The newly-created work records have been generated automatically via the app and have been assigned IDs LIT14518Diagram and LIT14519Winds. So 7,000 numbers have been skipped since the previous Id was LIT7113Horoscopes.
I hope this is correct, even if I do not understand why this has happened

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Documentation/issues/2666
