### ISSUE TITLE
work records/textparts

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#266]
Detailed issues specifying the outcome of the informal meeting between @MassimoVilla  @DenisNosnitsin1970  and me regarding the structure and creation of work records and textparts have to be created

**Comment by MassimoVilla** [comment]
In compliance with the assumption that only texts circulating independently receive the status of Work records (and with the complementary principle that any text is originally a Textpart and only potentially a Work record, i.e., only when we find it as an independent unit), a revision of the previously treated works is needed.
Some Work records should be downgraded to Textparts. For instance:

- the single Passiones within the Gadla Samāʿǝtāt (except for those texts that also have a different circulation like the Gadla Qirqos and few others);

- the single Miracles of Mary which currently have an own work ID (again, unless they are found as independent units);

- even the status of some biblical books like the minor prophets, which seem not to occur outside the Dodekapropheton collection, needs to be discussed;

- the Mazmura Dāwit and the Canticles of the Prophets are regularly part of the Dāwit and, accordingly to our principle, should theoretically not be given a Work ID.

These major changes in the treatment of specific texts as Work or Textparts require further discussion.

**Comment by abausi** [comment]
We can discuss this tomorrow. One could actually assign the rank of 
"text-parts" and raise it to "work" only when they occur in alone, if 
this has no other implications.

Alessandro

Il 01.02.2017 15:25, Pietro Liuzzo ha scritto:

**Comment by abausi** [comment]
We can discuss this tomorrow. One could actually assign the rank of 
"text-parts" and raise them to "work" only when they occur alone, if 
this has no other implications.

Alessandro

Il 01.02.2017 15:25, Pietro Liuzzo ha scritto:

**Comment by PietroLiuzzo** [comment]
the decision for each case will be recorded in the Works repo wiki and applied to the work in question. IDs will be created for subparts as discussed in meeting
https://github.com/SChAth/Works/wiki/Notes-on-Works-encoding
Works editors should update the wiki and pose questions in case of doubts using issues in the work repo or here pointing to the records
