### ISSUE TITLE
Prayer for childbirth

### ISSUE THREAD

**Issue by karljonaskarlsson** [SChAth/ScAthiop#2660]
There is a prayer for successful childbirth in MS Uppsala, O Etiop. 29: https://www.alvin-portal.org/alvin/imageViewer.jsf?dsId=ATTACHMENT-0076&pid=alvin-record:490723

A prayer with the same "title" appears in https://betamasaheft.eu/manuscripts/EMIP03223/main, but it's simply catalogued as "ʾAsmāt-prayer (general record) (CAe 5888)", and as far as I see, no images are available…

Do you think it's ok to create a new ID for the prayer in the Uppsala manuscript?

@eu-genia @CarstenHoffmannMarburg @nafisa-valieva

**Comment by CarstenHoffmannMarburg** [comment]
I did not receive a notification via email, although I was tagged by Jonas.

**Comment by CarstenHoffmannMarburg** [comment]
I did not find any comparable LIT ID or manuscript either.

**Comment by CarstenHoffmannMarburg** [comment]
There is a prayer for good childbirth with reference to Rufāʾel in EMIP03239, as well. The incipit is different but similar. However, I cannot see any ʾasmāt in O Etiop 29, so I think it is more probable to be a different prayer. The reference to Rufāʾel is probably typical for requesting a good childbirth.

I agree to create a new ID and refer to EMIP03239 and EMIP03223 as thematically similar in relations (perhaps dc:relation).

**Comment by eu-genia** [comment]
Ok for me
