### ISSUE TITLE
HTTP ERROR UppEt3 - settings for the UNCLEAR element

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#2662]
HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/UppEt3/main: exerr:ERROR XPTY0004: The actual cardinality for parameter $node/child::text() does not match the cardinality declared in the function's signature: zero or one. Expected cardinality: $node/child::text(), got zero or one. [at line 3511, column 6, source: /db/apps/BetMasWeb/modules/viewItem.xqm] In function: viewItem:unclear(element()) [4551:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [3033:41:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:hi(element()) [4375:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [3539:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:del(element()) [4327:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [2991:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:explicit(element()) [4339:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [1894:25:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msItem(item()*) [4433:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [3134:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:msContents(element()) [5591:53:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:divofmanuscriptpath(item()*, item()*, item()*) [5635:10:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscriptStructure(item()*) [4426:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:TEI2HTML(item()*) [5532:22:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:manuscript(item()*) [5843:21:/db/apps/BetMasWeb/modules/viewItem.xqm] viewItem:main(item()*) [1434:9:/db/apps/BetMasWeb/modules/viewItem.xqm] item2:RestItem(item()*, item()*) [565:36:/db/apps/BetMasWeb/modules/item.xqm] restItem:ITEM(item()*, item()*, item()*, item()*, item()*, item()*, item()*, item()*, xs:string*) [87:1:/db/apps/BetMasWeb/restviews/items.xqm] restItem:getItemC(xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*, xs:string*) [-1:-1:/db/apps/BetMasWeb/restviews/items.xqm]

**Comment by eu-genia** [comment]
Clearly the error comes from the fact that the xquery at the moment does not support that `unclear `element used in
```
<unclear>ያ<gap reason="lost" unit="chars" quantity="1"/>ቅበ<gap reason="lost" unit="chars" quantity="1"/><supplied reason="lost">፡</supplied>
                                    አብ፡</unclear>
```
has children.

I will try to fix viewitem to enable this, or we should avoid using `unclear `with children.

@HelenaSabel has suggested that she may find a work around that whenever the XML is correct, even if the encoding is not supported by xquery, we have something shown. So hopefully we will have fewer of such issues in the future

**Comment by eu-genia** [comment]
Currently we have only
```
declare %private function viewItem:unclear($node as element(t:unclear)) {
    $node/text() || '?'
};

```

**Comment by eu-genia** [comment]
at the moment `unclear `adds ? after a word/letter, not meant for passages, we need possibly another solution for visualizing unclear passages

`orig `makes the text grey but does not print children, should also be corrected

**Comment by eu-genia** [comment]
adding for now a wavy line

**Comment by eu-genia** [comment]
![image](https://github.com/user-attachments/assets/7d09d646-53a8-4586-92b9-57934b97805c)
@karljonaskarlsson @CarstenHoffmannMarburg @nafisa-valieva @DenisNosnitsin1970 @thea-m suggestions welcome

**Comment by karljonaskarlsson** [comment]
@eu-genia , @nafisa-valieva , @CarstenHoffmannMarburg , and I were discussing the visualisation of `unclear` in the office. It is not so easy to decide which is the best way of visualising this, especially as it has to be coherent with the other symbols that we use when visualising edited text in Geez. I think it's important to mark when the unclarity starts and where it ends (not just the end, as now). Many possibilities may be considered, such as wavy underlining, dotted underlining, grey text (but what happens then when it coincides with rubrication?), a superscript question mark at the end (but again, how then to mark the beginning?)…

As this is a somewhat tricky question, I would like to ask also you, @DenisNosnitsin1970 and @abausi , if you want to weigh in on this. What do you think would be the best way of visualising unclear letters and words?

**Comment by eu-genia** [comment]
I have now proposed
![image](https://github.com/user-attachments/assets/11db6398-c7d2-4b77-8edf-d80a60e61f08)

[unclear text lighter + background + wavy line?]

**Comment by eu-genia** [comment]
(inspired by https://whitmanarchive.org/item/loc.04048 - that's the way they deal with `tei:unclear`)

**Comment by CarstenHoffmannMarburg** [comment]
I would clearly prefer another visualisation based on the principle: one symbol = one meaning. So either ? or dot below indicating unclear letters (based on Jonas suggestions today). This is easy to visualise and easy to memorise. Three features are difficult, because users will either think, that three features have three different meanings or that this particular representation is perhaps an output problem or a link to another website.

For a lost character, I would prefer X or V (= vacat). So my preferred visualisation for this word would be:
¿ያXቅበ፡ Xአብ፡? 
![grafik](https://github.com/user-attachments/assets/934c0c55-b88b-4dc3-9493-a5f4ed90e8e6)
or
ያ̣Xቅ̣በ̣፡ Xአ̣ብ̣፡
![grafik](https://github.com/user-attachments/assets/837ba231-506b-451c-923e-49070d790a3f)

(In this particular case by the way, I would prefer to emend to ያዕቆብ፡ ዘአብ፡ as Jonas has suggested)

**Comment by eu-genia** [comment]
putting a dot under unclear letters would require marking up each unclear letter separately, one cannot then have unclear phrases with further mark up as in the example that started theis discussion

we did not use lighter print, grey background or wavy lines for anything else

best is in my mind to follow clear conventions, either present in print (as long as technically possible in `html`) or (better!) in other similar digital projects

**Comment by eu-genia** [comment]
**visualize** = encode in html in a way that also the mark up of children and parent elements as in the example above is preserved
 "**easy to visualise**" - I do not think what you suggest with dots is easy, or possible at all (unless each unclear letter is tagged unclear separately, but this is not what was initially desired), but maybe you know how to do it

**Comment by CarstenHoffmannMarburg** [comment]
I gave my preference but I have no problem with any other solution. 

The dots are widely used in edited epigraphical texts. However, I understand your point, that it would be a burden to the encoder to mark up every character individually.

The question marks before and after are not common to any edited texts, I know. So this would be an innovation. I see, that this is problematic.

The question mark standing alone after the word or letter would be ambiguous, because users do not know, whether it relates to the last character or to several characters.

In the end, the solution, which you proposed, might be the best option.

**Comment by eu-genia** [comment]
There is no ambiguity in the final question mark as in the example above and at the link provided it is used in combination with brackets, wavy line and lighter font colour

**Comment by karljonaskarlsson** [comment]
> There is no ambiguity in the final question mark as in the example above and at the oink provided it is used in combination with brackets, wavy line and lighter font colour

A combination like Zhenia suggests sounds quite good to me! For example, lighter text + grey background + superscript question mark after the entire marked sequence.

However, I don't know if it has precedence. But in any case, this would be clearer to me than what the Whitman Archive has.
