### ISSUE TITLE
CAe 2167

### ISSUE THREAD

**Issue by abausi** [SChAth/ScAthiop#2664]
The transcription of the Ethiopic title is wrong: _Tarafa nagar za-Bārok za-ʾi-kona ḫǝbuʾa za-ʾama yǝḍewawu Bābilon_. It should be: _Tarafa nagar za-Bārok za-ʾi-kona ḫǝbuʾa za-ʾama **yǝḍḍewwawu** Bābilon_.

**Comment by CarstenHoffmannMarburg** [comment]
Yes. If you agree, I will open a branch and change it in a couple of minutes.
