### ISSUE TITLE
Unidentified theological work

### ISSUE THREAD

**Issue by karljonaskarlsson** [SChAth/ScAthiop#2665]
In one of the Uppsala manuscripts, a theological work has been added on the guard leaves, beginning here: https://www.alvin-portal.org/alvin/imageViewer.jsf?dsId=ATTACHMENT-0006&pid=alvin-record:502581 … and ending here: https://www.alvin-portal.org/alvin/imageViewer.jsf?dsId=ATTACHMENT-0443&pid=alvin-record:502581

Löfgren notes that the same work also appears in https://betamasaheft.eu/manuscripts/BLorient735/main?hi=CCCXI, fols 3r ff., where we have not given it any CAe number.

I have not been able to identify this work based on incipit or explicit. However, one must note that in both attestations, we are thrown into "Chapter 3" (አንቀጽ፡ ሣልስ፡) of the work, so it is possible that this is not the "real" beginning.

I believe it is worth creating a LIT file for this work, given that it's attested twice now, but due to the complexities with the chapter numbering, I wanted to ask if any of you recognize this work and can see if there is a file for it already.

@CarstenHoffmannMarburg @nafisa-valieva @eu-genia @MassimoVilla

**Comment by nafisa-valieva** [comment]
Unfortunately, I do not recognize it either. Maybe you can create it as a narrative unit and explain what you explain here in the abstract?

**Comment by CarstenHoffmannMarburg** [comment]
I did not find any work in my searches either. I agree to create a LIT ID with all the information that you mentioned above.

**Comment by karljonaskarlsson** [comment]
> Unfortunately, I do not recognize it either. Maybe you can create it as a narrative unit and explain what you explain here in the abstract?

Why a narrative unit and not a LIT ID? This clearly is circulating separately

**Comment by nafisa-valieva** [comment]
because I understand it as a circulating chapter. But since we can't identify the textual unit, your are right to create a LIT Id!

**Comment by MassimoVilla** [comment]
I also do not recognize the work. It seems advisable to create a new work record with all relevant information, and to use it for both attestations

**Comment by karljonaskarlsson** [comment]
Thank you all!

**Comment by karljonaskarlsson** [comment]
I created the file through the app and it received the surprising LIT ID no. "LIT14520Theology" (the previous ones are all in the 7000s). @eu-genia , is this a problem?

**Comment by MassimoVilla** [comment]
> I created the file through the app and it received the surprising LIT ID no. "LIT14520Theology" (the previous ones are all in the 7000s). @eu-genia , is this a problem?

I also had the same issue. I got LIT14518Diagram and LIT14519Winds

**Comment by eu-genia** [comment]
Wait till I have a look. Of course once there is an ID with 14000 or more the new ones will be +1 to the last one
