### ISSUE TITLE
Unexpected LIT ID numbers

### ISSUE THREAD

**Issue by karljonaskarlsson** [SChAth/ScAthiop#2666]
I created the file through the app and it received the surprising LIT ID no. "LIT14520Theology" (the previous ones are all in the 7000s). @eu-genia , is this a problem?

_Originally posted by @karljonaskarlsson in https://github.com/BetaMasaheft/Documentation/issues/2665#issuecomment-2440705165_

**Comment by karljonaskarlsson** [comment]
https://github.com/BetaMasaheft/Documentation/issues/2665#issuecomment-2440743131

**Comment by karljonaskarlsson** [comment]
@eu-genia @MassimoVilla @nafisa-valieva @CarstenHoffmannMarburg 

(I figured that this should be its own issue)

**Comment by CarstenHoffmannMarburg** [comment]
I never came across such a problem. It is probably better not to create any new IDs through the app until this problem is solved.

**Comment by eu-genia** [comment]
I will try to temporarily remove
LIT14518Diagram LIT14519Winds LIT14520Theology

and see what goes, might need to restart the index so it will have to wait till noone is using the app and all the merges are complete.

By the way, @MassimoVilla LIT7112Horoscopes and LIT7113Horoscopes - both correct? Not a doublet?

**Comment by MassimoVilla** [comment]
LIT7113Horoscopes is the only valid; I had to create it anew because while generating LIT7112Horoscopes the system crashed.

**Comment by eu-genia** [comment]
Ok, have reindexed, seems to work again

Please rename directly in your NEW folders and in all the links you have been using
LIT14518Diagram ---> LIT7122Diagram 
LIT14519Winds ---> LIT7123Winds 
LIT14520Theology ---> LIT7124Theology 

(the app has already been updated, but clearly not the github where we have had no merges for the files yet)

Thank you!

**Comment by eu-genia** [comment]
@MassimoVilla when you believe a record has been created but you have not made to download it in time, open the xml at 
betamasaheft.eu/YOURID.xml (betamasaheft.eu/LIT7112Horoscopes.xml) and take it from there, otherwise the doublet stays in the application. Every time you hit "create new record" a record is created.  

I will remove it now from the backend, since 7112 has not been used you can locally use it to create a new ID, bypassing the app, then we have no skipped numbers.

**Comment by MassimoVilla** [comment]
Thank you @eu-genia for fixing the issue and for the suggestion

**Comment by eu-genia** [comment]
Thank you @karljonaskarlsson for noticing it )

**Comment by karljonaskarlsson** [comment]
Thanks be to all! :)
