### ISSUE TITLE
Editorial info in records

### ISSUE THREAD

**Issue by DenisNosnitsin1970** [SChAth/ScAthiop#2667]
I have a question: is the editorial history of the records now hidden on purpose, or it is a temporarily technical problem? I ask because there is a related issue. If the images of a manuscript cannot be displayed, by whatver reason, how one can learn that it has been digitized? (the info about this, in editorial history, is now hidden).

**Comment by eu-genia** [comment]
It is not hidden, you can click on the button and expand. It takes too much space on page otherwise.see https://github.com/BetaMasaheft/Documentation/issues/2555
