### ISSUE TITLE
text encoding

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#267]
in text encoding:
how do we express in TEI text written
- upside down 
- in negative writing (see for example ESgbi008)?

**Comment by eu-genia** [comment]
i guess we need the
`<mapping type="">`
element
(http://www.tei-c.org/release/doc/tei-p5-doc/en/html/WD.html)

**Comment by PietroLiuzzo** [comment]
I would be more inclined to give this information in the transcription, using a simple element hi with a @rend attribute. hi[@rend="reversed"], hi[@rend="negative"]. the information about this phenomenon needs to stay in a note

**Comment by PietroLiuzzo** [comment]
Please @thea-m add in guidelines with one example and close issue
