### ISSUE TITLE
merging gone wrong

### ISSUE THREAD

**Issue by MarcinKrawczuk** [SChAth/ScAthiop#2672]
https://betamasaheft.eu/persons/PRS14173HezbaIyasus/main

@eu-genia

**Comment by eu-genia** [comment]
It did not go wrong. When you create a record in the app you MUST download and save it to the folder called `new`
When you create a record in the app it is immediately stored in the `new` folder.
If you save it on github anywhere else then on merge you create a second file with the same name.

**Comment by MarcinKrawczuk** [comment]
OK, I'll come back to it on Monday, I'm off for a couple of days.

**Comment by eu-genia** [comment]
I can fix it on the backend, I assume the one in the numbered folder is the correct one

**Comment by eu-genia** [comment]
now I see here https://github.com/BetaMasaheft/Persons/pull/946 
![image](https://github.com/user-attachments/assets/bd60851e-99fd-47a0-adfa-8558c57e7974)
the merge created a copy in the `new `folder, so now it exists twice also on github
