### ISSUE TITLE
Prayer against the disease of Zār and Tǝgridā in BLorient12959

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [SChAth/ScAthiop#2675]
@eu-genia @karljonaskarlsson @nafisa-valieva 

I found a prayer against the disease of Zār and Tǝgridā (ጸሎት፡ በእንተ፡ ሕማመ፡ ዛር፡ ወትግሪዳ፡) in BLorient12959. Following this title, there are a number of ʾasmāt/qālāt, which are apparently derived from Arabic (ʾallāhuma = "Oh God", ʾal-malik = "the king").

```
<msItem xml:id="ms_i2">
  <title ref="LIT0000000000000000000000000000">Prayer against the disease of Zār and Tǝgridā</title>
  <incipit xml:lang="gez">በስመ፡ <gap reason="ellipsis"/> ጸሎት፡ በእንተ፡ ሕማመ፡ ዛር፡ ወትግሪዳ፡ አላሁማ፡ ያቹነጂ፡ አለመለኪ፡</incipit>
</msItem>
```

The same title is also attested in [CamOr1885 (fol. 92v-93r)](https://cudl.lib.cam.ac.uk/view/MS-OR-01885/186). Here again it is continued with many ʾasmāt or qālāt and repeated three times (followed by other ʾasmāt or qālāt). However, they are all different from what we got from Strelcyn's catalogue for BLorient12959. In contrast they seem to be rather onomatopoeic.

<img width="129" alt="Screenshot 2024_Zar wa-Tegrida" src="https://github.com/user-attachments/assets/0290e92e-3c50-4f71-87df-c4766228a4c5">

<img width="205" alt="Screenshot 2024_Zar wa-Tegrida II" src="https://github.com/user-attachments/assets/d1f7c8a2-da53-4c05-9315-7058e3cb4b1c">

The fourth mention of Zār and Təgridā might be the beginning of another prayer related to these demons.

I wonder, whether I should create a LIT ID just only for the prayer in BLorient12959 or to connect it to the ones in CamOr1885. I tend to create an ID just for the one in BLorient12959 and note those in CamOr1885 in a relation. What do you think?

**Comment by karljonaskarlsson** [comment]
That sounds good!
