### ISSUE TITLE
Integration of description in BL Or. 692,ms_i13 (Fols 139ra–173va ), Vita of St Antony

### ISSUE THREAD

**Issue by abausi** [SChAth/ScAthiop#2680]
As rightly noted by Zarzeczny, Rafał, ‘The Story of Paul the Simple from the Historia Lausiaca by Palladius in its Ethiopic Recension’, Orientalia Christiana Periodica, 82/1–2, 2016, pp. 127–178: see pp. 133 ff.: ff. 171-173 of BL Or. 692 are a later, inserted fascicle; they actually contain another text than the "Vita of St Antony", the same as EMML 1844, ff. 22ra-23rb, i.e. "History of Paul, disciple of Anthony". Besides the correction, it would be important to provide a further CAe no. for the "History of Paul, disciple of Anthony", unless this is already present. Moreover, the "Vita of St Antony" in the MS BL Or. 692 is mutilous.

**Comment by DenisNosnitsin1970** [comment]
If no other volunteers, I can have a look at this.

**Comment by abausi** [comment]
> In no other volunteers, I can have a look at this.

Thank you Denis. In case I can send the article, but I think this is available. Related to this, it would be really important to implement all CAe nos of texts available in EMML 1844, because there are quite a few important texts which have not yet received any CAe number; for example the "Life of Macarius", see Toda, Satoshi, ‘The Ethiopic Version of the Life of Saint Macarius the Egyptian and its Arabic Model’, Hitotsubashi Journal of Arts and Sciences, 48, 2007, pp. 23–42

**Comment by abausi** [comment]
Also important would be to include CAe nos for EMML 7469 that also contains a number of texts which have not received any CAe no yet, not all of them though (https://betamasaheft.eu/manuscripts/EMML7469/main).

**Comment by MarcinKrawczuk** [comment]
I can try and create some records which are missing in EMML 1844 and 7469 and also do the basic encoding for EMML 1844. If I decide to proceed, I will make an issue as usual to avoid double work. 

By the way, thanks to @abausi 's article on colophons yesterday I corrected the description of EMML 8509 I have included the reference to Gadla ʾAzqir in the record.

**Comment by eu-genia** [comment]
@abausi you can see the Ids created referenced here
https://github.com/BetaMasaheft/Documentation/issues/2682
and here
https://github.com/BetaMasaheft/Documentation/issues/2685

**Comment by eu-genia** [comment]
BL Or. 692 updated
