### ISSUE TITLE
Walatta Ṗeṭros written worngly ("Wälätä P̣eṭros" and similarly)

### ISSUE THREAD

**Issue by abausi** [SChAth/ScAthiop#2681]
In a number of MSS, the title of the work is written wrongly: "Gädlä Wälätä P̣eṭros" and similarly. All instances should be traced and corrected.

**Comment by CarstenHoffmannMarburg** [comment]
I can see five manuscripts with "Gädlä Wälätä P̣eṭros". I can change this title to "Gadla Walatta Ṗeṭros".

There are many other records with EAe transcription, but I do not know any efficient way to filter them out and to correct them quickly.

**Comment by eu-genia** [comment]
There is unfortunately no quick way to automatically fix all records with EAe or any other conventions inherited from other projects. WP is just one of many thousand cases. We can only correct records we deal with for whichever purpose.
