### ISSUE TITLE
Work records for EMML 1844

### ISSUE THREAD

**Issue by MarcinKrawczuk** [SChAth/ScAthiop#2682]
[EMML 1844 opis.pdf](https://github.com/user-attachments/files/17638837/EMML.1844.opis.pdf)

Following @abausi 's suggestion https://github.com/BetaMasaheft/Documentation/issues/2680, I have checked the situation concerning work records needed for EMML 1844 (see the attachment). It seems that most records are already in the database.

There are three however which I think need to be created i. e.
* no. 2 history of Paul disciple of Anthony
* no. 12 combat of Theodore, disciple of Pachomius
* no. 13 combat of Macarius the priest of Alexandria

I can create them. 

@eu-genia @CarstenHoffmannMarburg @MassimoVilla

**Comment by MassimoVilla** [comment]
I found no matches by searching for excerpts of the incipits of the three texts.
For me you can proceed.

**Comment by eu-genia** [comment]
Thank you!
