### ISSUE TITLE
Maṣḥafa falāsfā ṭabibān

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#2686]
The Bm database currently has only one record for the _Maṣḥafa falāsfā ṭabibān_ or the "book of the wise philosophers", i.e. LIT1925Mashaf. The record is already indicated as "Maṣḥafa falāsfā ṭabibān (general record)" because, as stated in the abstract, `There exist a short and a long recension of the <foreign xml:lang="gez">Maṣḥafa falāsfā ṭabibān</foreign>. The short recension generally preserves the Arabic text`. However, no specific records exist for the two recensions.
I would like to create two additional records for the short and long recensions, since both are consecutively attested in BAVet118 and I would like to avoid to use the same work ID for two similar but different textual units. Also, I would update LIT1925Mashaf with relations and other relevant aspects.

**Comment by nafisa-valieva** [comment]
Thank you very much, Massimo! I think it is a very nice idea! It would be very useful to include abstracts, incipits, and explicits.

**Comment by CarstenHoffmannMarburg** [comment]
I did not find any records for the long and for the short recensions either. From my point of view, you can proceed.

**Comment by eu-genia** [comment]
This would be wonderful, ideally, in this case the existing ms records should also be revised to point to the relevant record. In some records (BNFet157, BNFet158 etc) the recension is described under the msItem

**Comment by eu-genia** [comment]
I guess this can be closed?
