### ISSUE TITLE
work titles visualization

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#269]
Maybe we could introduce a parameter (type) to specify the title form we want to be visualized as the main entry title.
Now it is always the normalized transliteration - which is OK for most Ethiopic texts but becomes problematic for texts better known under their e.g. Latin or Greek names.
For example LIT2461Testam 

```
             <title xml:id="t1" xml:lang="gez">ኪዳን፡ ዘእግዚእነ፡ ኢየሱስ፡ ክርስቶስ፡</title>
            <title xml:lang="lat" corresp="#t1">Testamentum Domini</title>
            <title xml:lang="en" corresp="#t1">Testament of Our Lord Jesus Christ</title>
            <title xml:lang="gez" corresp="#t1" type="normalized">Kidān zaʾǝgziʾǝna Iyasus Krǝstos</title>
            
            
            <title xml:lang="lat" xml:id="t2arabic">Testamentum Domini (Arabic)</title>
            <title xml:lang="lat" xml:id="t3syriac">Testamentum Domini (Syriac)</title>
            <title xml:lang="lat" xml:id="t4greek">Testamentum Domini (Greek)</title>
```

 it would be better if it appeared as Testamentum Domini.
If we could add type="main" or something and define that if the type has been assigned that's the one shown?

Especially relevant when linked to from elsewhere (see e.g. the abstract of LIT2444Temher)

**Comment by thea-m** [comment]
I believe currently what is automatically displayed is the "normalized" version of t1, if there is one, and if there is none, then simply t1. 
So a solution for Testamentum Domini at the current stage could be to mark Testamentum Domini as t1 and the Geez title as t2.

**Comment by eu-genia** [comment]
does not really resolve the problem for links

**Comment by PietroLiuzzo** [comment]
I agree with a solution similar to that proposed by Dorothea 👍 , that is how the ids should be used. @eu-genia  : is the content of the title elements for the arabic, syriac and greek a place holder?

**Comment by eu-genia** [comment]
does not work for links, see LIT2444Temher

---------

t2-t3-t4 are the traditions in the respective languages.


---------
the situation as it is is not really optimal as we have to distinguish clearly - and have it visible in the visualization - between
a) several differing titles for the same text (by default in Ethiopic)
b) titles (possibly identical but in other languages) for the same text in other traditions
for the moment they are all t1-t2-t3 (even if with language addition but structurally the same)

the display should preferably then show first everything for the Ethiopic title and then everything for the others tradition by tradition, i.e. in the case of LIT2461Testam for example it should be 

titles: 
Testamentum Domini Ethiopic, ኪዳን፡ ዘእግዚእነ፡ ኢየሱስ፡ ክርስቶስ፡gez (Kidān zaʾǝgziʾǝna Iyasus Krǝstosgez, Testament of Our Lord Jesus Christen) (all in this case referring to the Ethiopic, Latin TD is just the Latin universal name for the text)
editions for Ethiopic, other biblio for Ethiopic, witnesses for Ethiopic

TD Syriac
biblio Syriac etc

TD Arabic
biblio Arabic etc

and when I link from somewhere e.g. to t2ethio I expect to see "Testamentum Domini (Ethiopic)" (not just "Ethiopic" as now, and not "Kidān zaʾǝgziʾǝna..."), this is why we need to have the possibility of a main title

**Comment by PietroLiuzzo** [comment]
for t2,3,4 I would have expected the respective titles to be there, not the latin with an appended information in brackets.

in LIT2444Temher I think you are extending the practice with placeName and persName to title, while for this we decided to use ref[@type="work"] (see: https://github.com/SChAth/ScAthiop/wiki/guidelines#references ) especially in a paragraph description.

please note that we don't use role="createdRecord" as such information belongs to the change element

 The issue remains at the moment unaltered although.

**Comment by PietroLiuzzo** [comment]
now links behave like the header and will display t1
