### ISSUE TITLE
Homilies on Melchizedek

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#2691]
We have two CAe Ids for two homilies om Melchizedek , 3326 and 3327, but CPG has one number 5280 and it seems that there is no independent circulation apart from a single fragment in Yerevan as I see from a recent PR by @nafisa-valieva .
 If both homilies are always transmitted together and correspond to one CPG item I wonder if we need two separate CAe IDs. 
Are two CAe IDs justified or should rather be merged?

@abausi @thea-m @karljonaskarlsson 

_Originally posted by @eu-genia in https://github.com/BetaMasaheft/Works/pull/1310#discussion_r1838016866_

**Comment by eu-genia** [comment]
@AaronButts feel free to share your opinion.

**Comment by AaronButts** [comment]
Thanks, @eu-genia. It is of course a difficult question, getting at what constitutes a text. But, I would personally suggest leaving the two different CAe numbers. I looked at several of the manuscripts quickly, and they would seem to demarcate two different texts. It would of course be more definitive to have cases of one of the homilies being transmitted without the other, but, even without that, the fact that scribes seem to have delineated two different texts is enough for me to have two CAe Ids. So I suggest keeping 3326 and 3327.

As for CPG, I am not sure why they have approached it in this way, but I don't like what they have done. If/when CPG is ever updated, redone, etc., maybe they can solve this problem by having a 5280 and 5280 bis or a 5280a and 5280b to correspond to the separate CAe numbers, which reflect the situation in Ethiopic manuscripts, at least how the scribes lay out the texts.

**Comment by nafisa-valieva** [comment]
> Thanks, @eu-genia. It is of course a difficult question, getting at what constitutes a text. But, I would personally suggest leaving the two different CAe numbers. I looked at several of the manuscripts quickly, and they would seem to demarcate two different texts. It would of course be more definitive to have cases of one of the homilies being transmitted without the other, but, even without that, the fact that scribes seem to have delineated two different texts is enough for me to have two CAe Ids. So I suggest keeping 3326 and 3327.
> 
> As for CPG, I am not sure why they have approached it in this way, but I don't like what they have done. If/when CPG is ever updated, redone, etc., maybe they can solve this problem by having a 5280 and 5280 bis or a 5280a and 5280b to correspond to the separate CAe numbers, which reflect the situation in Ethiopic manuscripts, at least how the scribes lay out the texts.

thank you, Aaron! so be it!
