### ISSUE TITLE
https://www.rrz.uni-hamburg.de/beratung-und-hilfe/policies.html

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#270]
check cloud dienst policies

**Comment by PietroLiuzzo** [comment]
@eu-genia do you have any better info on this from the Akadamie side?

**Comment by PietroLiuzzo** [comment]
the email of 21.12.16 does not seam to concern our use of GIT, but perhaps we ought to clarify this.

**Comment by eu-genia** [comment]
i think i had mentioned at the beginning: the university strongly disapproves of googledrive, gmail, dropbox, and other "insecure" storages. honestly i believe that if one explicitly asks they will say the same is valid for git. yet, the local services are extremely slow and inefficient, i only use uhhdisk for backups... akademie does not have any guidelines in this respect, but ERC does approve placing everything in public domain, and as we also use ERC project data i think we can justify our choices in this way.
