### ISSUE TITLE
name of the record is missing online

### ISSUE THREAD

**Issue by nafisa-valieva** [SChAth/ScAthiop#2703]
Dear Eugenia,
I have just checked the visualisation of the record and see that the name of the insitution is absent. All I see is Nafisa Valieva. 

[https://betamasaheft.eu/institutions/INS1021Matenadaran/main]
Is there anything I should fix or you can fix? (I put bug as a label, please correct it if it is wrong!)
Thank you very much in advance!

**Comment by eu-genia** [comment]
This is not a bug. The name can only appear after a second merge or records need to be manually expanded.
When you do the first merge the name is stored in a list.
When you update the record the name is extracted from the list. That's the way it works. I will update it manually for you.

**Comment by eu-genia** [comment]
fixed

**Comment by nafisa-valieva** [comment]
> fixed

thank you!
