### ISSUE TITLE
links in text transcription

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#271]
When adding text to manuscript entries in the body, the website (for example http://betamasaheft.aai.uni-hamburg.de/text/BNFet71) displays the ID of the Item when indicated, such as p1_i7, but doesn't link to the corresponding section in the entry.
I believe this would be helpful (possibly also to display the title of p1_i7 in addition to "p1_i7"). Currently the only way for users to know which work the text is actually taken from is to go back to the entry and find p1_i7 there.
(Possible of course that all of this works and I made mistakes in my records)
What I wrote in the record is:

````xml
<div type="edition">
       <div type="textpart" subtype="chapter" n="8"  xml:lang="gez" xml:id="Chapter8" corresp="#p1_i7">
          <ab>
     <locus target="#50v"/>````

**Comment by PietroLiuzzo** [comment]
now the app prints for the @corresp the title as in the msItem and the link to the item in the manuscript catalogue view. consider adding the @corresp only once at the outermost level. so for example in the div[@subtype='book'] so it will not be reproduced every time

**Comment by PietroLiuzzo** [comment]
@thea-m please close if ok
