### ISSUE TITLE
Update LIT6936TarWaAmidBeta (Texts, translations, witness BnF Éth. 211)

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [SChAth/ScAthiop#2710]
@eu-genia @thea-m @MagdaKrzyz @nafisa-valieva @karljonaskarlsson 

I want to update LIT6936TarWaAmidBeta with texts and translation that are available in editions (partial editions by myself, Budge, Derat/Seignobos). I have already started with this task.

I want to record all manuscripts, that have been used in these editions as witnesses in sourceDesc. For this reason, I need a stub for one manuscript in Paris. As far as I can see, we do not have a record in Bm so far:

1. Bibliothèque Nationale de France (Paris), Collection Mondon-Vidailhet, Éthiopie 211 ([BnF](https://gallica.bnf.fr/ark:/12148/btv1b525068170.r=%C3%A9thiopien%20211?rk), Chaîne, Marius: Cataloque des manuscrits éthiopiens de la Collection Mondon-Vidailhet, Paris: 1913, S. 14 (= no. 25).)

If I have not overseen anything and in case noone is just working on it at the moment, can I create a stub and name it BNFet211?

**Comment by thea-m** [comment]
It seems good to me, go ahead!

**Comment by CarstenHoffmannMarburg** [comment]
I also found another manuscript in the edition of Derat and Seignobos, which is indicated as "manuscrit 330 de la NALE" (bm:DeratSeignobos2015Moise on page 276). I like to create a stub also for this manuscript and name it NLA330 acording to the numbering of NALE manuscripts in the folder AddisAbabaNALE.

**Comment by CarstenHoffmannMarburg** [comment]
I added the edition of the Geographical treatise, which is based on my own edition to the record of LIT6936TarWaAmidBeta. Unfortunatly, the push did not make it to Github website. I got a Unicorn instead:
![Screenshot 2024-12-03 201122](https://github.com/user-attachments/assets/74dfb69f-d5ae-43a2-ab13-5088e096f8cf)
Is a change of about 500 lines of Ethiopic text to much for the app?

**Comment by eu-genia** [comment]
GitHub is not a website. 

Why do you think that something did not come through? Do you not see the changes [here](https://github.com/BetaMasaheft/Works/commit/2a5c86c5ac4504de31da48d6b0fe769e5a7443e7) among the files?
