### ISSUE TITLE
Dossier on ʾAbbā Yoḥanni 

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#2711]
LIT1521GadlaY corresponds to the Life of ʾAbbā Yoḥanni of Dabra ʿAśā as published by Basset. However, MS Ethio-SPaRe ADMY-014 has a much longer text, subdivided into 12 monthly readings, as well as a cycle of 24 short miracles and a malkǝʾ-hymn.
Moreover, MS Ethio-SPaRe ADMY-003 hosts two malkǝʾ-hymns to the same saint.
I would like to create new work records for these undocumented texts.
They will be indicated in a contribution I am  going to submit for the Proceedings of the II Colloque sur les études éthiopiennes.

I do not know if the single miracles also circulate independently or only as a cycle, because MS ADMY-014 is the only manuscript in which they are attested. Anyway, do you suggest me to create 24 different work records for the single miracles?

**Comment by thea-m** [comment]
Wonderful, please go ahead!
In analogy with other miracles, I think that it would be useful to create individual records, which would also have the advantage of producing a CAe ID for each miracle. This will be time-consuming, and as this is your own work I believe creating one record with all miracles as textparts would also be legitimate.

**Comment by CarstenHoffmannMarburg** [comment]
I would suggest to create one more CAe for the newly work in total and sub-IDs for each miracle or any other part, which are contained in it or in the existing LIT1521GadlaY. This is the easier and faster way to do it and as far as I know, this is our strategy, if no independant circulation of any textpart can be verified.
