### ISSUE TITLE
app rendering of note in bibl

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#2712]
The content of `<note>` inside `<bibl>` is currently printed without space following the content of `<citedRange>`, see examples from LIT3110RepCh390 and LIT1425GadlaA. 
![image](https://github.com/user-attachments/assets/381979ee-3a86-44b8-a1d6-fd3742d55556)
![image](https://github.com/user-attachments/assets/b3cd8c24-597b-480b-ac65-2693cdde0ab6)

Would it be possible to add a space? I personally would probably prefer the content of the note to be printed after a line break, to make clear that it is a comment on the reference and not part of it. What do you think?

@eu-genia

**Comment by eu-genia** [comment]
Sure, this is possible, but I am currently putting all visualization issues on wishlist as they may be superceded by the new TEI Publisher release.

**Comment by eu-genia** [comment]
would it not be better than note by default is rendered as e.g.

text text text (notenotenote) (in brackets after a space)

?

**Comment by thea-m** [comment]
Yes, that also works well, thank you!
