### ISSUE TITLE
"Malkǝʾa Fānuʾel" used as protective text

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#2714]
I would like to create a new work record for the beginning of Malkǝʾa Fānuʾel used as a protective text, attested in the scroll RDW009 (see branch of the same name): 
   ```
     <lb n="1"/><hi rend="rubric">በስመ አብ ወልድ
                  <lb n="2"/>ወመንፈስ ቅዱስ
                  <lb n="3"/>፩ አምላክ</hi>
                  <lb n="4"/>ጸሎት በእንተ
                  <lb n="5"/>ዓይነ ጥላ ወመ
                  <lb n="6"/>ደንግግጸ አጋ
                  <lb n="7"/>ንንት ወመደን
                  <lb n="8"/>ግጸ ሰይጣናት
                  <lb n="9"/>ሰላም፡ ለተፈ
                  <lb n="10"/>ጥሮትከ ም
                  <lb n="11"/>ስለ መላእክ
                  <lb n="12"/>ት ሕቡረ እን
                  <lb n="13"/>ዘ ኢይከውን
                  <lb n="14"/>ቅድመ ወእን
                  <lb n="15"/>ዘ ኢይዴኅር
                  <lb n="16"/><gap reason="illegible"/>ድኅረ፡ ሰዳ
                  <lb n="17"/>ዴ አጋንንት፡
                  <lb n="18"/>ፋኑኤል፡ እም
                  <lb n="19"/>ላእለ ፍጡሩ
                  <lb n="20"/>ን ወትረ ሰድ
                  <lb n="21"/>ዶሙ ለአጋን
                  <lb n="22"/>ንት ወአርእ
                  <lb n="23"/>ዮሙ ሐሰረ ከ
                  <lb n="24"/>መ፡ ኢይግበሩ
                  <lb n="25"/>ኪያየ ማሕ
                  <lb n="26"/>ደረ አድኅና
                  <lb n="27"/>ወእቀባ፡ ለአመ
                  <lb n="28"/>ትከ፡ <persName ref="PRS13479Rahmat" role="owner"><hi rend="rubric">ራሕማት</hi></persName>
```

A possibly longer excerpt (or the entire text?) with protective function is also attested in BLorient3716a. I think it would make sense to distinguish the text in this function from the "proper" Malkǝʾ, attested for example in BLorient5422. I propose to create a new ID that serves as general ID for Malkǝʾa Fānuʾel (or excerpts) as a protective text.
Any objections?
@CarstenHoffmannMarburg @nafisa-valieva @eu-genia @MagdaKrzyz

**Comment by CarstenHoffmannMarburg** [comment]
It sounds reasonable. However, there are many scrolls, that contain various texts, which appear also in other circumstances. The "magic" use in a sense that is considered to invoke supernatural powers is an ambiguous criteria, that can also be considered for liturgical books. I would agree to create a new CAe, if it is a distinguishable textual unit, that was used for 'magic' purposes. For other texts as salāms or prayers, I would not support the idea to create a second ID for each of them, that is attested in a magic scroll. In the latter cases, I would suggest to keep one ID and remark the double use in an abstract.

**Comment by eu-genia** [comment]
Please see also https://github.com/BetaMasaheft/Documentation/issues/2640 to avoid double work.
I am gradually importing data into Malke'at, I have now updated 2765, 2885, and 6491, the latter has now a more extensive set of stanzas with xml:id so I would rather say, it is enough to refer to add the necessary xml:id to relevant stanzas and refer to them (?)

**Comment by thea-m** [comment]
Thank you, the updates are very helpful. I would however prefer to encode the text with an individual work ID (rather than as LIT6491MalkeaFanuel#masgabiya), as its introductory formula and final supplication mark it as a self-contained textual unit. This would also follow the analogy of the first verses of the Gospel of John (LIT5920JohnBeg), which are similarily attested as a self-contained textual unit in scrolls.

**Comment by eu-genia** [comment]
Ok for me
