### ISSUE TITLE
EMIP00851 manifest incorrect

### ISSUE THREAD

**Issue by joergleh** [SChAth/ScAthiop#2716]
https://betamasaheft.eu/api/iiif/EMIP00851/manifest - the "canvases" element contains the value "null" and does not contain any links to image files

**Comment by eu-genia** [comment]
https://github.com/BetaMasaheft/Documentation/issues/2017 for some EMIP mss the n has not been provided yet. We are working through them, but some may still be incomplete. In all such cases the manifest will not be available.

Fixed now for 851
