### ISSUE TITLE
Miracles of Raphael

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#2719]
I would like to encode Miracles of Raphael in ANLcr3.
We currently have:
LIT1297Dersan (Dǝrsāna Rufāʾel, ID for the homiliary which can also include miracles, some already encoded as textparts)
LIT2387Taamme (Taʾammǝra Rufāʾel, currently no textparts)
I would propose to create work records for the individual miracles that are attested in ANLcr3, and include their references to the existing works. Since they are attested in different collections in varying groups, I think it is better to create individual IDs, also in view of https://github.com/BetaMasaheft/Documentation/issues/1985

Any objections?
@eu-genia @CarstenHoffmannMarburg @nafisa-valieva

**Comment by CarstenHoffmannMarburg** [comment]
I have no objection to this strategy.

**Comment by nafisa-valieva** [comment]
This sounds good! thank you!

**Comment by eu-genia** [comment]
Thank you, just as with https://github.com/BetaMasaheft/Documentation/issues/2361 a clear disambiguation and linking of Dersan and Miracle set is necessary.

**Comment by eu-genia** [comment]
Nb i have updated xml Ids in this ms as well in the dersana mikael branch

**Comment by thea-m** [comment]
Thank you, I will update them in my branches for ANLcr2 and 3 before making a PR so that hopefully there should be no conflicts
