### ISSUE TITLE
references not displayed

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#272]
In BNFet71, the references `<ref target="#Chapter8"/>` and `<ref target="#Chapter19"/>` are not displayed on the website

````xml
<note>See for excerpts from this work <ref target="#Chapter8"/> and <ref target="#Chapter19"/>.</note>
````

http://betamasaheft.aai.uni-hamburg.de/manuscripts/BNFet71#p1_i7

**Comment by thea-m** [comment]
This kind of reference is never displayed. Is it wrong?

**Comment by PietroLiuzzo** [comment]
it is ok. please check if now it is satisfactory. when the matching element with the given id is a div It points to the text view for that div and prints the @subtype and @n of the div as text for the link

**Comment by PietroLiuzzo** [comment]
@thea-m please close if ok
