### ISSUE TITLE
new records RDW009

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#2722]
I would like to create new records for three protective texts contained in the scroll RDW009 (see branch of  the same name). I could find none of them on the app.

1. Prayer against the evil eye and for the drowning of demons, containing ʾasmāt and the names of the days of the week
ጸሎት፡ በእንተ፡ ዓይነ፡ ጥላ፡ ወመስጥመ፡ አጋንንት፡ ዘአሰሞሙ፡ ለእስክንድር፡ ንጉሥ፡ አጋንንት፡ ንጉሠ፡ ቀለይ፡ ወምድር፡ ወባሕር፡ ኢይራፎን፡ ውልዊት፡ ለአብኤልክስ፡ በኤል፡ ለአብኤልክስ፡ በኤል፡ ሰአብኤልክስ፡ በኤል፡ አማኑኤል፡ አማኑኤል፡ ዘተደመራ፡ ለእለተ፡ እሁድ፡ ዘተደመራ፡ ለእለተ፡ ረቡዕ፡ ዘተደመራ፡ ለእለተ፡ ሐሙስ፡ ዘተደመራ፡ ለእለተ፡ ዓርብ፡ ዘተደመራ፡ ለእለተ፡ ቀዳሚት፡ ሂጥ፡ ተመይጥ፡ እምላእለ፡ አመትከ፡ ራሕመት፡

2. Prayer against the evil eye for birth
በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩፡ አምላክ፡ ጸሎት፡ በእንተ፡ ዓይነ፡ ጥላ፡ ሕማመ፡ ጽንእ፡ አሌፍ፡ ስሞ፡ ኮ፡ አርግስይ፡ `<gap reason="illegible"/>`፡ በማሕ፡ ጸና፡ ሄምራ፡ ሕፍና፡ ማሕጸና፡ ሆው፡ ይምጸእ፡ በስምረትከ፡ ደመ፡ ተክቶ፡ ሃ፡ ወልደ፡ ዘንብለከ፡ ዘይት፡ ዘከር፡ እግዚኦ፡ እለ፡ ዘን`<gap reason="illegible"/>`፡ ለከ፡ ሔት፡ ክፍለለ፡ ወሊድ፡ ወልደ፡ ዘይበቁዕ፡ ለአመትከ፡ ራሕመት፡ የፈንታየ፡ ልጅ፡ ራሕመት፡

4. Prayer against haemorrhage
ጸሎት፡ በእንተ፡ ደም፡ ክተረም፡ ክተረም፡ ክተረም፡ ዘወጽአ፡ ደም፡ እምገቦሁ፡ ለእግዚእነ፡ ኢየሱስ፡ ክርስቶስ፡ እንዘ፡ ይጸእ፡ ስሬ፡ ፌራወ፡ ወመጋኛ፡ ፈንዘ፡ ወተያያዢ፡ ቀንተው፡ ቀርለው፡ ሮተ፡ ሶተ፡ ምለናክፈም፡ ፈለ፡ ፈለማይ፡ አዶናይ፡ ይትበሃል፡ በ፲ቃላተ፡ ኦሪት፡ ወበ፮፡ ቃላተ፡ ወንጌል፡ በከመ፡ ከተርኮ፡ ደማ፡ በቃለ፡ ኤልያስ፡ ነቢይ፡ ከማሁ፡ ክተር፡ ደማ፡ በማኅጸና፡ ለአመትከ፡ ራሕመት፡ የፈንታየ፡ ልጅ፡ ሳዶር፡ አላዶር፡ ደናት፡ አዲሩ፡ ሮዳስ፡ እቀባ፡ ለአመት፡ ከራሕመት፡ ወገጹ፡ ዘፍእም፡ በጽልመት፡ ፈርሃ፡ ወደንገጸ፡ ዲያብሎስ፡ እዮብ፡ `<gap reason="illegible"/>`፡ ተልጸት፡ በሠጋ፡ አምላክ፡ በሲኦል፡ እቀባ፡ ወአድኅና፡ ለአመትከ፡ ራሕመት፡ የፈንታየ፡ ልጅ፡ ሳዶር፡ አላዶር፡ ደናት፡ አዲሩ፡ ሮዳስ፡ እቀባ፡ ለአመት፡ ራሕመት፡ ወገጹ፡ ዘፍእም፡ በጽልመት፡ ፈርሃ፡ ወደንገጸ፡ ዲያብሎስ፡ እዮብ፡ እቀባ፡ ለአመትከ፡ ራሕመት፡

@CarstenHoffmannMarburg @MagdaKrzyz

**Comment by CarstenHoffmannMarburg** [comment]
I did not find any corresponding works or texts in manuscripts either.
