### ISSUE TITLE
Trial to create a personal record

### ISSUE THREAD

**Issue by MagdaKrzyz** [SChAth/ScAthiop#2724]
I tried to create a new personal record and I got this message. I clicked twice so maybe I have made a problem (told me Dorothea). Can you retrieve the file or shall I create a new one? 
![Zekrestos_screenshot](https://github.com/user-attachments/assets/06399c3c-df05-46da-b770-c5f4259c3068)

**Comment by eu-genia** [comment]
The record has not been created. 
You were not logged in.
