### ISSUE TITLE
Controlling LIT1295Dersan, Updating Witlist: Stub for BNFet346

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [SChAth/ScAthiop#2725]
@eu-genia @thea-m @nafisa-valieva 

I wanted to control my latest changes to LIT1295Dersan after it was merged. I saw, that the witness of BNFet346 was not properly represented on the website. This happened, because there is no record for this manuscript. I can create one, if you agree and if there is no other branch or nobody, who is working on it at the moment. 

However, I have also seen, that BNFet346 is not mentioned at all in this work record except for the witList. As far as I understood our [latest discussion on witList](https://github.com/BetaMasaheft/Documentation/issues/2699), only those manuscripts should be listed there, that play a role in the edition in this record or in any printed editions or secondary literature. If I am correct, this manuscript should be deleted from the witList. Do you agree? Do you want me to create a stub for BNFet346 or do you want me to delete the manuscript from the witList?

There are also some information commented out in listWit. I do not know, what "mini mss" is about and I do not know "Bachmann's edition", but I want to find out and try to integrate it to the bibliography and to the witlist soon and update LIT1295Dersan together with some other changes as for example the one indicated by Dorothea in https://github.com/BetaMasaheft/Documentation/issues/2723.

**Comment by eu-genia** [comment]
the decision is we should list in the list of witnesses (`listWit`) as many of the witnesses that we know to contain the work as we judge necessary and important, especially if these witnesses are useful for research history, identification, completeness or other purposes and not extensively already described on Bm.
The presence of the work in BNFet346 must be known from some source so it is fully OK to have it among the witnesses, of course, for that a stub is needed. You do not have to open issues to create stubs for manuscript records, just mark them as [stub](https://github.com/BetaMasaheft/Documentation/issues/2700)

**Comment by eu-genia** [comment]
Issues are only necessary for **new work IDs** because of the importance of the unique Clavis IDs. All other types of records (manuscripts, places, persons) may be created and suggested directly through pull request.
