### ISSUE TITLE
Bibliography of LIT4099MashafaT

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#2726]
BAVet123 contains a few texts, among which a Tǝrgʷāme fidal.

`LIT4099MashafaT` points to the Maṣḥafa tǝrgʷāme fidal. In the work record there are three bibliographic references, among which `bm:Dillmann1847BM`, which correctly identifies Dillmann's _Catalogus codicum manuscriptorum orientalium qui in Museo Britannico asservantur_. This is right, because the work is found in two manuscripts of the BL.
However, this reference is visualized in the app as Dillmann, C. F. A. 1848. _Catalogus codicum manuscriptorum Bibliothecae Bodleianae Oxoniensis, Pars VII: Codices Aethiopici_ (Oxonii: E Typographeo Academico, 1848) (here: https://betamasaheft.eu/works/LIT4099MashafaT/main).
There is no error in Zotero, because the British Library catalogue is tagged as `bm:Dillmann1847BM` and the Oxford catalogue is tagged as `bm:Dillmann1848Catalogus`, and there is no error in the work record, where the correct tag for the British Library is used. So, why does the app wrongly display the reference for the Oxford catalogue?

**Comment by eu-genia** [comment]
You can easily see https://betamasaheft.eu/works/LIT4099MashafaT.xml that the record present in the app has bm:Dillmann1848Catalogus.

**Comment by eu-genia** [comment]
Probably some merge happened when app was online and never made it to the web application. In doubt please always control the version online by adding .xml after the filename and check the last change element. If needed I can always update manually.
Done.
