### ISSUE TITLE
New work in BAVet123

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#2727]
BAVet123 contains the following prayer, entitled  ጸሎተ፡ ማዕድ or Ṣalota māʿǝdd (transcription of ማዕድ taken from Leslau), translated as "prayer of the banquet" or "prayer of the meal".
Incipit: ጸሎተ፡ ማዕድ፡ አቡነ፡ ዘበሰማያት፡ በል፡ ወአንብሮ፡ በቅድሜከ፡ ዘትጥዕሞ፡ ቅዱስ፡ ቅዱስ፡ ቅዱስ፡ እግዚአብሔር፡ ዘአውረድከ፡ መና፡ ለእስራኤል፡ በገዳም፡ ወነአምን፡ ከመ፡ ኵሎ፡ ትክል፡
Explicit: ባርኮ፡ በአፈ፡ ኵሉ፡ ፍጥረት፡ ለአለመ፡ ዓለም። ኪርያላይሶን፡ በ፡ ፫ ጊዜ፡ ባርክ፡ ፫ ጊዜ፡ ወጠዓም፡ በፈሪሃ፡ እግዚአብሔር፡ ወዓይንከ። ...

I could not find any reference in the database. Shall I proceed?

**Comment by CarstenHoffmannMarburg** [comment]
I did not find anything, either.
