### ISSUE TITLE
Miracles of Gabriel

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#2728]
I would like to create new records for 15 miracles of Gabriel attested in ANLcr3 (see branch with the same name) for which I could find no existing IDs, and add a relation to LIT4652TaammeraGa and LIT1284Dersan. I have searched for the attestations of these two records and for excerpts and keywords from the miracles.
Any objections?
@CarstenHoffmannMarburg @eu-genia @nafisa-valieva

**Comment by eu-genia** [comment]
Wonderful thank you

**Comment by nafisa-valieva** [comment]
I have no objections!
