### ISSUE TITLE
rubrication

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#273]
The guidelines state two places to indicate rubrications:
- as a `<decoNote> `
- in `<seg type=“rubrication”>` in `<handNote>`

Is there a difference in the use?  `<seg type=“rubrication”>` seems to be more precise and is also used more often as far as I see.

**Comment by PietroLiuzzo** [comment]
https://github.com/SChAth/ScAthiop/issues/79#issuecomment-226742269

**Comment by PietroLiuzzo** [comment]
https://github.com/SChAth/ScAthiop/wiki/guidelines#rubric

**Comment by thea-m** [comment]
Please, could we agree on a standard for rubrications?
I believe the encoding as a decoNote has been used for the ES manuscripts, otherwise `<seg type=“rubrication”>` is more common in our records
@eu-genia

**Comment by MassimoVilla** [comment]
I have been regularly encoding rubrications within `<handNote>` in  `<ab type="rubrication"/>` (instead of `<seg type="rubrication"`) since it was the way foreseen in the modelfileManuscriptSimple.xml. 
So we actually have now three ways of encoding rubrication.
A standard is needed before transforming the minority choices into the most common one.

**Comment by PietroLiuzzo** [comment]
the guidelines (sorry for the unupdated minifiles!) on this are quite clear.
https://github.com/SChAth/ScAthiop/wiki/guidelines#hands-description

    `<seg type="rubrication"/>`

is correct.

**Comment by PietroLiuzzo** [comment]
action items

- [ ] update minified records
- [ ] correct files where ab[@type="rubrication"] is used

ES files are to be conformed, probably will require previous hand testing to set rules stright

**Comment by PietroLiuzzo** [comment]
The main guidelines page has been updated and the mini files have been moved to a deprecated folder as they are out of date. further references to such files should be fixed as soon as they are found
