### ISSUE TITLE
Magic prayer in UUB O Etiop. 45

### ISSUE THREAD

**Issue by karljonaskarlsson** [SChAth/ScAthiop#2731]
Hello!

I'm encoding a magic "wall amulet" from Uppsala and wonder about some works. I apologize in advance for the tedious questions that will come but would appreciate some input from people who have worked more with manuscripts like this.

There is one prayer in the amulet that begins and ends like this:

```
<incipit xml:lang="gez">
<hi rend="rubric">በስሙ፡ ለአብ<supplied reason="omitted">፡</supplied> 
በስሙ፡ ለወልድ፡ በስሙ፡ ለመንፈስ፡ ቅዱስ፡ ታኦስ፡ አ</hi>ዝዮስ፡ ማሲ፡ ማስዮስ፡ 
አቅዴፌር፡ በስሙ፡ በሐራዋን፡ ሐሪ፡ ፌኬር፡ በጠጁን፡ ዘሐጁን፡ ፌልፌልማኤል፡ 
በስመ፡ አልዶር፡ አዳናትፌዳ፡ ታኦስ፡ አብሽቱር፡ ፀባዖት<supplied reason="omitted">፡</supplied>
 ጮሕ፡ ዋረቅ፡ ሐሩርቃኤል፡ በዝንቱ፡ አስማተ፡ ቃልከ፡ ስሑል፡ እሳተ፡ መለኮት፡ 
መግዝም፡ ምን<supplied reason="omitted">፡</supplied> እንዳለህ፡ አሞር፡ ኤሴር፡
</incipit>

<explicit>
ወይፃዕ<supplied reason="omitted">፡</supplied> መንፈስ፡ ርኩስ፡ ወለዘአሐዞ፡ ሰብእ፡ 
ወተግባረ፡ ሰብእ፡ ወኀበ፡ ቦአ፡ ዝንቱ፡ ጸሎት፡ ይሰደድ፡ <sic resp="JK">እምላለ፡</sic> 
ዝንቱ፡ ቤት፡ አሜን፡ አልፋ፡ አልፋ፡ አልፋ፡ አልፋ፡ ፃዕ፡ ፃዕ፡ ወወጺአከ፡ ኢትግ<del rend="effaced">ባ</del>ባዕ፡ 
አልፋአ፡ አልፋአ<supplied reason="omitted">፡</supplied> ፃዕ፡ ይቤለከ፡ ኢየሱስ፡ ክርስቶስ፡ 
ወዝክረ፡ ስምከ፡ ይደምሰስ፡ ለዓለመ፡ ዓለም፡ አሜን፡ ይሰደድ፡ ጋኔን፡ ላዕለ፡ አመትከ፡ 
<hi rend="rubric">ወለተ፡</hi>
<subst><del rend="effaced" unit="chars" quantity="5"/><add>ማርያም<supplied reason="omitted">፡</supplied></add></subst>
</explicit>
```

It's quite close to LIT6851Prayer (https://betamasaheft.eu/works/LIT6851Prayer/text), but do you think it's close enough to identify them as the same text?

@CarstenHoffmannMarburg @thea-m @eu-genia

**Comment by thea-m** [comment]
Only the first words seem to be very close, so I would cautiously say no. If you want, you could check whether the text following the incipit remains close (and the divergence only happens in the explicit), but based on these excerpts I think a new record might be warranted.

**Comment by CarstenHoffmannMarburg** [comment]
> Hello!
> 
> I'm encoding a magic "wall amulet" from Uppsala and wonder about some works. I apologize in advance for the tedious questions that will come but would appreciate some input from people who have worked more with manuscripts like this.
> 
> There is one prayer in the amulet that begins and ends like this:
> 
> ```
> <incipit xml:lang="gez">
> <hi rend="rubric">በስሙ፡ ለአብ<supplied reason="omitted">፡</supplied> 
> በስሙ፡ ለወልድ፡ በስሙ፡ ለመንፈስ፡ ቅዱስ፡ ታኦስ፡ አ</hi>ዝዮስ፡ ማሲ፡ ማስዮስ፡ 
> አቅዴፌር፡ በስሙ፡ በሐራዋን፡ ሐሪ፡ ፌኬር፡ በጠጁን፡ ዘሐጁን፡ ፌልፌልማኤል፡ 
> በስመ፡ አልዶር፡ አዳናትፌዳ፡ ታኦስ፡ አብሽቱር፡ ፀባዖት<supplied reason="omitted">፡</supplied>
>  ጮሕ፡ ዋረቅ፡ ሐሩርቃኤል፡ በዝንቱ፡ አስማተ፡ ቃልከ፡ ስሑል፡ እሳተ፡ መለኮት፡ 
> መግዝም፡ ምን<supplied reason="omitted">፡</supplied> እንዳለህ፡ አሞር፡ ኤሴር፡
> </incipit>
> 

There is a strong similarity, because both texts contain **ታኦስ፡ አዝዮስ፡ ማሲ፡ ማስያስ፡ አብፌድርስ፡** in the incipit. We cannot follow up, because, we do not have images for BDLeu7. I think, both options are possible and legitimate. I would recommend to be rather more cautious and create a new record, as Dorothea did, and mark the strong similarity and the possibility or even probability of identical texts in an abstract and in a relation.

**Comment by eu-genia** [comment]
I keep thinking about all those magic texts and keywords and similarities and differences and now start developing an inclination to create a set of narrative units (similar to art themes in painting) for main topoi of magic prayers that then the textual individual IDs could all be linked to.
Keywords https://github.com/BetaMasaheft/Authority-Files/pull/33 are too general and the list cannot be indefinite, individual IDs do not allow sufficient possibilities for grouping similar texts together, but possibly narrative units for themes could be an additional way of structuring data.

**Comment by CarstenHoffmannMarburg** [comment]
I think, that ታኦስ፡ አዝዮስ፡ ማሲ፡ ማስያስ፡ አብፌድርስ፡ are either ʾasmāt or qālāt and they can be marked with keyword 'asmat'. I think, that creating narrative ID could be an option for similiraties in the exhortation (what a prayer does) and for the enforcements (what is said in support of the exhortation) if this enforcement is based on biblical or other narratives. I think, it is not recommendable to create narratives for qālāt or ʾasmāt, because they are  too multifold and better to be found in searches or in relations.

**Comment by karljonaskarlsson** [comment]
Thank you! I will create a new work and mark the relations
