### ISSUE TITLE
"Walatta" search error

### ISSUE THREAD

**Issue by karljonaskarlsson** [SChAth/ScAthiop#2736]
When I search for "walatta" (https://betamasaheft.eu/simpleSearch.html?query=walatta), the following error message appears:

An error has occurred
something has gone wrong. Sorry! This error has been generated by the application.

err:XPTY0004 Grouping variable t evaluates to more than one item [at line 1542, column 23, source: /db/apps/BetMasWeb/modules/app.xqm]
In function:
	app:paginateNew(node(), map(*), xs:int, xs:int, xs:int, xs:int) [-1:-1:/db/apps/BetMasWeb/modules/app.xqm]
	templates:process-output(element(), map(*), item()*, element()) [211:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call-by-introspection(element(), map(*), map(*), function(*)) [189:28:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call(item(), element(), map(*)) [137:36:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [237:13:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [148:81:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [428:17:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process-output(element(), map(*), item()*) [230:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process-output(element(), map(*), item()*, element()) [211:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call-by-introspection(element(), map(*), map(*), function(*)) [189:28:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:call(item(), element(), map(*)) [137:36:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [133:51:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:process(node()*, map(*)) [90:9:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]
	templates:apply(node()+, function(*), map(*)?, map(*)?) [50:5:/media/add/exist/exist2/data/expathrepo/shared-0.9.1/content/templates.xql]

@eu-genia (I would also appreciate feedback on the issue – is this a good way of reporting errors like this?)

**Comment by eu-genia** [comment]
Yes this  is a good way, but it may take a while to know which of the many manuscript records containing the word "walatta" causes the problem

However I can tell you that the issue only regards manuscripts so you can search for walatta everywhere else https://betamasaheft.eu/as.html?query=walatta&homophones=true&AttestedInType=1&xmlid=&work-types=work&work-types=nar&work-types=pers&work-types=place&work-types=ins

**Comment by karljonaskarlsson** [comment]
Ok, thank you! :)

**Comment by eu-genia** [comment]
fixed

**Comment by eu-genia** [comment]
part of the problem ![image](https://github.com/user-attachments/assets/e0a4813f-d9bb-4ee4-a425-34303ec06efd)
for some reason a Berlin ms got copied to Vatican

**Comment by eu-genia** [comment]
the issue is back after reboot

**Comment by eu-genia** [comment]
`HTTP ERROR 500 javax.servlet.ServletException: javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMasWeb/manuscripts/BNFet117/main: null`

fixed

BLorient3663 reexpanded for error in LIT7094PrayerDevils (multiple ids)

all works again but new fixes may be needed on reboot
