### ISSUE TITLE
Third magic prayer in UUB O Etiop. 45

### ISSUE THREAD

**Issue by karljonaskarlsson** [SChAth/ScAthiop#2738]
A third prayer in UUB O Etiop. 45 begins and ends like this:

```
<incipit xml:lang="gez">
<hi rend="rubric">በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩አምላክ<supplied reason="omitted">፡</supplied></hi>
ያቂ፡ ወያቂ፡ አንተ፡ ሰይጣን፡ ወአንተ፡ ባርያ፡ ወአንተ፡ ሌጌዎን፡ ወአን፡ ጋኔን፡ ወአንተ፡ ደስክ፡ 
ወጉዳሌ፡ አንተ፡ ሥራይ፡ ወአንተ፡ ዓይነት፡ አንተ፡ ውግዓት፡ ወቍርጥማን፡ ዘትትሜሰል፡ 
በብዙኅ፡ ጾታ፡ አራህድራህያ፡ ምራኤል፡ ኃያል፡ እግዚአብሔር፡ አዶናይ፡ ቅዱስ፡
ወልደ<supplied reason="omitted">፡</supplied> ወልደ፡ ክርስቶስ፡ ነገርኩክሙ፡
በሎፍሐም፡ 
</incipit>

<explicit>
ፒልፒልማኤል፡ ያሽኩት፡ አምደ፡ ብርሃን፡ ልብርሃን፡ ይበርቅ፡ በቅ<surplus>ድ</surplus>ድመ፡ 
ገጹ፡ ወለኃይለ፡ ጸላኢ፡ ባርያ፡ ወለኃይለ፡ ፀላኢ፡ ዓይነት፡ ወሥራይ፡ ወለኃይለ፡ ፀላኢ፡ ሌጌዎን፡ 
ወለኃይለ፡ ጸላኢ፡ ጋኔን፡ ወጉዳሌ፡ ውግዓት፡ ወቍርጥማት፡ ፍልፀት፡ ወቍርፀት፡ ፓንዋማ፡ 
አርዮ፡ ኃይለ፡ ግርማ፡ ንጉሠ፡ ስብሐት፡ ፌማ፡ ኢይርአዩ፡ ገጻ፡ 
ወኢ<supplied resp="JK" reason="omitted">ይ</supplied>ስምዑ፡ ድምፃ፡ 
ወኢይልክፉ፡ ኀበ<supplied reason="omitted">፡</supplied> ነፍሳ፡ ወሥጋሃ፡ 
ለዓመትከ፡ <hi rend="rubric">ወለተ፡</hi>
<subst><del rend="effaced" unit="chars" quantity="7"/><add>ማርያም፡</add></subst>
</explicit>
```

This time, the prayer in the Uppsala ms is similar to a prayer found in https://betamasaheft.eu/manuscripts/BLorient5425/main (ms_i2), where it is classified with the general record LIT5888AsmatPrayer. Do you think it's worth creating a new record for both of these prayers? Or just a new one for the one in the Uppsala manuscript? Or shall I also use the general LIT5888AsmatPrayer for the prayer also in the Uppsala ms? Thank you for your input!

@CarstenHoffmannMarburg @thea-m

**Comment by thea-m** [comment]
I would advise for a new record

**Comment by karljonaskarlsson** [comment]
> I would advise for a new record

For both or just the attestation in UUB O Etiop. 45?

**Comment by CarstenHoffmannMarburg** [comment]
Yes, I think, it is the same prayer and BLorient5425#ms_i2 should be updated as well. If you update it, you can mention the longer and partly different incipit and explicit in BLorient5425#ms_i2.
