### ISSUE TITLE
Fourth magic prayer in UUB O Etiop. 45

### ISSUE THREAD

**Issue by karljonaskarlsson** [SChAth/ScAthiop#2739]
A fourth magic prayer in UUB O Etiop. 45 begins and ends as follows:

```
<incipit xml:lang="gez">
<hi rend="rubric">በስመ፡ አብ፡ ወወልድ፡ ወመንፈስ፡ ቅዱስ፡ ፩አምላክ፡</hi>
ወመጽኡ፡ እሉ፡ አጋንንት፡ <sic resp="JK">ወእግዝትነ፡</sic> <hi rend="rubric">ማርያምሰ፡</hi>
አእመረት፡ ወ፡ ምክሮሙ፡ ወትቤ፡ ዮሳምር፡ አርሞሳድክኤል፡ አዶናኤል፡ ሮሳ፡ ኪራክስክኤል፡ ርድአኒ፡ 
በዛቲ፡ ሰዓት፡</incipit>

<explicit>
ወእምዝ፡ ጸለየት፡ በነገረ፡ ዕብራይስጢ፡ ወትቤ<supplied reason="omitted">፡</supplied>
ኪርምያል፡ አፍዳኮዳዮዳ፡ ሕልማና፡ ያሰርስ፡ ብንያክኤል፡ ሶርስሳብ፡ ሮስሳብ፡ እርዳድ፡ 
ለምንያም፡ አልሚስ፡ ጢራጢብንዮስ፡ ስምዓኒ፡ ለአመትከ፡ 
<subst><del rend="effaced" unit="chars" quantity="7"/><add>ማርያም፡</add></subst>
ወትቤ፡ እግዝእትነ፡ በነገረ፡ ዕብራይስጢ፡ ሶፎሶሮያሮስቦ፡ ወክርሜል<supplied reason="omitted">፡</supplied>
</explicit>

```

This is very similar to what is found in the first addition in https://betamasaheft.eu/manuscripts/EMIP00382/main, where the prayer hasn't been given an ID. Do you think it's worth creating a new record for both of these prayers (although, for the EMIP one, we only have a small excerpt)? Or is it better just to create a new ID for the prayer in the Uppsala manuscript?

@CarstenHoffmannMarburg @eu-genia @nafisa-valieva

**Comment by eu-genia** [comment]
I think one for both is good, thank you!

**Comment by karljonaskarlsson** [comment]
Now the images for the EMIP manuscript are available and it turns out the prayers are different, although they share some asmat at several points. I think it's better to create two different works and mark that there is a relation between them. Sorry for the change of mind!

**Comment by nafisa-valieva** [comment]
> Now the images for the EMIP manuscript are available and it turns out the prayers are different, although they share some asmat at several points. I think it's better to create two different works and mark that there is a relation between them. Sorry for the change of mind!

Sounds good for me!
