### ISSUE TITLE
Fifth magic prayer in UUB O Etiop. 45

### ISSUE THREAD

**Issue by karljonaskarlsson** [SChAth/ScAthiop#2740]
This may be the easiest case. There is also a fifth magic prayer in UUB O Etiop. 45, which begins and ends like this:

```
<incipit xml:lang="gez">
<hi rend="rubric">ጸሎት፡ በእንተ፡ ሕማመ፡ ቍርጥማት፡ በሸበል፡ ሽሩምያል፡ ግርሙ</hi>ያል፡ 
ሳምአም፡ ስያል፡ በዝንቱ፡ አስማቲከ፡ አድኅና፡ ለአመትከ<supplied reason="omitted">፡</supplied>
እምሕማመ፡ ቍርጥማት፡ ወዓይነት፡ ወውግዓት፡ አድኅና፡ ለአመትከ፡ <hi rend="rubric">ወለተ፡</hi>
<subst><del rend="effaced" unit="chars" quantity="7"/><add>ማርያም፡</add></subst>
</incipit>

<explicit>
<hi rend="rubric">ወገጹ፡ ዘፍጹም፡ በጽልመት<supplied reason="omitted">፡</supplied></hi>
ፈርሃ፡ ወደንገጸ፡ ዲያብሎስ፡ ርእዮ፡ ብሁተ፡ ልደት፡ በሥጋ፡ አምላክ፡ በሲኦል፡ በዝ፡ ቃለ፡ 
መለኮትከ፡ ዕቀባ፡ ለአመትከ፡ <hi rend="rubric">ወለተ፡</hi>
<subst><del rend="effaced" unit="chars" quantity="8"/><add>ማርያም፡</add></subst>
</explicit>
```

I haven't been able to find any closer correspondences and would suggest creating a new ID. Do you agree?

@eu-genia @CarstenHoffmannMarburg 

Thank you for your help with these prayers! This is the last one for now :)

**Comment by eu-genia** [comment]
Agree )

**Comment by CarstenHoffmannMarburg** [comment]
You can check LIT6754PPQwertmat. I think, it is probably similar with a different set of ʾasmāt.

**Comment by CarstenHoffmannMarburg** [comment]
It may be useful to compare it also to LIT4577MagicPr.

**Comment by karljonaskarlsson** [comment]
Thank you!
