### ISSUE TITLE
Prayer against vaginal haemorrhage (ጸሎት፡ በእንተ፡ ሕማመ፡ ደም፡ ወውኅዘተ፡ ደም፡ ወትክቶ፡ ሰስሎሜ፡) in BLorient12959

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [SChAth/ScAthiop#2743]
@eu-genia @thea-m @karljonaskarlsson 

I found a prayer in BLorient12959. The incipit is the following:  ጸሎት፡ በእንተ፡ ሕማመ፡ ደም፡ ወውኅዘተ፡ ደም፡ ወትክቶ፡ ሰስሎሜ፡
Strelcyn described it as "Prayer against haemorrhage and especially vaginal haemorrhage"
The word ሰስሎሜ may be a mutilation of ሰሎሞን. It can either be an ʾasmāt-word or a reference to Solomon, who is prominent in magic prayers for fighting demons. I want to create a new ID for this prayer.

I found a prayer in EMIP00287 beginning with ጸሎት፡ በእንተ፡ ደመ፡ ትክቶ፡, where it is referenced with the general record for Asmat prayers (CAe 5888). The concerning image (f. 179v) is currently not available in the viewer (cf. https://github.com/BetaMasaheft/Documentation/issues/2742). If the concerning image was available, I could check, whether it is legitimate to assign a new LIT ID to both attested texts.

**Comment by eu-genia** [comment]
images are available, thank you

**Comment by CarstenHoffmannMarburg** [comment]
I have checked the prayer in EMIP00287#a8 (f. 179v, bottom) and found no parallels except for the word ትክቶ. So, I will not include it in the new LIT record.
