### ISSUE TITLE
locus of mspart

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#275]
Can we use locus somewhere to specify the folia of a msPart?
Eg BLorient490, the msPart 2 is ff. 30-33, the text is on ff. 31-32
Would
```
<extent>
                                    <measure unit="leaf">4</measure>
                                    <locus from="30" to="33"/>
                                </extent>
```
work or is there a better way? (if this works: at the moment naturally this is not visualized)

**Comment by PietroLiuzzo** [comment]
in the website, I see **4 (leaf) ff. 30-33**. Is this incorrect?

**Comment by PietroLiuzzo** [comment]
@eu-genia please close if ok
