### ISSUE TITLE
New PRS IDs for king Darius and Aristotle

### ISSUE THREAD

**Issue by CarstenHoffmannMarburg** [SChAth/ScAthiop#2753]
@thea-m @eu-genia 

I want to update LIT6936TarWaAmidBeta and add the text on the Alexander story from the edition by Budge. I want to mark up some personal names, that play a role in this story and that have no ID, yet.

a) Aristotle አርስጣጣሊስ፡ (Q868)

b) Darius III Codomannus (Q102865), who has the name ዳርዮስ፡ ዘይልህቅ፡, but also ዳራ፡ in this text should not confused with Darius the Mede (Q603176), Darius I the Great (Q44387) and Darius II (Q202236). I found PRS3370Darius, but this record has no information and no attestations. I want to update PRS3370Darius and use it for Darius the Mede, who is known from AT book Daniel, and create three new IDs for the others to avoid future confusion.

**Comment by eu-genia** [comment]
For Aristotle why do you not want to use PRS2032Aristotl?
PRS3370Darius should be used for Darius the Great; I suggest you create IDs for other namesakes
