### ISSUE TITLE
alternative dates in handDesc

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#276]
Alternative dates given in handDesc are not well shown on the website, see for example p2 of BNFet82. 

````xml
  <date notBefore="1400" notAfter="1499" resp="PRS10747Zotenbe"/>
  <date notBefore="1375" notAfter="1450" resp="PRS9619Uhlig"/>
````

**Comment by PietroLiuzzo** [comment]
should be better now with a new line break for each date and the explicit attribution of the data
