### ISSUE TITLE
schwa

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#277]
According to our transcription rules for the sixth order we should use
ǝ (01DD - Latin small letter turned e) - which also has a capitalized pendant Ǝ (018E)
and not
ə (0259)
(Two different unicode symbols).
Some of the records use the wrong symbol. 
@DenisNosnitsin1970 @thea-m @MassimoVilla

**Comment by thea-m** [comment]
I searched through all records and corrected it, but this has to be kept in mind by us all and probably be checked again occasionally
@eu-genia @MassimoVilla @DenisNosnitsin1970  @sologebre
