### ISSUE TITLE
BNFet numbering

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#280]
It seems that unfortunately the BNF et numbers we use are not those universally accepted. We should switch the entry id and the other identifier. E.g. what we have as BNFet5 is actually BnF éthiopien 94 = Zotenberg 5. (the library number is primary).

**Comment by PietroLiuzzo** [comment]
@thea-m We can preserve all this identifiers in altIdentifier if needed

**Comment by PietroLiuzzo** [comment]
to be evaluated how much of this work can be processed with a script without risks. needs files renaming and id changes.

**Comment by thea-m** [comment]
I agree that we should use the universally accepted identifier, but it seems that in this case both are in use (for instance in the EAe). It is my feeling that the Zotenberg number is used more often, and it is also used on the BnF website, where the other shelfmark is found under “ancienne cote”:
http://archivesetmanuscrits.bnf.fr/ark:/12148/cc94953x
Please, what do you think, @abausi ?

**Comment by abausi** [comment]
Dear all,

there is no question on this, the answer is very clear, and I agree with 
Dorothea: we MUST use the catalogue number given by Zotenberg, that has 
been used for years as the official shelfmark for all manuscripts 
belonging to the fund catalogued by Zotenberg. ("EAe", as for many other 
aspects, is not a model in this.)

With best wishes,

A.B.

Il 23.01.2017 09:02, thea-m ha scritto:
