### ISSUE TITLE
colophon types?

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#284]
could we introduce a type to distinguish copied colophons?

**Comment by thea-m** [comment]
@MassimoVilla  and I discussed this already several times, and wanted to talk about it in a meating as well. 
We probably also still need to distinguish better between colophon, Subscription and ScribalNoteCompleting, as mentioned in a comment in #175

**Comment by PietroLiuzzo** [comment]
I have allowed @type in colophon values are at the moment not restricted and no indication as been given as how to use this data and where to visualize it.

**Comment by eu-genia** [comment]
this should go on our meeting agenda i think

**Comment by eu-genia** [comment]
the oxygen still highlights the colophon type as invalid in `<colophon xml:id="coloph1" type="Subscription">`

**Comment by PietroLiuzzo** [comment]
This is now fixed. Value of type will be printed instead of colophon when available
