### ISSUE TITLE
add incipit to edition of work

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#286]
Do we already have a way of adding the incipit to a work record (that is, without a note saying "this is the incipit"?)
(I used `<div type="textpart" xml:id="incipit">` once)
Maybe we could add a `subtype="incipit" `to `textpart`?

**Comment by PietroLiuzzo** [comment]
Can't already do that? @subtype should have suggestions not a strict list of values. Please try and let me know.

**Comment by thea-m** [comment]
<div type="textpart" subtype="incipit"/> is marked as an error (must be equal to book, chapter or stanza)
(see also #251)

**Comment by PietroLiuzzo** [comment]
this values have now been added and the values for @subtype are open.
