### ISSUE TITLE
searching for t2 etc.

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#289]
It would be very helpful if, when using the filter search for textual units, not only t1 would be prompted from the app and searches for any other titles would also lead to the right record
(I was searching for LIT1100Anapho with "anaphora of our lord", which produced an error)

**Comment by PietroLiuzzo** [comment]
I cannot reproduce this issue. if I digit in the GO to box Anapho this is the third hit and clicking on it leads to the record without any problem.

**Comment by PietroLiuzzo** [comment]
unfortunately this is a visualization issue related to browsers. this behaves as expected in all but visualizes in different ways the datalist element used in the html.
