### ISSUE TITLE
citation

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#290]
was in a mixed issue from @eu-genia 

 in the Citation format for the database entries the quotation marks should be single, a comma is missing before "in", and the editor should come before the main work title, i.e. 
XY, 'Article', in Alessandro Bausi, ed., Beta masaheft....

**Comment by PietroLiuzzo** [comment]
@eu-genia this should be now ok. please check and close if ok

**Comment by eu-genia** [comment]
is it possible to have the round quotation marks?
after the license information i believe to see two dots - can you check?
