### ISSUE TITLE
scopes writtenLines

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#291]
when the cataloguer says e.g. 28 to 40 lines
I write 
`writtenLines="28 40"`
but does this cover the whole range? will the manuscript pop up if i search for mss e.g. with 35 lines? 
what is the best way to encode?

**Comment by PietroLiuzzo** [comment]
there was no requirement to search with this information until now. it is correct to mark it up like this.

**Comment by PietroLiuzzo** [comment]
The Advanced Search offers now a slider to filter text searches by number of leaves and number of written lines. it will take any value within the range so giving 20-30 all mss which have one of the two values in writtenLines set to a value between 20 and 30 included. please test and tell me if this is the expected behavious

**Comment by eu-genia** [comment]
looks good. but if we go into codicological issues to search for - there are also columns, eventually margins, and always size(s) (possibly with scopes) and proportions (vertical/square/horizontal). all the things we code separately we do so in order to be able to search for them.

**Comment by PietroLiuzzo** [comment]
It is already possible to search also directly by XPath, http://betamasaheft.aai.uni-hamburg.de/xpath, this allows full query flexibility. IMHO too many inputs in list filtering and in search mask do not really help the user, but I am happy to add all those which are required off course. please provide me a full list of all the encoded things which you would like to be able to use to filter in the search beside those already in the form and those already mentioned here. Please, also consider that any such filter will automatically exclude those entries for which the given information is not provided.

**Comment by PietroLiuzzo** [comment]
closing issue as original and subsequent request has been fulfilled. continuation of list to occur in new issues.
