### ISSUE TITLE
bibl visualization

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#293]
for titles with more than one author the bibl references should appear as
2 authors --> Author1 and Author2 Year
3 and more --->Author1, Author2, and Author3 Year

**Comment by PietroLiuzzo** [comment]
example please? you mean in-text citations? in bibliography the app only prints what is returned from zotero with the HCLES style.

**Comment by eu-genia** [comment]
i mean in-text citations of the author-year type, see RIE193II (Nosnitsin and Munro-Hay)
btw the oxygen still highlights the bibl used in history as invalid

**Comment by PietroLiuzzo** [comment]
This is another issue...
