### ISSUE TITLE
See Also... section display update

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#295]
given a work id number show in a slider all ms msDesc which contain it and their supart. with javascript highlight in the same color the parts with the same id and link them with an arrow.
order manuscripts from left to right according to date

**Comment by PietroLiuzzo** [comment]
please see http://betamasaheft.aai.uni-hamburg.de/seealso/LIT1961Mashaf or use the comparison tool offered by list view and resources menu.

**Comment by PietroLiuzzo** [comment]
the arrow requires SVG lines/paths/markers to be further studied. usefull library is this 
https://gist.github.com/alojzije/11127839
although it needs changes to make lines with markers and does not well integrate with Slick carousel

**Comment by PietroLiuzzo** [comment]
please @eu-genia @MassimoVilla @DenisNosnitsin1970 @thea-m provide feedback for improvement of this functionality.

**Comment by thea-m** [comment]
It seems to work very nicely. 
For my personal taste it would be more useful if more than three manuscripts were displayed at the same time (no idea whether this is possible or not - what seems to take up place are the full manuscript names?) and/or there would be a faster way to scroll through the results than by clicking on the points below them.

There is also a certain redundancy between this comparison and the list provided in "This Work is mentioned in Manuscript records 34 times" below - maybe it would be possible to only list the manuscripts there in which the work record in question is not a msItem? (for the example of http://betamasaheft.aai.uni-hamburg.de/seealso/LIT2505Weddas that would leave BLadd16197)

**Comment by PietroLiuzzo** [comment]
part one sorted, part 2, @eu-genia @abausi @MassimoVilla @DenisNosnitsin1970 please let me know what you would like there

**Comment by thea-m** [comment]
I think that the "see also" page is extremely useful, but looks slightly crowded at the moment - would it be possible to list the entities sharing the same tag separately or smaller, or to expand the result list only when clicking on "The following 175 entities also share the Poetry tag"?
(I also think that this feature is much more interesting than one would maybe guess when seeing the name "See Also..." all at the end of the menu like an afterthought - could it be changed? or maybe this is just my impression)

**Comment by PietroLiuzzo** [comment]
- [ ] you  should be seeing the related items in boxes and scroll inside them to see the full list. please send me a screenshot if the behaviour you are seeing is different.
- [ ] I could provide this as a choice. nothing would be loaded but only the list of possible comparisons. on selecting Poetry you would get the list for that. ok?
- [ ] All can be changed, especially string text! let me know in which order you want the menu items and what names they should have, if on top, left, right, left, bottom of the page, etc.

**Comment by PietroLiuzzo** [comment]
Items related via one of the categories initially listed for the see also view are now in a selector pulling up cards on request.
