### ISSUE TITLE
idno EMML mss

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#296]
for filling up the mini mss records:
What is the correct `<idno> ` of EMML manuscripts?
`<idno>EMML Pr. No. 7630</idno>`?
`<idno>EMML No. 7630</idno>`?
<idno>EMML no. 7630</idno>?

**Comment by eu-genia** [comment]
yes, what should be shown is EMML no. 7630 (never EMML 7630).
with the new filters Pietro introduced the full content of idno tag is not shown (we might have to rethink the temporary solution Pietro suggested as it does not always work.)
for the EMML mss there will be another problem for showing the title - the title actually should be EMML no. 7630, and not, e.g. Addis Ababa, Sellasse, EMML no. 7630 (actually it can be EMML no. 7630 = Addis Ababa, Sellasse, C-IV-300 [I am inventing numbers now but you get what I mean, the local numbers are the ARCCH/NALE ones, the EMML are microfilms, and we have a repository for the ms which is not the same as the repository for the mf, tricky!)

**Comment by PietroLiuzzo** [comment]
cant we create these records as manuscript records and not microfilm records and assign them the correct id. I think it would overall improve consistency.

**Comment by eu-genia** [comment]
this is not always easily possible, and then everyone around the world refers to them with the microfilm reference.

**Comment by PietroLiuzzo** [comment]
we would still have that id and we can certainly use it

**Comment by eu-genia** [comment]
for the moment we had agreed that we do not create new descriptions for EMML mss but get the ones they have when they have them. as long as we have not imported we only make stubs. so for the moment i do not think we can dedicate any effort into structuring further their descriptions. and even after we have imported we will still not get the structure we'd need. this is a task never planned, i don't think we can work on EMML that much. We should stay with the mf reference for now. maybe for the view function it can be coded something that if EMML is contained in the idno show complete idno as title.

**Comment by PietroLiuzzo** [comment]
Please provide example for the desired EMML title output.
we can add as many exceptions as we want, but these do not help consistency in the presentation of data in my opinion.

**Comment by eu-genia** [comment]
EMML no. 1234 would be sufficient for the title
the EMML mss now created as XML stubs were those linked from LIT2317Senodo but there they were marked as "external" - we might need to get a clear idea how external references are to be treated
