### ISSUE TITLE
wāzemā collection

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#298]
For discussing the textpart/work status of a collection of wāzemā hymns, as in 
BL Dillmann  Nr. XXIX (bm:Dillmann1847BM p. 34, no shelfmark)
or Bodl Aeth. f. 8 (bm:Ullendorff1951Catalogue p. 11): should the single hymns have independent IDs or be textparts of a "Collection of wāzemā hymns" work?
@abausi @DenisNosnitsin1970 @eu-genia @MassimoVilla

**Comment by abausi** [comment]
The situation may be a bit different from the case we discussed, but I 
would stay with single IDs for the single hymns.

Il 06.02.2017 12:32, thea-m ha scritto:

**Comment by thea-m** [comment]
thank you, added to 
https://github.com/SChAth/Works/wiki/Notes-on-Works-encoding

**Comment by MassimoVilla** [comment]
I was subsequently wondering whether the single Dǝggʷā hymns, contained as a collection e.g. in BLadd16195 and currently listed as textparts of LIT3178Deggwa, should be treated accordingly, that is upgraded to the status of work records.

**Comment by abausi** [comment]
I think that all the similar cases of hymnodic collections should be 
treated in the same way.

Il 06.02.2017 14:44, MassimoVilla ha scritto:

**Comment by MassimoVilla** [comment]
thank you.
