### ISSUE TITLE
hypothes.is annotations

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#299]
You will have noticed by now in the app homepage the rss feed which shows some test comments.

This is collecting annotations from Hypothes.is which contain the tag "BetMas". every time someone somewhere writes a hypothes.is public annotation with this tag, it will show up there.

I think this will be useful to gather links to useful websites and pdfs in the web which do not directly or immediately make it into the contents. needless to say it could be the commenting function we support for the app embedding it or simply pointing people to it for this kind of feature.

You can create an account on hypothes.is and test with some annotations, it is indeed a very useful and powerful tool for many other things.

**Comment by eu-genia** [comment]
i posted a reply to a comment you left... but am not sure this is what it is for

**Comment by PietroLiuzzo** [comment]
sure enough it is
