### ISSUE TITLE
advanced search filters and SORT

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#305]
- is it possible to sort everything alphabetically?
- for the persNames with forename surname please show surname, forename and sort by surname
- if the search is too heavy - would it possibly make sense to have separate search windows for manuscripts, texts, persons, places and institutions? or does not help much?
- as mentioned elsewhere, ethnic names are often also place names by extension so those marked as such should be searchable with places

**Comment by PietroLiuzzo** [comment]
Yes, but the sorting is performed on computed values I don't have an immediate solution but there must be one easy enough.
The current advanced search form already gives you the option to search only one collection. This will result in a much shorter list. 
in the Advanced search there is no filter for ethnic records at the moment, I can add one that will narrow down to the two collections.

**Comment by PietroLiuzzo** [comment]
sorting with tinysort works. needs to find a good method to apply it at the right moment. restructure advance search to load only requested modules with a multiselect. 
will offer basic filters (keywords, types, indexes, etc.) then this option, on submit the requested filters ONLY will be loaded.
