### ISSUE TITLE
double date display

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#306]
In person records, the dates of birth and death are displayed twice, if the date is provided as an attribute value and is also written in the content of the element, such as  
`<death when="1632" evidence="internal">1632</death>`
in http://betamasaheft.aai.uni-hamburg.de/persons/PRS9038Susenyos

**Comment by PietroLiuzzo** [comment]
Thanks for reopening this issue, I had been looking for an example but could not find it and thus closed the previous issue about it. The point here is that death, birth, floruit, etc. can take content, thus I first print the value of the attributes, then apply templates to the content. in this case there is content, thus both things happen, but I cannot safely omit processing the content as it might be different from just the date (see floruit in the same record). I would thus suggest that the mark up needs to be fixed to remove the content. @sologebre could you please change <death when="1632" evidence="internal">1632</death> to <death when="1632" evidence="internal"/>? thanks!

**Comment by PietroLiuzzo** [comment]
[at this link a list of files which should contain this phenomenon](http://betamasaheft.aai.uni-hamburg.de/xpath?xpath=collection%28%27%2Fdb%2Fapps%2FBetMas%2Fdata%2Fpersons%2F%27%29%2F%2F%28t%3Adeath+%7C+t%3Abirth+%7C+t%3Afloruit%29%5Btext%28%29+%3D+%40when%5D)

**Comment by PietroLiuzzo** [comment]
@sologebre please close issue if you are done with this

**Comment by sologebre** [comment]
It is done
