### ISSUE TITLE
work status Wəddāse Māryām, Wəddāse ʾAmlāk, ʾArgānona Māryām

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#308]
Do the textparts (for the days of the week) of all of these works remain textparts, or should they be assigned individual IDs? 
(the sections of Wəddāse ʾAmlāk are attributed to different authors (currently expressed as relations within the textparts), but don't seem to occur independently?)
@abausi @DenisNosnitsin1970  @eu-genia @MassimoVilla

**Comment by abausi** [comment]
I do not know if we can mulitply enormously the numer of IDs. I would be 
in favour of a limitation, at a certain point.

Il 08.02.2017 11:42, thea-m ha scritto:

**Comment by PietroLiuzzo** [comment]
IMHO I do not think authorship is enough to make it into a full work record and the way the authorship is attributed is clear for these textual unit. let me know if the visualization is wrong. I also remember discussing in the past texts with the day of the week. if the days of the week are always there (no matter if in different order which will be comparable here http://betamasaheft.aai.uni-hamburg.de/compare?target-work=LIT2505Weddas) I do not personally think they should get an id.

**Comment by abausi** [comment]
It seems to me that there is a consensus that they should not receive an ID.

Il 09.02.2017 08:03, Pietro Liuzzo ha scritto:

**Comment by PietroLiuzzo** [comment]
updated https://github.com/SChAth/Works/wiki/Notes-on-Works-encoding
