### ISSUE TITLE
samuel 1 and 2 

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#310]
new work records?

**Comment by thea-m** [comment]
but they exist: LIT2697Sam and LIT2698Sam
It is only a problem of terminology, as far as I'm aware

**Comment by eu-genia** [comment]
sometimes the spreadsheet does help...

see e.g. BLorient483

`<msItem xml:id="ms_i2">
                        <locus from="133r" to="194v"/>
<title type="Complete" ref="LIT1719Bookso">Books of Samuel and Books of Kings</title>                        
                        
                        <msItem xml:id="ms_i2.1">
                           <locus from="133r" to="148v"/>
                           <title type="Complete" ref="LIT2697Sam"/>
                           <quote xml:lang="gez">ትፈጸመ ፡ ነገሥት ፡ ቀደማዊ ፡ ዘወጠኖ ፡ ስሙኤል ፡ ወፈጸምዎ ፡ ናታን ፡ ወጋድ ፡፡ ስብሐት ፡ ለእግዚአብሔር ፡ ሣህሉ ፡ ለእግዚአበሔር ፡ የበሉ ፡ ምስለ ፡ ንጉሥነ ፡ ደዊት ፡ ለዓለመ ፡ ዓለም ፡ አሜን ።</quote>
                        </msItem>
                        
                        <msItem xml:id="ms_i2.2">
                           <locus from="149r" to="161r"/>
                           <title type="Complete" ref="LIT2698Sam"/>
                           <quote xml:lang="gez">ትፈጸመ ፡ ነገሥት ፡ ደግማዊ ፡ ዘጸሐፍዎ ፡ ና ታን ፡ ወጋድ ፡፡ ሣህሉ ፡ ለእግዚአብሔር ፡ የሀ ሉ ፡ ምስለ ፡ ነፍስ ፡ ንጉሥነ ፡ ደዊት ፡ ለዓለ መ ፡ ዓለም ፡ አሜን ።</quote>
                           <note/>
                        </msItem>
                        
                        <msItem xml:id="ms_i2.3">
                           <locus from="162v" to="178v"/>
                           <title type="Complete" ref="LIT2699Kings"/>
                           <note/>
                        </msItem>
                        
                        <msItem xml:id="ms_i2.4">
                           <locus from="179r" to="194v"/>
                           <title type="Complete" ref="LIT2700Kings"/>
                           <note/>
                        </msItem>
                        
                     </msItem>`

**Comment by PietroLiuzzo** [comment]
Thanks! 

In my opinion this is exactly where the spreadsheet deceives us and confuses our work: what might have happened here is that this record for LIT1719Bookso was created before the bracketed information in the spreadsheet (1, 2 Samuel and 1, 2 Kings) was entered there **and NOT in the data.** or it might have been missed in the initial transformation from the spreadsheet (although this would be surprising given the entire content of cells has been slavishly copied over...). If you search the app in works you cannot get to this information (1, 2 Samuel and 1, 2 Kings) because is not there. Also the results returned are confusing because of the data encoding. I try to explain better below.

With Martin we went on the clavis view, we entered kings in the go to function and got to know there is a Books of kings, a kings 3 and a kings 4 and  wondered. Then we looked for Samuel, we found 1. Lets leave aside at the moment the fact that there are abbreviations Sam. 1 Sam 2 Sam in Dillmann (if this is what they point to...) while the abbreviation list reports 1 Reg 2 Reg 3 Reg 4 Reg only. 

Indeed the simple search for Book of Kings returns the four record mentioned instead, but I believe the first access point to get to this data should be the clavis list view or a simple search. We do not really want a user to find the information about a work in a mss record and browse from there if he is searching for a work and not a manuscript.

LIT1719Bookso should report somewhere this information and the relations to the parts. Each of the four books should at least record the alternative titles in a consistent way.

If my understanding of this and #309 is right 

LIT1719Bookso
     LIT1220BookofSamuel
         LIT2697Sam = sam 1 = kings 1
         LIT2698Sam = sam 2 = kings 2
     LIT2699Kings = kings 1 = kings 3
     LIT2700Kings = kings 2 = kings 4. 

Instead, we have in the two records for kings a t1 Kings 3 and 4. I would expect one of the two naming system to be consistently prioritized instead, so if we use samuel in the other two here I would expect kings 1 and 2. 

Given these small changes in the data then one should get the desired behaviour from the app list view "Go to" function, entering kings will be lead to BookS of Kings, kings 1 and kings 2 (not 3 and 4) and find in the first record the link to the four records. Entering Samuel, should instead return the general Samuel record LIT1220BookofSamuel (is it?) which will contain links to the first two records.

BUT

The rules for the main title prioritise at the moment the transcription of the t1 in fidel. Thus the standard titles will be also for kings Nagaśt śālǝsāwi not king 3.

This means in the Go To function I will get only the general records if they will have a english main title for a english entry. which is fine if in LIT1719Bookso I find the information I need about the components.

I would also suggest when you will work on these work records to use a bible keyword for biblical texts because at the moment they cannot be filtered in any way. In this way I will go to the clavis willing to find my samuel book, filter down to bible works and find all of the above in the list view directly.

If the desired user experience is different do let me know!

**Comment by eu-genia** [comment]
pls check if it works now for the Kgs the way it should

**Comment by PietroLiuzzo** [comment]
I certainly find useful the bible tag filtering. on the title instead I don't think is what one expects, but this is not my decision. I would encode them something like this but with the modification described below

```xml
<title xml:id="t1" xml:lang="en">(Ethiopic) Book of Kings 1</title>
<title xml:id="t2" xml:lang="gez">ነገሥት፡ ቀዳማዊ፡</title>
<title corresp="#t2" xml:lang="gez" type="normalized">Nagaśt qadāmāwi</title>
<title corresp="#t2" xml:lang="en">First Kings</title>
<title xml:id="t3" xml:lang="en">1 Sam (Septuagint)</title>
<title xml:id="t4" xml:lang="en">Book of Samuel 1</title>
```
and consequently keep for the denomination of the same series in the same position. The rules for the title of a record prioritize as required the gez transcription of t1, I would not alter the encoding (in this case promoting one english title to t1) to get a different title printed unless is really necessary as for the discussed case of testamentum domini. below I reproduce the current rule which can be further specified of course to meet the needs.

```xml
case "work"  return       
                     if ($resource//t:titleStmt/t:title[@corresp='#t1'  and @xml:lang='gez']) 
            then $resource//t:titleStmt/t:title[@corresp='#t1'  and @xml:lang='gez']/text() 
           else if ($resource//t:titleStmt/t:title[@corresp='#t1'  and @xml:lang='en']) 
            then $resource//t:titleStmt/t:title[@corresp='#t1'  and @xml:lang='en']/text() 
            else if ($resource//t:titleStmt/t:title[@xml:id]) 
            then $resource//t:titleStmt/t:title[@xml:id='t1']/text() 
            else $resource//t:titleStmt/t:title[position()= 1]/text()
``` 

one will only find the main record in the go to, but so it should be according to the current architecture and with the keyword filtering together with the relations it seams to me good and nice.

**Comment by eu-genia** [comment]
as for the title - this is the same case as the "Testamentum domini" though. since we do not have the type="main" for the title version we want to show we have to use t1 for the English title as this is the one we want to be printed, not "Nagaśt qadāmāwi". we have just discussed with Dorothea that we always need the universal English title be printed for biblical works and similar.

**Comment by PietroLiuzzo** [comment]
as said we can have a @type it is just a decision of consistency in what we want to display. we want to provide all the available and apply consistently rules or do this but anyway apply on a case by case basis a decision with the @type attribute? adding a rule above to prioritize the one with @type is easy. but is what actually we want?

**Comment by PietroLiuzzo** [comment]
it could be a decision based on keywords. if it is Bible then take xml:lang en of t1...

**Comment by PietroLiuzzo** [comment]
I revised the testamentum domini issue. eventually what we said there is the same, simply we use t1 as type main at the end of the day... thus the problem remains inaltered... because eventually t1 does not carry semantic value. if this t1 solution is actually ok for you I would simply not put there the = and the alternative as in the example above and keep with that. sorry for the unnecessary confusion.

**Comment by eu-genia** [comment]
I accepted the t1 solution then and acted upon it with the Kings - but as before I am still in strong favour of having an additional @type as sometimes also for t2-t3-t4 I want to be able to define which is printed when I point to them. as with the TD I want to be able to point to either TD Ethiopic or TD Syriac and have the title printed as I choose.

We cannot simply use "Bible" as a universal rule, there are other texts that have "universal" circulation and titles and should be primarily referred to under their English (or Latin as with TD or whichever is main) label.

**Comment by PietroLiuzzo** [comment]
on the bible keyword, we can have as many rules as we want, as for the inscriptions, EMML, etc. they just need to be clarified with one example.

**Comment by PietroLiuzzo** [comment]
the rules are updated. if you use in a record a type='main' in the titles of a work record, this will be chosen. the other rules apply as before, so there is no need to change things. 

also the rules for the pointers have been updated. 

if you enter in a pointer LIT2461Testam#t4syriac this will print the title with type main and corresp #t4syriac or if that is not there simply the title with that id.

**Comment by PietroLiuzzo** [comment]
let say we have

t1 
corresp=t1 main
t2syr
corresp=t2syr main
t3
t4

on a generic call, taking the title with main will fail. can I take type=main and corresp t1 ? 

modifing for the example the case of testamentum domini:

```xml
<title xml:lang="lat" corresp="#t1eth" type="main">Testamentum Domini</title>
<title xml:id="t1eth" xml:lang="gez">ኪዳን፡ ዘእግዚእነ፡ ኢየሱስ፡ ክርስቶስ፡</title>
<title xml:lang="en" corresp="#t1eth">Testament of Our Lord Jesus Christ</title>
<title xml:lang="gez" corresp="#t1eth" type="normalized">Kidān zaʾǝgziʾǝna Iyasus Krǝstos</title>
<title xml:lang="ar" xml:id="t3arabic">Testamentum Domini (Arabic)</title>
<title xml:lang="syr" xml:id="t4syriac">Testamentum Domini (Syriac)</title>
<title xml:lang="syr" corresp="#t4syriac" type="main">the title in syriac</title>
<title xml:lang="gr" xml:id="t5greek">Testamentum Domini (Greek)</title> 
```

calling the record (LIT2461Testam):
"normally" Kidān zaʾǝgziʾǝna Iyasus Krǝstos would be taken.

in this case, because this is not the desired title, type main is added and Testamentum domini is printed instead.

calling the title with LIT2461Testam#t4syriac will behave as described thus in this case print "th e title in syriac". if no type=main is added there, than "Testamentum Domini (Syriac)" is printed

is it ok?

**Comment by eu-genia** [comment]
looks good
