### ISSUE TITLE
add keywords to work records

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#313]
We should remember to add keywords to new work records, and also to any existing work record we're working with

**Comment by thea-m** [comment]
can we add a keyword for Beta ʾƎsrāʾel literature? (since we have ChristianLiterature and IslamicLiterature)
@PietroLiuzzo

**Comment by eu-genia** [comment]
and also a general one AmharicLiterature

**Comment by eu-genia** [comment]
to add
AmharicLiterature
BetaEsraelLiterature
TigrinyaLiterature
Fiction

possibly also
Translation
could be nice to highlight translated things quickly.

**Comment by PietroLiuzzo** [comment]
I can add these to the schema, no problem, but please do not forget to create records and to update taxonomy.xml with these values.

**Comment by PietroLiuzzo** [comment]
done, close issue once the files have been created/updated, please

**Comment by eu-genia** [comment]
done
