### ISSUE TITLE
work records/spreadsheet harmonisation

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#314]
to make sure that all information added at various stages to the spreadsheet is also present in the work records, we have to go systematically through the spreadsheet, look for added information and check/modify the work records
Works 1001-2000: me
Works 2001-3000: @eu-genia 
Works 3001-4000: @MassimoVilla 
Works 4001-: whoever is finished first, please write a comment here

**Comment by thea-m** [comment]
we can use this as an opportunity to add keywords to the records we're opening ;)

**Comment by eu-genia** [comment]
i am also using the opportunity to update the titles (esp transcription) throughout

**Comment by eu-genia** [comment]
sometimes the records are linked to those in another collection - in this case feel free to update all together marking the entire line yellow in the spreadsheet

**Comment by thea-m** [comment]
I added all the extra spreadsheet information to 1001-2000 (though I didn't add the keywords and updated the titles of all the works yet (mainly those I was opening anyway or where I knew that they are often referenced) - I wanted to get finished with the spreadsheet for once and all first), so I'll start with 4001- now

**Comment by thea-m** [comment]
added all spreadsheet information 4001-4276
There are no records for the last two works added to the spreadsheet, LIT4277GoldenG and LIT4278HistAeth. Whoever added them, could you please create new records through the app and delete them in the spreadsheet?
@eu-genia @MassimoVilla @DenisNosnitsin1970 @sologebre

**Comment by thea-m** [comment]
I believe that this issue can be closed, as its aim was to ensure that all relevant information contained in the spreadsheet is present in the xml records, which I believe is the case. 
We can and should now stop using the spreadsheet as reference.
