### ISSUE TITLE
add support for dc:creator beside saws:isAttributed author

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#315]
support in list view, in title handling, in search, in item view and in references functions

**Comment by PietroLiuzzo** [comment]
also persons analytic apps need update

**Comment by eu-genia** [comment]
we need rather isCreatedBy or isWrittenBy as the relation goes with the work not the person
or switch active/passive

**Comment by PietroLiuzzo** [comment]
***dcterms:creator*** is now supported.

**Comment by eu-genia** [comment]
since we place the relation under the work - do i twist active-passive?
i.e. LIT1234ABC has as author PRS5678XYZ
under LIT1234ABC
i have then
`<relation name="dcterms:creator" active="PRS5678XYZ" passive="LIT1234ABC"></relation>
`
correct?

**Comment by PietroLiuzzo** [comment]
sure

**Comment by PietroLiuzzo** [comment]
wait a sec, no, this is intended as the work has a person as creator

**Comment by PietroLiuzzo** [comment]
no twisting needed.

**Comment by PietroLiuzzo** [comment]
http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#creator

**Comment by eu-genia** [comment]
seems to me from the description that creator is the person, i.e. must be the active part in the relation. active is the creator passive is the work

**Comment by PietroLiuzzo** [comment]
this is intended in the description of a book for example, i.e. the resource.
See also this example from dublin core wiki:
ex:myBook dcterms:creator _shakespearesName
in our case
LIT1234ABC dcterms:creator PRS5678XYZ
I understand this exactely as our zotero metadata where we assign dc:creator to our page (active) with the name of the editors (passive). the names of the attributes in TEI and the property names do not help, I agree!

**Comment by eu-genia** [comment]
in the dublin core wiki the example has a different syntax, it is clear that the creator is shakespeare.
with our syntax my perception is different.
we distinguish between the relations like hasPart and isPart (ACTIVE isPART of PASSIVE ACTIVE hasPart of PASSIVE) so for me instinctively (ACTIVE creator of PASSIVE) or then (ACTIVE isCreatedBy PASSIVE). 
but if you say the meaning of active/passive means nothing...

**Comment by PietroLiuzzo** [comment]
I think is just that a label such as "creator" can be instinctively interpreted as "has creator" or "is creator". trying not to use instinct, in the first case, which is that of this dcterm, where the subject is the work, active (=SUBJECT) is the work and it has a creator passive (=OBJECT). 
We are using a named relation with a @active and a @passive attributes as if this was a triple with a subject, a verb and an object. in your translation, dcterms:creator means Is Created By thus a Work (active/subject) is created by a person (passive/agent). Here we have no inverse property, but that is fine, we are using this for certain attributions, is just like the name of a field in a db.

**Comment by eu-genia** [comment]
ok :) got it

**Comment by eu-genia** [comment]
sorry one last thing it is still underlined red in my editor

**Comment by PietroLiuzzo** [comment]
it might be just caching, try and validate to your local copy of the downloaded and updated schema repo

**Comment by thea-m** [comment]
could you add the correct use to the guidelines?
