### ISSUE TITLE
transcribed incipit in work records

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#316]
is there a place in work records to add a transcribed textpart?
(in this case, the incipit of anaphoras, were a search for the incipit should lead to the correct work record)
something like this?

```xml
 <div type="edition">
            <div type="textpart" subtype="incipit" xml:lang="gez" xml:id="Incipit">
               <ab>
                  ነአኵተከ፡ እግዚኦ፡ [በፍቁር፡ ወልድከ፡ እግዚእነ፡ ኢየሱስ፡] ዘበደኃሪ፡ መዋዕል፡ 
               </ab>
            </div>
            <div type="textpart" subtype="incipit" xml:lang="gez" corresp="#Incipit">
               <ab>
                  Naʾakkʷǝtaka ʾǝgziʾo [ba-fǝqur waldǝka ʾǝgziʾǝna ʾIyasus] za-ba-daḫāri mawāʿǝl
               </ab>
            </div>
         </div>
```

**Comment by thea-m** [comment]
Same question for translations as well, see IVefiopsk5 #Stichometry

**Comment by PietroLiuzzo** [comment]
div[@type='translation'] should hold the translation, with minimal editorial markup. I would really avoid entering transcriptions all together. The requirement is here to search with transcription and find fidel? [here is the requirement](SRC12). it is not possible currently.
