### ISSUE TITLE
more on textparts - Gospels

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#317]
We used to have IDs for various Gospel subparts (introduction - tituli - main text). They have been used but then reduced to textparts within the main Gospel entry. While it is correct that the intro and titles never appear independently and are textparts, the main text does circulate also without the intro and titles and thus does need its own ID back.
(i.e. there should be one ID for each Gospel with the text parts, and additional IDs for the main Gospel texts).
Should preferably also be restored in the mss records where this has been corrected.

**Comment by thea-m** [comment]
So we will have:
- LIT1560Gospel for the four Gospels
- LIT2709Matthew etc. for the text of each single Gospel without tituli and introduction (currently deleted but can be re-created)
- LIT1558Matthew etc. for the text of each single Gospel including tituli and introduction as textparts
- no individual records for tituli and introductions 

Is this correct?

**Comment by eu-genia** [comment]
yes perfect

**Comment by thea-m** [comment]
added to https://github.com/SChAth/Works/wiki/Notes-on-Works-encoding

**Comment by MassimoVilla** [comment]
Work IDs for the gospels without tituli and introduction have been re-created: LIT2709Matthew (Bəsrāta Mātewos), LIT2711Mark (Bəsrāta Mārqos), LIT2713Luke (Bəsrāta Luqās), and LIT2715John (Bəsrāta Yoḥannəs);
Work IDs for gospels with tituli and introduction are, as usual, LIT1558Matthew, LIT1882MarkGo, LIT1812GospelLuke, and LIT1693John.

Guidelines have been updated, MSS from BAV and British Library (BLadd) corrected.

**Comment by eu-genia** [comment]
there is something wrong at least in some of the records
in LIT1693John I found

```
<div type="textpart" subtype="chapter" xml:lang="gez" xml:id="LIT2715John">
               <label>Bǝsrāta Yoḥannǝs</label>
            </div>
```

this is not correct as you are creating a new derived ID for the part of the form "`LIT1693John#LIT2715John`" and not pointing to the existing record.

I have corrected this now to `corresp="LIT2715John"`, please check all the other similarly treated records

**Comment by thea-m** [comment]
all corrected
