### ISSUE TITLE
authorship in work records

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#318]
As we decided at a past meeting and wrote in the work guidelines, authorship should be expressed as a relation in the concerned work record (not as a relation in the author's record and not using the `<author>` element in the work record)
(There seem to be some inconsistencies in our records)
@MassimoVilla @eu-genia @DenisNosnitsin1970 @sologebre

**Comment by eu-genia** [comment]
yes
Pietro shall be creating an additional relation of dc: type for works with sure authorship (esp valid for recent/Amharic texts) so that we can have two possibilities, for attributions, and for definite authorships. in case of doubt always go for isAttributed relation.

**Comment by PietroLiuzzo** [comment]
***dcterms:creator*** is now supported
