### ISSUE TITLE
Amharic titles

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#319]
There seems to be a small problem with the display of Amharic titles on the app. If I see it correctly, what is always printed is 1) the English translation of t1 or 2) the fidal version of t1 (an never the normalized t1, as in all other works)

for example, LIT2016Mestir or LIT2023Moras)

**Comment by eu-genia** [comment]
yes i noticed that too i think lang="am" must be treated as a rule in the same way as lang="gez", and it is not for the moment.
moreover i think wherever there is a normalized title it always has priority (also for ar, syr, and whichever other language)

**Comment by PietroLiuzzo** [comment]
Please check if the behaviour is now as expected.

**Comment by thea-m** [comment]
looks good now
