### ISSUE TITLE
alternative dates

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#320]
From discussion with @eu-genia 
It would be preferable to describe alternative datings of hands verbally and by adding a bibliographic reference, similar to this: 

RIE193II 
```xml
<origDate notBefore="0600" notAfter="1300">between the <date>7th and the 12th cent. A.D.</date>
                        (dating according to <bibl><ptr target="bm:NosnitsinMunro2005Danel"/></bibl>)</origDate>
```

However, in the following, `<bibl>` is marked as a mistake and the dates in `notBefore="1400" notAfter="1499"` are not printed on the website:

```xml
 <handNote xml:id="h2" script="Ethiopic"> <!--to be updated-->
                <date notBefore="1400" notAfter="1499">Date according to
                  <bibl>
                    <ptr target="bm:Zotenberg1877Catalogue"/>
                    <citedRange unit="page">87b</citedRange>
                  </bibl>.</date>
                <date notBefore="1375" notAfter="1450">Date according to
                  <bibl><ptr target="bm:Uhlig1988Palaographie"/><citedRange unit="page">254-255</citedRange></bibl>.</date>
              </handNote> 
```

(I could of course just repeat the date inside the element, but this doesn't seem ideal)
Or it would be possible to leave `<date>` without any further specification and add the description and bibliography in a `<desc>` or `<note>`

(This case has previously been encoded like this, which is not very precise and looks also strange on the app:

```xml
  <handNote xml:id="h1" script="Ethiopic"> 
                        <date notBefore="1600" notAfter="1632" resp="PRS10747Zotenbe"/>
                        <date notBefore="1550" notAfter="1632" resp="PRS9619Uhlig"/>
                     <listBibl type="secondary">
                           <bibl>
                              <ptr target="bm:Uhlig1988Palaographie"/>
                              <citedRange unit="page">512-513</citedRange>
                           </bibl>
                        </listBibl>

```
)

**Comment by PietroLiuzzo** [comment]
Please do not modify encoding on the basis of the result you want to see.
If the encoding is not sufficient for the information, it is ok to change it but the visualization should remain a separate issue. please provide an example of how this information should be visualized.

**Comment by PietroLiuzzo** [comment]
Please also provide reference to the files of the examples.

**Comment by PietroLiuzzo** [comment]
both encoding are ok. you can now see the date contained in the attributes before the text contained in the date element. 

1400-1499 Date according to Zotenberg 1877, page 87b.
1375-1450 Date according to Uhlig 1988, page 254-255.

This applies everywhere there is a date element (not origDate, which is handled differently and has a different function. 

Using @resp is still possible and will print according to followed by the name of the person according to the naming rules discussed. I assume one could need any of the two and either is fine. @resp takes any of the editors initials as well.

**Comment by thea-m** [comment]
Nicely shown on the app now, but still marked as an error in the record (BNFet82)

**Comment by PietroLiuzzo** [comment]
bibl is now allowed in date by the schema
