### ISSUE TITLE
advanced search filters

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#325]
to collect here the filters we need in advanced search.

Manuscripts
- [x] height width thickness
- [x] proportions
- [x] owner
- [x] parchmentMaker
- [x] binder

Persons
- [x] all possible roles

Works
- [x] a question: we do not mark author as `<author>` but as a relation of varying types (attributedTo most frequent but now also dc:creator (or if possible createdBy) for securely authored works) - are these the names used for the filter?

**Comment by PietroLiuzzo** [comment]
the names for work filter are at the moment only thos in attributedTo, as I did not yet get to work on #318

**Comment by PietroLiuzzo** [comment]
and #315

**Comment by PietroLiuzzo** [comment]
minimize variable content in list and search view using $item/text() when possible

**Comment by PietroLiuzzo** [comment]
proportions is not an indexed value.

**Comment by PietroLiuzzo** [comment]
all the values are now in the advanced search. the "all possible roles" for persons has been interpreted as a look up function which needs to retrive all persons which are mentioned somewhere as e.g. scribe. the list is thus a static reproduction of the allowed values in the schema and the results are a list of names with a list of items where the given person occurs with the given role.

**Comment by PietroLiuzzo** [comment]
please test and close if ok

**Comment by eu-genia** [comment]
for manuscripts the things mentioned in issue 291 (esp. columns) should be considered
dimensions now look funny and offer no range (?)
number of leafs (-->leaves) - the range shows is very close to the list so once selected I cannot click on e.g. dimensions any more
scribes (and other person types) should preferably be listed as "Last name, First name", alphabetically sorted

**Comment by PietroLiuzzo** [comment]
#291

**Comment by PietroLiuzzo** [comment]
results of persname filtering are sorted on the basis of the standard rules given. Thus when there are surname and forename in the person record, those are displayed as Hiob Ludolf first name and last name. why should they be different in the search results?

**Comment by eu-genia** [comment]
because in lists/lexica/encyclopaedias etc persons are sorted under Last name, first name

**Comment by PietroLiuzzo** [comment]
I fail to see what the criteria should be here. generally we have a rule that says if there are forename and surname, print forename and surname. in the results we print the same title of the item that the user will find in the record, I think it would be definitely an overkill to change the order here only... unless we revert to the southern italian way all over...

**Comment by eu-genia** [comment]
the reason is alphabetic sorting - the first letter is the sorting key

**Comment by PietroLiuzzo** [comment]
I understand now, you want them sorted by surname, not by forename, when possible. this can be done regardless of the label used. I can do that without changing the match to last name, first name

**Comment by PietroLiuzzo** [comment]
try selecting in the more specific filters author (it will look only for persName[@role="author"]) to check if the alphabetic order is ok. e.g. Vittori is second last, but the title is Mariano Vittori.
