### ISSUE TITLE
text erased and overwritten

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#328]
According to our current guidelines, text deleted/erased and rewritten should be indicated by means of subst/del[@rend 'erasure'] and add[@place 'overstrike'] (e.g., `<subst><del rend="erasure">ለሰኔ፡</del><add place="overstrike">ለግንቦት፡</add></subst>`).
Actually, 'overstrike' is tolerated but it is not among the values which are suggested for `add`. We do have 'inspace' (= "in a predefined space, for example left by an earlier scribe"), but it does not seem to properly fit what we need.
The value 'overstrike' needs to be included among the values and a short definition provided.

**Comment by PietroLiuzzo** [comment]
fixed and in schema, please sync schema
