### ISSUE TITLE
visualising relations

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#330]
I believe some types of relations should be visualized in the main window. 
- [x] E.g. for works, the persons in the "attributedTo" or similar relations should be shown as Authors in the main preview.
- [x] Also for works that have "hasPart", "isPart", "formsPart", etc. relations it would be best to show them as list in the main window. E.g. as "The following parts are also independent works: ...." "The work is included in the following works: ..."
It is essential that the users see this information immediately without having to go to related view or clicking anything extra.

**Comment by eu-genia** [comment]
possibly also the titles of the textparts (if they have id-s and labels) should be visualized as a list right in the main window.

**Comment by PietroLiuzzo** [comment]
More descriptions for different relations can be added without any problem.
the default is "The following works have a relation {RELATION NAME} with this work"

**Comment by PietroLiuzzo** [comment]
the related works button is now gone and the information is listed directly under the title.
