### ISSUE TITLE
visualisation corresp="#..." in handNote

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#332]
I have often added a `corresp="#a1"` or similar in `handNote`, if it is known which particular part of the manuscript is written in this hand, and this is also stated similarly in the guidelines.
for example BNFet103

```xml
  <handNote xml:id="h2" script="Ethiopic" corresp="#a1"> 
   <date notBefore="1600" notAfter="1632"/>
    </handNote>
              
<handNote xml:id="h3" script="Ethiopic" corresp="#a2"> 
 <date notBefore="1600" notAfter="1632"/>
  </handNote>
```

On the app, this is visualised by linking the name of the hand (i.e. Hand 1; Hand 2) to the addition in question. 

I think that this would not make the relation obvious to users, especially as of course the part of website one would jump to usually contains more than this one item (in the case of BNFet103, it looks exactly the same for hand 1- hand3, and one would notice what was meant only by reading the url).
Can this relation be visualised in another way, or should it be encoded differently? Maybe it is negligence of my part not to have stated this information differently or verbally.

**Comment by thea-m** [comment]
(I have also used, for instance in BNFet41
```xml
<handNote xml:id="h2" script="Ethiopic">
                <ref target="#a2"/>
```
but this doesn't seem ideal either)

**Comment by PietroLiuzzo** [comment]
Both are fine. I can show the links to the corresponding parts beside the hand title ok?

**Comment by PietroLiuzzo** [comment]
Of course using one method allows computation. Those with ref will not be found uf one looks for hands who have written additions by querying the content of corresp

**Comment by thea-m** [comment]
Adding links sounds good, and I'm going to change the records using ref

**Comment by PietroLiuzzo** [comment]
@thea-m please check if the behaviour is as expected and close issue
