### ISSUE TITLE
xml:id in witness

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#333]
It seems that there are several work records which have assigned a xml:id to the witnesses, as for example in LIT2317Senodo:

```xml
<witness corresp="BLorient481#ms_i3" xml:id="blorient481"/>
```              

I think that this might lead to errors on the app.
If I see it correctly, the only place in which this xml:id has been used in the concerned records is to specify `<bibl>` - would it be possible here to use @corresp with the respective ms ID?
@eu-genia @MassimoVilla @PietroLiuzzo

**Comment by PietroLiuzzo** [comment]
the error is given when the xmlid assigned here is the same as a mss record xmlid. the ought to be no problem in using this internal reference as long as the id is unique within the file and is not the same as any record id.

**Comment by eu-genia** [comment]
assigning internal IDs is not a problem and sometimes is necessary or helpful - e.g. for editions and other bibliographic references to specific mss, see LIT1709Kebran 
```
<listBibl type="editions">
               <bibl><ptr target="bm:Praetorius1870Fabula"/></bibl>
               <bibl corresp="#bnfet5 #bnfet146 #BDLbruce93 #BDLbruce87 #berlin395 #blor818 #blor819"><ptr target="bm:Bezold1905KebraN"/></bibl>
            </listBibl>
```

**Comment by PietroLiuzzo** [comment]
in most of the above cases the problem was a bibliographic tag missing or not synced or something of that kind.
The bibliography rendering is now entirely changed and will not stop the page from loading but will load it and popup a message telling you where is the problematic bibl.

**Comment by thea-m** [comment]
If a user happens to enter one of these xml:ids directly into the URL, for example
http://betamasaheft.aai.uni-hamburg.de/manuscripts/bnfet5
a page is opened which seems like a very truncated ms record and contains only the title of the work. Is there any way to prevent this from happening? Someone not knowing that the URLs are case sensitive might easily enter a ms identifier there in lower case, which is how these xml:ids are mostly formed. 
Should we use xml:ids that do not remotely ressemble possible ms Identifiers?

**Comment by PietroLiuzzo** [comment]
the solution you propose is the correct one, it should check before leading to a wrong xmlid that it is a record id. this is part of another issue #467
