### ISSUE TITLE
seals

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#337]
How do we encode information about seals? I see that they have been encoded already as an extra within additions (probably taken from Ethiospare conventions?), but there exists also an element `<sealDesc>` - would it make sense for us to use this? (TEI guidelines describe seals as "attached to documents to guarantee their integrity" - is this our case, or is a seal more like an ownership mark?
(BDLaethg14 for example has seals of Menilek II)

**Comment by MassimoVilla** [comment]
Moreover, we also have StampExlibris (= stamp affixed by the owning institution, e.g., a library) among the values allowed for additiones and taken from Ethio-SPaRe conventions.

**Comment by PietroLiuzzo** [comment]
I see no problem with this. Please follow tei guidelines and provide one or two examples. I will then provide visualization. Any preferences?

**Comment by thea-m** [comment]
From BDLaethg14 (xml:ids added by me, are they fine like this? locus is marked as an error - can this be added to the schema or should it be written somewhere else?):

```xml
  <sealDesc>
                     <seal xml:id="s1">
                        <locus target="#3r"/>
                        <p>Part of the seal of <persName ref="PRS7006Menilek"/> in violet ink.</p>
                     </seal>
                     
                     <seal xml:id="s2">
                        <locus target="#64v"/>
                        <p>The entire seal of <persName ref="PRS7006Menilek"/> in violet ink.</p>
                     </seal>
                  </sealDesc>
```

**Comment by PietroLiuzzo** [comment]
Please use locus inside p. 
The preview now shows this just after binding.
gl updated
I am updating assignees so you can decide what to do on exlibris

**Comment by eu-genia** [comment]
I think that the sealDesc in TEI stands for "real" seals needed in diplomatic studies; we do not have that at all (unless maybe on some letters by kings, so we can keep the element if we ever have a letter to describe, for the moment this is an element that should not be used). Our seals are pure ownership marks, so I would prefer to keep them where they used to be before.

**Comment by DenisNosnitsin1970** [comment]
Just to give some information - on the whole we have ca 35 "seals" in the catalogued Ethio-Spare manuscripts (called here "stamps"), of course mostly reasent, both personal seals of the donors and the seals of owning institutions. We have also some 17 manuscripts with "fingerprints" with names around - used instead of signatures by illiterate persons (this is also a recent practice).

**Comment by eu-genia** [comment]
i still believe that "seal" stricto sensu is made of wax and is appended to the document as a sign of authenticity (not ownership). it is not a stamp.
stamps of donors and owning institutions are ownership notes of the type stamp/exlibris.
stamps that replace signature are possibly a different case.

**Comment by thea-m** [comment]
So we agree that the "seals" we are talking about (I was actually just using Ullendorff's terminology - are my examples (BDLaethg14 ) stamps?) are not made of wax and not attached to the manuscript, therefore don't conform to the definition of the TEI element.

So we would have:
- all stamps of donors and owning institutions, whether modern or not, in additions (as OwnershipNote or StampExlibris? Can an addition have several values?)
- stamps replacing signature not clear yet

**Comment by MassimoVilla** [comment]
Since we potentially have multiple ways to encode seals made of wax and ownership stamps (sealDesc, additiones) the most reasonable solution might be to devote each way to a particular type of item. 
I agree with Dorothea's solution (ownership and donation stamps encoded as StampExlibris).
Anyway, we might fix this in a definitive way in the next meeting.
