### ISSUE TITLE
work subjects

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#338]
For the moment I have been using the relation "saws:P129i_is_subject_of" for the subjects of works.
i hope this is ok but now under Works it is shown as "The following works have a relation saws:P129i_is_subject_of with this work" 

- [x] can this relation be shown as "The following subjects are treated in this work"? or at least "The following entries..."

- [x] On the other hand I would expect under the Persons/Places to see the list of works that point to them as the subject possibly in the main window, taken from the same relation.

- [x] At the moment under Relations only those saved with the person are shown.

- [x] The active/passive order of the subject relation to be clarified too.

**Comment by PietroLiuzzo** [comment]
so, there was a problem with those values as they are not saws but ecrm properties. sorry about that. p129i_is_subject_of should have a person or place as subject and a work as object. so the correct property to use to mark in works the subjects is the inverse of it, P129_is_about.

e.g. 
a WORK is about a Person or a place

a Person is subject of a work

I have updated the records containing this property to use this one instead. 

http://betamasaheft.aai.uni-hamburg.de/works/LIT1113Anqasa shows the subjects in the head
http://betamasaheft.aai.uni-hamburg.de/persons/PRS6819Mary shows the list of works which have it as subject.

**Comment by PietroLiuzzo** [comment]
for the third point I need more specification, please.

http://betamasaheft.aai.uni-hamburg.de/analytic/PRS6819Mary

uses in the graph all available relations (i.e. REALLY too many to be useful in this way IMHO)
in the table displays only those within the record. 

what would you like this or anything else to look like instead?

**Comment by eu-genia** [comment]
i would say possibly one could take out the subject relations since they are listed already above from the graph
one could also possibly create a separate list - possibly also in the main entry window - for the tabots dedicated (in case there are any persName of the tabot type pointing to the record). this is important for the saints. then this type of relation to institutions would not have to be serialized/shown in the graph.
also some LIT titles while appearing correctly in the list of subjects appear with the ID instead of the title in the graph

**Comment by eu-genia** [comment]
there are other relations that must be corrected from saws to ecrm 
e.g. CLP46i_may_form_part_of has been used a lot
and maybe some others

**Comment by eu-genia** [comment]
@MassimoVilla @thea-m @DenisNosnitsin1970 may be interesting for you too

**Comment by thea-m** [comment]
I corrected all, but the schema still reports an error for the new values

**Comment by PietroLiuzzo** [comment]
for which one do you get the error? it might simply be caching, update your local copy of the schema repo and validate to that to test

**Comment by thea-m** [comment]
works now, thanks

**Comment by PietroLiuzzo** [comment]
the tabots, keywords and other relations are under the challenged tab see also...

**Comment by PietroLiuzzo** [comment]
http://betamasaheft.aai.uni-hamburg.de/seealso/PRS6819Mary

**Comment by PietroLiuzzo** [comment]
#295

**Comment by PietroLiuzzo** [comment]
now also other relation are included, with disadvantage on the load time for frequently quoted records
