### ISSUE TITLE
Work status homilies of ʾAragāwi manfasāwi

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#339]
The homilies which are part of the ʾAragāwi manfasāwi are currently textparts of LIT3989Aragawi - but BDLclarkeor3 contains two single homilies, not the entire work (the catalogue gives no information to precisely identify which of the homilies are meant). 
Should individual IDs be created for all homilies, since apparently they can circulate independently? Or is this case an exception and they should remain texparts?
@abausi @DenisNosnitsin1970 @eu-genia @MassimoVilla

**Comment by abausi** [comment]
I would tend to consider these "text parts", in the end, excerpts from 
the work, which, in my impression, has a very stable structure and 
transmission.

Alessandro B.

Il 24.02.2017 08:57, thea-m ha scritto:

**Comment by thea-m** [comment]
Thank you, updated https://github.com/SChAth/Works/wiki/Notes-on-Works-encoding
