### ISSUE TITLE
new id

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#341]
As @sologebre rightly pointed out, the way the id is currently offered is prone to many problems. first of all, you create records simultaneously.

This is a big ISSUE!  Please, report such problems as soon as possible, do not look for workarounds!

I will update the next id function to

generate a full id based on your choice of prefix and name

TEXT1234traest

once you click on take! the numeric part will be updated, you a new file with that id generated. This should also help the generation of files with wrong ids to stop. 

you will have to save this file in the correct works repo and then update that file and commit it as normal.

the file will be already stored in the app and your changes will be synced as such and not as a new file.

**Comment by PietroLiuzzo** [comment]
@eu-genia @MassimoVilla @sologebre @DenisNosnitsin1970 @thea-m please refrain from creating new files until this is working.

**Comment by PietroLiuzzo** [comment]
You shall now find a new "create new entity" function in the list view of the app.

you only need to enter the name of the file, for manuscripts this is the full filename, for the other entities just the last part of the id 

for LIT1234iliad, you would enter only "iliad"

for a manuscript, simply enter the full name, the small print will indicate you what is needed.

as you start typing the button will become active and you can create the file.

this is stored in the app, not in git!

as the confirmation page tells you, you need to
1. download the file
2. save it in a folder called "new" into the proper folder
3. commit and sync to git

once you have done this git and our server will be again in sync, which means you can now move your file if you need to (especially for manuscripts) and then commit and sync this change again.

if you omit the first step, we will have two identical files in two locations and thus the id lookup of the app will fail not showing you your file. On leaving the page you will get a warning every time, intended to make you stop before you carry on without syncing. 

The generated file will have a consistent new id and will insert it in the appropriate place in the file. This should avoid the really frequent problem of ids not being updated after copy-pasting a master file. it remains entirely possible to create your files in oXygen as previously, but this method is recommended as it makes sure your id is unique.

The file will also have the correct type and  a change element with your initials and current date, nothing else.

**Comment by PietroLiuzzo** [comment]
https://github.com/SChAth/ScAthiop/wiki/workflow updated

**Comment by thea-m** [comment]
Don't these files also need in `titleStmt`
 ```xml
  <editor role="generalEditor" key="AB"/>
                <editor key=""/>
                <funder>Akademie der Wissenschaften in Hamburg</funder>
     
```
?
When creating a new work record with this method, somehow the schema doesn't prompt any values, which is quite unpractical - can this be changed to behave as in all other files?

**Comment by thea-m** [comment]
and would it be possible for the "Thank you" page to open in a new tab? It takes relatively long to go back to the list

**Comment by PietroLiuzzo** [comment]
the button now takes you to another page where you get a form depending on the type of item you want to create. I have added functionality to add institution and id to manuscript. Please open new issues with requests or bugs on this new entry form.
