### ISSUE TITLE
add roles for original/later owners?

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#343]
It is often the case that the name of the original owner of a manuscript is subsituted by the names of later owners. We record this information in extras (and of course mark up erasures etc. when actual text is transcribed). 
I was wondering now whether it would make sense to specify the role "owner" by adding for example two more roles, "orginalowner", "laterowner"? Could this be interesting for users to search for, or is it overencoding?

**Comment by eu-genia** [comment]
maybe if we find a way to encode "layers" we could add a corresp to the respective layer id?

**Comment by PietroLiuzzo** [comment]
all owners can be encoded as owners, and there can be more than one for each ms. the values proposed would not help much imho, whereas the issue is certainly related to #327 and [requirement NAV3](https://github.com/SChAth/ScAthiop/wiki/NAV3)
