### ISSUE TITLE
overlines=rubrications in Zotenberg?

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#346]
Zotenberg usually overlines words rubricated in the manuscripts, but in BNFet64, there seems to be an inconsistency:

https://archive.org/stream/manuscritsorient00bibl#page/70/mode/2up

in the incipit of the first work (f. 2r), only ቃለ፡ ኦሪት፡ and ትርጓሜ፡ are overlined, but this doesn't correspond to the rubricated parts in the manuscript:
http://gallica.bnf.fr/ark:/12148/btv1b52000971q/f9.image

Is this a mistake by Zotenberg or did I misunderstand the overlines?
(In the quotation later from the prophecy of Aser, overlines equal rubrications)

**Comment by eu-genia** [comment]
to me it seems an error in Zotenberg. (a copypaste from the second passage)

**Comment by thea-m** [comment]
Seems the most probable to me as well, thank you
