### ISSUE TITLE
new ID creation

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#349]
I believe it would save time if all records except manuscript records created through the new ID function on the app would remain in the "new" folder - so we don't have to move them, re-commit and sync (this adds up when creating a lot of records).
However, we would all need to stick to this workflow, otherwise the folders will quickly become chaotic (especially troublesome if someone happens to create a new record manually)
Do you agree? @eu-genia @MassimoVilla @sologebre  @DenisNosnitsin1970

**Comment by PietroLiuzzo** [comment]
please confirm and close issue

**Comment by eu-genia** [comment]
ok for me

**Comment by thea-m** [comment]
should someone disagree, please reopen
