### ISSUE TITLE
bibliography display

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#350]
In a  `<listBibl>` element  within a msItem containing several items, the items are all displayed on the app following each other without space, not listed separately as in the `<listBibl>` in `<source>` at the end of the record
See for example http://betamasaheft.aai.uni-hamburg.de/manuscripts/BNFet121

**Comment by PietroLiuzzo** [comment]
This is the expected behaviour for a listBibl in a note. if you want the dotted list with the full reference, simply remove the note element around your listBibl

**Comment by thea-m** [comment]
thank you!
