### ISSUE TITLE
title new mss records

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#351]
Currently, newly created mss records have the following title element (in analogy to the other records):

   ` <title xml:lang="gez" xml:id="t1">...</title>`

In the old mss records, we use:

 `<title>...</title>`

We had agreed previously to generally write in the title the works contained in the manuscript in transcription (without marking them up as foreign), but we also occassionally use English here when this is more useful, so it would maybe be better to stick to  `<title>...</title>`?

**Comment by PietroLiuzzo** [comment]
that information is currently used only to print "General Description" which could be easily and nicely just omitted. I would suggest using whatever is simplest in title for mss as this information is not used for important purposes

**Comment by eu-genia** [comment]
agree with dorothea
