### ISSUE TITLE
new manuscript ID

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#352]
When creating a new ms ID, it would be helpful to:

- [x] be able to decide on the amount of msParts to be created
- [x] include one or two msItems, possibly like this:
```xml
 <msItem xml:id="ms_i1">
                            <locus from=""/>
                            <title type="" ref=""/>
                            <textLang mainLang="gez"/> 
                        </msItem>
```
- [x] include    `<physDesc>` with   `<objectDesc>`,  `<handDesc>`,  `<bindingDesc>`
- [x] include   `<history>` with   `<origin>` and   ` <provenance>`
- [x] include  `<additional>` for the catalogue reference

**Comment by PietroLiuzzo** [comment]
- [ ] floruit, birth, death for persons

**Comment by PietroLiuzzo** [comment]
- [ ] note for all
