### ISSUE TITLE
new person records

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#354]
For me, it would be practical if the `<person>` element in new person records would consist of this, since this is the format in which the names of practically all owners/copists etc. of manuscripts are entered:

```xml
<person sex="">
                    <persName  xml:lang="gez" xml:id="n1"></persName>
                    <persName  xml:lang="gez" type="normalized" corresp="#n1"></persName>
                </person>
```

**Comment by PietroLiuzzo** [comment]
done
