### ISSUE TITLE
relation names 

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#355]
copying here part of Dorothea issue.

What is the difference between saws:contains and dcterms:hasPart? (ecrm:P57_has_number_of_parts being used when there are several parts?)

we need to know what you are using these for and how. then I would suggest shortening and making more sensible the actual list of available relations in schema.

**Comment by PietroLiuzzo** [comment]
sensible = with the values you need rather than a long and random list of relations

**Comment by thea-m** [comment]
There is no difference in our use between saws:contains and dcterms:hasPart. Since saws:contains is used more often, I would propose to change every dcterms:hasPart to saws:contains

**Comment by eu-genia** [comment]
yep and then remove dcterms:hasPart from the list to avoid confusion

**Comment by thea-m** [comment]
all changed
