### ISSUE TITLE
option in search to ignore ʾ and ʿ

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#356]
The user needs to be able to opt out or the search should find both with and without

**Comment by eu-genia** [comment]
+ if possible add the possibility (if not there yet) that one types " ' " and finds either ʾ or ʿ

**Comment by PietroLiuzzo** [comment]
' is a reserved character. would ` be ok?
currently entering ʾ and ʿ will search either or none, entering ` will also search either or none.

**Comment by PietroLiuzzo** [comment]
please test and close if ok.

**Comment by PietroLiuzzo** [comment]
tested with abba
http://betamasaheft.aai.uni-hamburg.de/as.html?query=%CA%BEabba

**Comment by thea-m** [comment]
searching for a word starting with a vowel should also point to results ʾ+vowel, if possible
"yekunno amlak" should point to Yǝkunno ʾAmlāk
