### ISSUE TITLE
relation for attested persons

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#357]
sometimes we know a person or a place are attested in a text for which we have a record but no text to mark up with such reference.

we need to find a suitable relation name to describe this in the place or person record

**Comment by thea-m** [comment]
could lawd:hasAttestation be used here?

**Comment by PietroLiuzzo** [comment]
that's what I was thinking about! Thanks a lot! was driving me nuts not to remember!
