### ISSUE TITLE
information on missing quires

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#358]
does information on missing quires belong to `<collation>`, `<binding>` or `<condition>`?
see IVefiopsk4 (currently in  `<condition>`)

**Comment by PietroLiuzzo** [comment]
I think condition is ok in this case. there is no collation and actually this sounds like an event in the history of the manuscript to me, which would need to be considered in https://github.com/SChAth/ScAthiop/wiki/NAV3, #327 etc.
