### ISSUE TITLE
abbreviations

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#359]
A place is needed to encode canonical and/or frequently used abbreviations of titles 
e.g. 
`<title xml:id="t1" cref??="Jn">Gospel of John</title>` or corresp type="abbreviation" or something else in order to be able to look for "Jn" and find "Gospel of John" etc.

**Comment by PietroLiuzzo** [comment]
asked advise on TEI list

**Comment by PietroLiuzzo** [comment]
as suggested by Hugh we will use as many <title type="short"/> as needed.

**Comment by PietroLiuzzo** [comment]
schema and guidelines updated

**Comment by PietroLiuzzo** [comment]
test search with Jn. returns Gospel of John as first hit.

**Comment by eu-genia** [comment]
Before closing maybe draw attention of the others to the new type?

**Comment by PietroLiuzzo** [comment]
sure, I have other changes to notify and I will do in a dedicated email, as I gather not all follow on issues.

**Comment by eu-genia** [comment]
have synced the schema but don't seem to have the type short

**Comment by PietroLiuzzo** [comment]
updated but not yet synced! now they are
