### ISSUE TITLE
symbol substitutions

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#36]
please check that the examples provided here are correct

https://github.com/SChAth/ScAthiop/wiki/guidelines#symbols

**Comment by eu-genia** [comment]
better write
for Schwa - please always use ǝ (01DD, Latin Small Letter Turned E) and not ə (0259, Latin Small Letter Schwa)
for Alif - please always use ʾ (02BE), not ˀ
for Ayn – please always use ʿ (02BF), not ˁ
