### ISSUE TITLE
IVefiopsk5 turaev in binding

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#360]
bei Binding wird der Name von Turaev nicht angezeigt
````xml 
<decoNote xml:id="b1"> According to <persName ref="PRS9602Turaev"/>, the binding is not Ethiopian, but Arabic. Leather boards with tooling; 
                  one pair of sewing stations can be assumed (not indicated in the catalogue)</decoNote>
````

**Comment by eu-genia** [comment]
In such cases actually the reference should be not to person but to `<bibl>` @DenisNosnitsin1970

**Comment by eu-genia** [comment]
(still the name of course should appear, there can be cases when the reference is indeed to a person and not a book)
