### ISSUE TITLE
order of msItems/decorations in scrolls

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#367]
As it is not possible to add a `<locus>` to msItems etc in scrolls, how can the relative sequence of items be described? (See for example BDLaethf4 or BDLaethf5)

I have now added the msItems simply in their sequence and described the decorations in `<decoNote>` as usual, adding their relative location in the scroll:
 ```xml
<decoNote xml:id="d1" type="drawing">
<desc>Crude drawing of two angels and a cross before <ref target="#ms_i1"/>.</desc>
</decoNote>
```
is it fine like this, or is there a better way?

**Comment by PietroLiuzzo** [comment]
I think this is ok. Although I am not sure to fully understand the question. Is the problem that there are no folia thus no numbers for locus? Is the order of the msitems different from "relative order"?
encoding is correct and the ms items have ordered ids. Are there more scrolls into each ms item that need better referencing?

**Comment by thea-m** [comment]
No, the relative order is the same as that of the msItems, so probably it is fine like that, thank you! The scrolls consist of several strips, but their length is not indicated in the catalogue

**Comment by PietroLiuzzo** [comment]
Out of pure intuition as I know nothing about this ms. There might be a part for each scroll which is material distinction and an item for each strip (?) If it conrains a text. Not really sure how this looks bur I think the markup is fine
