### ISSUE TITLE
use of msFrag

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#368]
Question arrising from BNFet165#p4_i1 (https://archive.org/stream/manuscritsorient00bibl#page/266/mode/2up), which contains several leaves that were detached from BNFet45#ms_i1.1 (https://archive.org/stream/manuscritsorient00bibl#page/42/mode/2up):

 I have just stated this information in a note in both mss records, but maybe msFrag should be used here?

Our guidelines state that "msFrag can be used when there are at least two parts of one manuscript kept in different repositories.", but the TEI guidelines state that "The msFrag element may be used inside msDesc when encoding one or more fragments of a scattered or fragmented manuscript. The fragment(s) described in a single msDesc element may be held either at several institutions or at a single institution, so different call numbers may be attached to the fragments. " - this seems to apply to my case.
What do you think?

**Comment by thea-m** [comment]
see also #369

**Comment by eu-genia** [comment]
i read from the TEI guidelines in the sense that one creates one record for the "abstract" original manuscript as it used to be, which consists then of msFrag each with its own idno/call number.

**Comment by eu-genia** [comment]
like the Codex Suprasliensis example they provide (the Codex only exists as a virtual reconstruction):

	
```
<msDesc>
 <msIdentifier>
  <msName xml:lang="la">Codex Suprasliensis</msName>
 </msIdentifier>
 <msFrag>
  <msIdentifier>
   <settlement>Ljubljana</settlement>
   <repository>Narodna in univerzitetna knjiznica</repository>
   <idno>MS Kopitar 2</idno>
  </msIdentifier>
  <msContents>
   <summary>Contains ff. 10 to 42 only</summary>
  </msContents>
 </msFrag>
 <msFrag>
  <msIdentifier>
   <settlement>Warszawa</settlement>
   <repository>Biblioteka Narodowa</repository>
   <idno>BO 3.201</idno>
  </msIdentifier>
 </msFrag>
 <msFrag>
  <msIdentifier>
   <settlement>Sankt-Peterburg</settlement>
   <repository>Rossiiskaia natsional'naia biblioteka</repository>
   <idno>Q.p.I.72</idno>
  </msIdentifier>
 </msFrag>
</msDesc>
```

**Comment by eu-genia** [comment]
(Ullendorff's split scroll might fit, if one describes it as one scroll consisting of two msFrag, the rebinding of several fragments of various mss in another codex sounds like a different case)

**Comment by PietroLiuzzo** [comment]
I have no objection to the use of msFrag here, although I think the way you have stated this in your file is fine. It might be also a topic worth posting to the TEI list, to see what people have been doing in such cases. 
In the ref you could have pointed to BNFet45#ms_i1.1  rather than just BNFet45, or did this generate problems?

**Comment by thea-m** [comment]
corrected the ref

**Comment by PietroLiuzzo** [comment]
- [ ] encode the two ms with msFrag for the part which is not there any more and msPart for the second manuscript
- [ ] document in GL decision to encode as msPart in second ms and as msFrag in the first ms
