### ISSUE TITLE
list name of relations in guidelines by type as in IHA

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#374]
pers/pers
mss/mss
text/mss
mss/text
etc.

**Comment by PietroLiuzzo** [comment]
@thea-m you had started a very nice job in this direction, am I wrong? would you copy it in the guidelines under relations organised as above? I think it would be useful.
I have started here a subdivision. https://github.com/SChAth/ScAthiop/wiki/guidelines#relations
I think @sologebre should know best what to list under pers/pers
this and the values in the list for new record should be aligned and consequently I will clean the schema from unused values

**Comment by thea-m** [comment]
Added my list to the guidelines according to categories (but this is not, I believe, an exhaustive list of all relations used in our records)

**Comment by PietroLiuzzo** [comment]
the following are the values in use currently (xpath: distinct-values(//t:relation/@name)
to see in which records these values occur you can use the [xpath search functionality like this](http://betamasaheft.aai.uni-hamburg.de/xpath.html?xpath=collection%28%24config%3Adata-root%29%2F%2Ft%3Arelation%5B%40name%3D%27motherOf%27%5D)

motherOf
snap:GrandsonOf
snap:StepFamilyRelationship
snap:AllianceWith
saws:isAttributedAuthorOf
wifeOf
ecrm:P129i_is_subject_of
sisterOf
daughterOf
grandfatherOf
snap:SonOf
sonOf
snap:FatherOf
unspecified
bm:husbandOf
snap:CousinOf
snap:BrotherOf
rel:enemyOf
bm:ordainedBy
husbandOf
snap:NephewOf
snap:FriendshipFor
bm:wifeOf
snap:MotherOf
snap:HouseholdOf
brotherOf
snap:DaughterOf
snap:SisterOf
snap:GrandmotherOf
snap:GrandfatherOf
bm:hasOrdained
saws:isAttributedToAuthor
saws:isSiblingOf
snap:GrandchildOf
saws:P129i_is_subject_of
snap:GreatGrandfatherOf
lawd:hasAttestation
saws:hasOwned
saws:hasWritten
snap:Group
bm:isAuthorOfEthiopicTranslation
snap:GranddaughterOf
snap:IntimateRelationshipWith
snap:NieceOf
snap:SiblingOf
snap:UncleOf
saws:isCopierOf
syriaca:has-relation-to-place
saws:isMemberOf
dcterms:isPartOf
bm:sonInLawOf
saws:
bm:fatherInLawOf
saws:isRelatedTo
bm:baptizedBy
snap:KinOf
syriaca:born-at
snap:LegallyRecognisedRelationshipWith
snap:InLawFamilyRelationship
snap:EmnityFor
gn:nearBy
gn:locatedIn
saws:isDirectCopyOf
saws:isAncestorOf
saws:isCloseTranslationOf
saws:formsPartOf
ecrm:P129_is_about
saws:isVersionInAnotherLanguageOf
saws:contains
saws:isDifferentTo
ecrm:CLP46i_may_form_part_of
saws:isShorterVersionOf
saws:follows
dcterms:creator
saws:isVersionOf
dcterms:hasPart
syriaca:possibly-identical
saws:isLongerVersionOf
saws:fallsWithin
saws:isVariantTranslationOf
saws:isVariantOf
saws:AbstractManuscriptText
ecrm:F15_Complex_Work
ecrm:P57_has_number_of_parts
saws:hasUsed
syriaca:share-a-name
saws:isChildOf
saws:hasDescendant
saws:hasComment
saws:hasChild
contains
saws:hasParent
