### ISSUE TITLE
creating new IDs

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#375]
The function to create new IDs on the app is apparently currently not synced with our records, so should not be used (It just created for me PRS11488TawaldaM, though we are already at PRS11504WalattaK)
@MassimoVilla @sologebre @DenisNosnitsin1970

**Comment by PietroLiuzzo** [comment]
As per emails, **the app is not yet live** in all is functionality. especially the git sync script does not work yet, i.e. the app **IS NOT synced at all** with the git repo. However, the function can be used with caution and at your own risk. the progression of numeric values is anyway unimportant, given they are unique, and should not create concern. e.g. PRS11488TawaldaM and PRS11488Tawalda are two ok ids. @MassimoVilla @sologebre @eu-genia @DenisNosnitsin1970 @thea-m . closing this as it is not an issue, is a known system down, although longer then expected.
