### ISSUE TITLE
space error in new person files?

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#376]
Not sure if this is an issue, but it seems to me that in new person records created through the app, there is always a space after the value in `<faith type="">`:
`<faith type="EOTC "/>`
This is the case for most records in the “new” person folder.
(some cases might also be copy paste errors)
(Can't try it out now by creating a new ID because I constantly get the same old (cache?) error)

**Comment by PietroLiuzzo** [comment]
yes, there was an unwanted space created after the inserted value.
