### ISSUE TITLE
encoding cancelled/exponctuated text

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#377]
Which values do we use for encoding cancelled (struck out) words?
And for "exponctuated" words (what is described in Ethiospare records as "Immediate corrections are indicated by thin lines or dots above and below the letters or words to be cancelled")?

**Comment by PietroLiuzzo** [comment]
Is del[@rend=erasure] not ok?

**Comment by PietroLiuzzo** [comment]
http://www.tei-c.org/release/doc/tei-p5-doc/de/html/ref-del.html

Overstrike is also an available value and I can visualize it in any way

**Comment by PietroLiuzzo** [comment]
Or strikethrough

**Comment by PietroLiuzzo** [comment]
I have added rendering options for del[@rend='erasure'] which you can continue to use as before and also for del[@rend=strikethrough]. in the value I have added also exponctuated, but I am not sure how you want this to be visualized.
