### ISSUE TITLE
allow listBibl in colophon?

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#381]
`<listBibl> `in a colophon is currently marked as an error, can it be allowed?
(in BNFet112#coloph1 the bibliography is currently written in a note and thus not well displayed on the app)

**Comment by PietroLiuzzo** [comment]
intext bibl is the desired output in a note for listBibl. I have removed the double entries.

**Comment by thea-m** [comment]
I don't actually want it in a note, it was just there so the record would be validated...how could I add general secondary bibliography about a colophon?

**Comment by PietroLiuzzo** [comment]
I fail to understand, sorry! Could you please tell me why it is not fine in a note? Do you fell the way you are doing is not correct for some reason? thanks!
