### ISSUE TITLE
authorship displayed in work records

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#383]
(maybe this question is the one dealt with in #226) 
If I see it correctly, currently all authorship-related relations are displayed in the work records under "author" - but it is not differenciated in this display whether the entire work or a part of it is attributed to a certain author (see for example LIT1295Dersan, where different textparts are attributed to different authors, which cannot be understood from the app). This is mainly a problem for relations for which no `<desc>` has been provided - should it be added to the guidelines that `<desc>` has to be given with each relation? 
The relations containing `<desc>` are also not correctly displayed, at least in my browser: the text contained in `<desc>` is printed once as a link, but without the marked up words, and then again correctly (for example in LIT1295Dersan#HomilyGenbot).

**Comment by PietroLiuzzo** [comment]
check if it is better now, please

**Comment by thea-m** [comment]
great!
