### ISSUE TITLE
clavis in zotero

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#387]
@eu-genia could I please ask you to add the correct clavis references to Zotero if they are not yet there and assign them the following tags? I have added CPG, but I am not sure at all that it is the correct record.

clavis|target
|----|----|
 Clavis Coptica | bm:CC
CPG Graecorum | bm:CPG
BHO Bibliotheca agiographica | bm:BHO
CANT Apocriph. Nuovo Testamento | bm:CANT
CAVT Apocriph. Antico Testamento | bm:CAVT
BHL Biblioteca Agiographica latina | bm:BHL
Syriaca.org | bm:syriaca

this way I can then create a correct code template for them

**Comment by eu-genia** [comment]
most of these works are multi-volume works, where each volume has to be entered separately according to the bibliography rules. 
e.g. CPG are 6 books (for now). can they have then each their individual tag/id (bm:CPG1 bm:CPG2) + the "group tag/id" (?) 
the work numbering within CPG is of course continuous.

**Comment by eu-genia** [comment]
or maybe group tag is not needed at all as there is a reference type and then the zotero link goes to the specific one... only in the visualization for the cases where one of these types is selected the abbreviation and not the complete title should be shown.

**Comment by eu-genia** [comment]
have added all, please check and use
