### ISSUE TITLE
add certainty in locus?

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#388]
would it be possible to add `<certainty>` in `<locus>`?
For instance, I have `<locus from="1" to="129r">` where to="129r" is a conjecture. If I add cert=low it is not clear to which value I refer.
(Otherwise it is of course possible to leave it simply at `<locus from="1">`)

**Comment by PietroLiuzzo** [comment]
done, please update schema repo.

**Comment by thea-m** [comment]
Thank you, I updated everything and waited a bit, but it's still marked as an error

**Comment by PietroLiuzzo** [comment]
tested validating to local copy?

**Comment by thea-m** [comment]
works now, thanks
