### ISSUE TITLE
Keywords per periodi letteratura 

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#390]
Paola Buzi consiglia l'impiego di Keywords per le opere relative al periodo di produzione. Credo sarebbe utile accanto all eventuale data di creazione. Quali potrebbero essere i valori?

**Comment by abausi** [comment]
Potrebbero essere (si intende, per la produzione/creazione delle 
traduzioni etiopiche! altrimenti la cronologia va impostata in 
tutt'altro modo):

Aks = Aksumite = 300-700 CE
Paks1 = Postaksumite I = 1200-1433
Paks2 = Postaksumite II = 1434-1632
Gon = Gondarine = 1632-1769
ZaMa = Zamana Masāfǝnt = 1769-1855
MoPe = Modern Period = 1855-1974

Naturalmente, non ho idea di quanto dettagliata debba essere la griglia 
e qual è esattamente lo scopo della proposta. Se si deve invece adottare 
una periodizzazione universale, è tutt'altro discorso.

A presto,
grazie mille!

Alessandro

Il 28.03.2017 17:55, Pietro Liuzzo ha scritto:

**Comment by PietroLiuzzo** [comment]
Grazie!

**Comment by PietroLiuzzo** [comment]
@abausi che riferimenti bibliografici di base si possono dare per questa periodizzazione? ne basterebbe uno, massimo due.

**Comment by abausi** [comment]
Userei sempre ancora qualche vecchia letteratura, per es. Cerulli 1968 o anche Guidi 1932; altrimenti dovremmo indicare più opere, ma credo che per i nostri scopri potrebbe bastare anche solo Cerulli 1968
