### ISSUE TITLE
Persons folder: "PRS11001-12000" or "new"?

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#397]
Should the newly-created Persons records be added to the folder named as "PRS11001-12000" or to the folder names as "new"?
The numeric part of the records in the "new" folder reaches now PRS11533, but new files have been recently created in the  previous folder, covering the (already used) values from PRS11517 to 11526.
The second part of the IDs makes them ultimately unambiguous, but parallel sets of records in different folders should be in my opinion avoided.

**Comment by thea-m** [comment]
I would be in favour of adding them all to the "new" folder

**Comment by PietroLiuzzo** [comment]
When creating the records from the app, the first commit they MUST be added to the new folder. Then as per previous issues there it should remain. 

If you are creating new records manually, please add them ALSO to the NEW folder in git and try not to reuse numbers. 

This is making me think we should stick to creating new records in the app. Especially if this happens for Works where the numeric id is our clavis number and thus shall not be reused or duplicated. 

@eu-genia your latest records in this folder, which are the ones Massimo is talking about can stay, but please next time either check the numeric value of the latest entry in the new folder or use the app to create new records. Thanks!

**Comment by eu-genia** [comment]
i do not know why but yesterday and the day before i was not able to create new persons and/or places from the app, so i went the old way...

**Comment by PietroLiuzzo** [comment]
if some parts of the app are not working you should please fire an issue or notify me if it is very urgent on skype or email so that the problem can be sorted when you need without workarounds. Thanks!
