### ISSUE TITLE
keywords for hymns etc to God/Saints

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#400]
Which keywords should be assigned to these hymns (such as Chaine's répertoire or the many records we create from short descriptions in the catalogues)? We didn't always use the same ones and of course we should
Can we agree on:
ChristianLiterature
Poetry
(I added Hagiography to hymns to saints, is this correct?)
?

**Comment by MassimoVilla** [comment]
I agree with the proposed set of keyword values (I have been using ChristianLiterature quite inconsistently at the beginning, I'm now adding it whenever needed).

**Comment by eu-genia** [comment]
yep have been doing the same for the hymns
