### ISSUE TITLE
records not displayed on the app

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#403]
The following ms records lead to errors on the app:
BDLaethc1
BDLaethc2
BDLaethd4
BDLaethd6
BDLaethe3
BDLaethf1
BDLaethf11 (msFrag)
BDLaethg11
BDLaethg18
I can't find mistakes in the records

**Comment by PietroLiuzzo** [comment]
please try to comment out parts of the files to identify the area where the problem occurs. the error message hints to some wrong or double ids.

**Comment by thea-m** [comment]
Sorry for not trying this before. 
The problem in most of the records was that I used `<ref type="hand" corresp="#h...">` and <`ref type="mspart" corresp="#...">` to refer to IDs within the same record. I corrected them to `<ref target="#..."/>` 
In BDLaethd6 the problem seems to be that I used `<material key>` twice for the description of the manuscript, which consists of paper and parchment parts. Should I just leave this out for the general `<physDesc>`? It is specified in each msPart anyway

**Comment by thea-m** [comment]
`<ref type="..." corresp="#...">` for pointing to an ID within the same record has also been used in records by @eu-genia  and @MassimoVilla  (see also my third comment in #216 ): is this actually allowed or should we switch to `<ref target="#..."/>` in these cases?

**Comment by PietroLiuzzo** [comment]
could you provide some examples please?

**Comment by thea-m** [comment]
For instance, in BDLaethe3, I had  
```xml
<seg type="script">Written in a mediocre hand and in a more conventional ductus than <ref type="hand" corresp="#h1"/>.</seg>
```
(corrected now to `<ref target="#h1"/>`)
Other examples would be in ESbmqm003, BLadd16197, BLadd16201 (all not displayed currently)

**Comment by PietroLiuzzo** [comment]
does not seam to be any more an issue, but will keep the link to the one about clarifying the use of ref corresp and target
