### ISSUE TITLE
Encoding of conluding formulae

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#408]
Even though they occur often, I am still unsure about how to encode simple concluding formulae as are often quoted in the catalogues, such as
 ተፈጸመ፡ መጽሐፈ፡ ነገሥት፡
"The book of the Kings has been completed". 

We have encoded them as
- explicit (but this seems not to agree entirely to the TEI guidelines: " `<explicit>` contains the explicit of a manuscript item, that is, the closing words of the text proper, exclusive of any rubric or colophon which might follow it." )
- in additions as ScribalNoteCompleting or Subscription: These are maybe more exact but lead to the impression that the concluding formula has been added later to the manuscript
- as colophon (but as I understood it, this should only be used if concrete information of the circumstances of copying are given)
- (there is also the element `<finalRubric>` which we haven't used at all - would this make sense here or add more confusion?)

We should agree on a standard and then revise our records.

**Comment by eu-genia** [comment]
I must say I like `<finalRubric>` if we do agree with the very restrictive definition of `<explicit>` in TEI (though I doubt this is the universal definition of an explicit... (as a side note: in the Coptic PATHs project it seems that they use the terms "inscriptio" and "subscriptio" to define the titles appearing at the beginning resp. the end of a text, but I do not believe these are universally accepted terms either).

**Comment by eu-genia** [comment]
Another problem with phrases like in the example is that it is a complete sentence, not simply a title.
There is a difference between "ተፈጸመ፡ መጽሐፈ፡ ነገሥት፡" and simply "መጽሐፈ፡ ነገሥት፡" in an extra line or otherwise highlighted, which would clearly fall under a "rubric" definition...

**Comment by thea-m** [comment]
NB: The term "subscription" would probably be the most adequate, I only think that the encoding as "addition" is problematic. There are several cases now in the records where the fomula has been encoded as explicit or colophon and then been referred to in written text as subscription, which is not very consistent

**Comment by eu-genia** [comment]
"addition" should definitely be corrected (it is not incorrect though in cases where a title/rubric was clearly added by a later hand at a later point)
i may have used colophon type subscription somewhere... possibly explicit type subscription could be introduced instead

**Comment by thea-m** [comment]
Explicit type subscription seems very nice to me (especially as we might also have cases where a "true" explicit can be encoded) - would this be possible, @PietroLiuzzo ?

**Comment by thea-m** [comment]
Or we could just write them as a textpart in the text transcription?

**Comment by PietroLiuzzo** [comment]
- [ ] you are already using explicit type subscription. it is bad practice not to have it in the guidelines! please make sure you first update the guidelines and notify everyone officially before putting a decision into use.
- [ ] if this needs to be displayed in a particular way, please clarify that.
- [ ] inconsistent encoding of the same phenomenon should be made homogeneous if you then expect to find consistent results
- [ ] to update the schema we need a clear definition. I think no one expects to find universally accepted terms, but a definition indeed!

**Comment by thea-m** [comment]
the current definition of "Subscription" in the schema is: "note added at the end of the main text concerning its completion." - we could use this for <explicit type="subscription"> and clarify in the guidelines that additions are only to be used for later additions to the text
It will take some time to go through all the records to make this homogenous: it would maybe be best if everyone does this for their own records when they have time and comment on this issue when they are finished, so that we can close the issue then

**Comment by thea-m** [comment]
updated guidelines

**Comment by eu-genia** [comment]
done on my part of BLorient

**Comment by thea-m** [comment]
maybe Explicit type subscription could be visualized as "Subscription" instead of "Explicit"?
