### ISSUE TITLE
Pointer

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#414]
On the app, the pointer doesn't change to a hand over "Bibliography", "Indexes" and "Resources"

**Comment by eu-genia** [comment]
I guess this is because there are submenus (where the hand does show), but maybe they should drop down on hover not on click

**Comment by thea-m** [comment]
I'm also in favour of dropping down on hover

**Comment by PietroLiuzzo** [comment]
missing a  href="#" apparently... sorry about that...
