### ISSUE TITLE
institutions/places/repositories

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#416]
Just as a reminder: I believe that during the last meeting it has been decided that the libraries (currently labelled institutions) should be (1) re-labelled repositories and (2) be listed also together with the places, as many are also places.
We might also need entries for institutions in the sense of entities - simply under places or separately? E.g. not only EOTC (now a confession, as mentioned in the meeting) but also e.g. Universities or similar. (?)

**Comment by PietroLiuzzo** [comment]
I would institutions or places if there is a need for them with the types available.
