### ISSUE TITLE
places creation listRelation

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#418]
- [x] if no relations selected do not print the empty listRelation

**Comment by thea-m** [comment]
same for works

**Comment by eu-genia** [comment]
while person creation allows selecting text attested in; places creation does not (should better be there for all)
person creation should also allow "group" (and also deselecting male/female)

**Comment by PietroLiuzzo** [comment]
As discussed in last meeting, marking where a person or a place are attested instead of marking the text where they actually are should be only a temporary work around where strictly necessary to make this connection from now. Persons and places should be tagged in the text where they occur.

**Comment by PietroLiuzzo** [comment]
I will add this as to places only.

**Comment by PietroLiuzzo** [comment]
note that attestation now is a lookup, i.e. it loads values on demand rather than loading the entire list at page load.
