### ISSUE TITLE
person creation form

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#421]
- [x] group as alternative to m/f

- [x] distinguish keywords faith/occupation / general type

**Comment by thea-m** [comment]
and would it be possible to directly add the viaf link?

**Comment by eu-genia** [comment]
then also gn:  for places ;)

**Comment by PietroLiuzzo** [comment]
#211

**Comment by PietroLiuzzo** [comment]
instead of mixing the two distinct informations on gender and group, I have added a small script that disables gender if group is ticked.

**Comment by thea-m** [comment]
Now it is not possible anymore to add relations to the form, which was very practical (and any information added to "Attested in" is not transferred to the record)

**Comment by PietroLiuzzo** [comment]
you will need to be patient as I am working on this to fullfill the above requirements.

**Comment by PietroLiuzzo** [comment]
relations and note are there now, and also attestations.

**Comment by thea-m** [comment]
Thank you!

**Comment by PietroLiuzzo** [comment]
it is now possible in the form to enter the wikidata Q item id for both places and persons. without lookup because it is much easier to google, disambiguate and get the id to enter in the form.

**Comment by PietroLiuzzo** [comment]
the form will also validate its format
