### ISSUE TITLE
spaces left for rubrication

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#425]
can I mark up in text spaces left for rubrication, which were left unfilled? 
 `<gap reason="rubrication">` maybe?

**Comment by PietroLiuzzo** [comment]
sure!

- [ ] update schema for gap reason rubrication
- [ ] update guidelines for gap reason rubrication
- [ ] update visualization of gap reason rubrication

**Comment by PietroLiuzzo** [comment]
third point requires you to provide me with an example of how you would like this to be displayed.

**Comment by thea-m** [comment]
the guidelines said "`<space reason="rubrication" unit="chars" quantity="1"/>`" - I corrected `<space>` to `<gap>`, I suppose that's what you meant?

**Comment by PietroLiuzzo** [comment]
no, the error is here in the issue. a space voluntarily left e.g. for later rubrication never accomplished, is a space. space[@reason='rubrication'] should be now replace where used by (3 chars left for rubrication and never filled)

**Comment by thea-m** [comment]
<space reason="rubrication" unit="lines" quantity="1" n="1"/> is marked as an error in BDLpoc8, not sure where the mistake here is. Maybe I misunderstood this issue and the guidelines

**Comment by PietroLiuzzo** [comment]
I have added a rule to the schema, update schema repo and test validating locally please

**Comment by thea-m** [comment]
thank you!
