### ISSUE TITLE
manuscript item view in app : layout suggestions

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#431]
Suggestions from Sophia: 
The app's layout is still very confusing to those not working with it. 
- [x] It would be maybe more user friendly if codicological information were presented in a less prominent way (maybe by appearing only when clicking on "Codicological information", or something similar) while the manuscripts' content (which is presumably what the majority of users will be interested in) 
- [x] should be immediately visible (it is not immediately clear that one has to click on the "item" buttons to get to the detailed content description).
- [x] The presentations of manuscripts consisting of several codicological units might be especially confusing to those not used to this terminology, and it would be helpful if, when opening such a record, the content of all parts would be visible at once

**Comment by PietroLiuzzo** [comment]
@DenisNosnitsin1970 @eu-genia @thea-m @MassimoVilla please comment and expand to clarify the requirement. a drawing of how you would like the item to look like would very much help.

**Comment by PietroLiuzzo** [comment]
#295
