### ISSUE TITLE
model for narrative unit

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#44]
create basic template for narrative unit

**Comment by PietroLiuzzo** [comment]
@MassimoVilla would you have an example of a reused text narrative please ?

**Comment by MassimoVilla** [comment]
I am not sure I understood what you exactly need.
Do you mean a narrative which has been re-written and incorporated in a different text (e.g., a text originally translated from Greek/Arabic, then secondarily reworked in order to form a homily to be read on a given day), or rather episodes/elements/allusions linking more texts together as one presumably borrowed them from another textual source (e.g., the Roman provenance of a saint, episodes of the saint's activity amongs pagans/Muslims, common visions, the typically cruel executions of some martyrs)?

**Comment by PietroLiuzzo** [comment]
I think a typical execution or miracle would do for a model file. We need
also to decide which information pertain to such entity.

* title
* short description

only?

On 6 May 2016 at 10:48, MassimoVilla <notifications@github.com> wrote:

> I am not sure I understood what you exactly need.
> Do you mean a narrative which has been re-written and incorporated in a
> different text (e.g., a text originally translated from Greek/Arabic, then
> secondarily reworked in order to form a homily to be read on a given day),
> or rather episodes/elements/allusions linking more texts together as one
> presumably borrowed them from another textual source (e.g., the Roman
> provenance of a saint, episodes of the saint's activity amongs
> pagans/Muslims, common visions, the typically cruel executions of some
> martyrs)?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/SChAth/ScAthiop/issues/44#issuecomment-217399753>
>



-- 
Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by MassimoVilla** [comment]
A frequent miracle worked by a number of saints (Marha Krestos, Yohanni Mesraqawi, others) is the following: the saint makes miraculous water spring from a rock, and the blessed water has prodigious powers. It heals the ill in various ways, makes an infertile woman pregnant, or even resuscitates the dead.
Another typical topos of the Ethiopic Vitae is the way the saint leaves his own family: demanded to get married, the saint escapes from the secular world and embraces the monastic life. This happens frequently in the hagiographical works.
But let me express a concern regarding the narrative units. Just remaining within the field of the Ethiopian hagiography, it is true that on the one hand these works display a certain distribution of common literary motifs (variously inflected in each work), but on the other hand we do not know how far we can regard these literary works as structures that can be more or less systematically segmented in subparts. I do not know how far variety can blur our attempt to formalize narratives, and little investigation has been made in this direction. This is not a criticism, it's something we will possibly have to pay attention to.
Moreover, handling the relations narrative/text requires a very deep acquaintance with each text, which will have to be scrutinized in detail. This is an additional task we necessarily have to postpone after a first stage of the project. But I understand that we want to establish at least the template as soon as we can.

**Comment by PietroLiuzzo** [comment]
I think that a very light model can allow flexibility and further future
development. We can restrict this model at the moment to a simple title and
description as the one you provide and see if it is useful. I think the
distinction made by Orlandi between textual units (corresponding to the
abstract notion of work, and with consideration of the occasions in which
it has been altered) and narrative units independent of such textual units
of which they are part would be very important to make and could constitute
a basis for further enquiry into this field making the catalogue much more
valuable as a research tool. I agree that only at a later stage when such
texts will be there and marked up this will become really useful.

On 6 May 2016 at 19:31, MassimoVilla <notifications@github.com> wrote:

> A frequent miracle worked by a number of saints (Marha Krestos, Yohanni
> Mesraqawi, others) is the following: the saint makes miraculous water
> spring from a rock, and the blessed water has prodigious powers. It heals
> the ill in various ways, makes an infertile woman pregnant, or even
> resuscitates the dead.
> Another typical topos of the Ethiopic Vitae is the way the saint leaves
> his own family: demanded to get married, the saint escapes from the secular
> world and embraces the monastic life. This happens frequently in the
> hagiographical works.
> But let me express a concern regarding the narrative units. Just remaining
> within the field of the Ethiopian hagiography, it is true that on the one
> hand these works display a certain distribution of common literary motifs
> (variously inflected in each work), but on the other hand we do not know
> how far we can regard these literary works as structures that can be more
> or less systematically segmented in subparts. I do not know how far variety
> can blur our attempt to formalize narratives, and little investigation has
> been made in this direction. This is not a criticism, it's something we
> will possibly have to pay attention to.
> Moreover, handling the relations narrative/text requires a very deep
> acquaintance with each text, which will have to be scrutinized in detail.
> This is an additional task we necessarily have to postpone after a first
> stage of the project. But I understand that we want to establish at least
> the template as soon as we can.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/SChAth/ScAthiop/issues/44#issuecomment-217507840>
>



-- 
Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo
