### ISSUE TITLE
ጙ missing in guidelines?

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#441]
https://github.com/SChAth/ScAthiop/wiki/guidelines#text-transcription

could somebody check if this ጙ is missing in this page? if yes, could you update that page and close this issue? 
thanks!

**Comment by MassimoVilla** [comment]
Added to guidelines:
 ጘ	[ŋa]
ⶓ	[ŋʷa]
They are additional letters not currently used in Gǝʿǝz, which indicate velar nasal consonants.
