### ISSUE TITLE
list of catalogues

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#454]
I though we had such thing somewhere but apparently not. We need a list of catalogues to be digitized which reports also the copyright and availability in digital format. I think this should be given high priority. Also in such list should be clear which catalogues need to be considered in which order. the example brought to our attention is the dÁbbadie collection with three differing editions of the catalogue. in such cases we need to go through the first, then the second and then the first edition, if they contain *significant* disagreement.

I would suggest to add such list for the moment in a new page of the wiki in the manuscript repo, then I will move it to an authority list. 

each catalogue should have a bm: zotero tag.

**Comment by thea-m** [comment]
I started setting up the list:
https://github.com/SChAth/Manuscripts/wiki/List-of-manuscripts
 
Please feel free to add to it and/or change the order of priority

**Comment by MassimoVilla** [comment]
Added new catalogues. The list is still largely incomplete and the order of priority can be obviously changed.

**Comment by PietroLiuzzo** [comment]
please note that there is now a view with available catalogues (from listBibl[@type='catalogue'])
http://betamasaheft.aai.uni-hamburg.de/catalogues/list
you can click on the bibliographic note to go to a list of manuscripts from which contain a link to the specified catalogue.
