### ISSUE TITLE
naming of ms records without shelfmark

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#457]
From discussion with @sologebre :
Do we have guidelines on how to name records of manuscripts that have not been catalogued yet and thus have no shelfmark (and belong to no "collection" other than the insitution holding them?)
I see that some files have been named for their content, i.e. DabraBizanSenodos1. We now similarly created TMChronicle1
Maybe we should add this to the guidelines? 
@eu-genia @MassimoVilla @PietroLiuzzo

**Comment by eu-genia** [comment]
we should always as far as possible first refer to the institution then to collection and then to the manuscript; if there is no id then an "invented" title followed by a number

**Comment by thea-m** [comment]
This is what we did, I added it to the guidelines now
