### ISSUE TITLE
keyboard

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#458]
once the keyboard is activated one cannot simply type in Latin script as the keyman combinations get automatically converted - i guess this is what it is meant for but it should be made clear somewhere. 
(a word in transcription that consists of both diacritica and normal signs is a bit difficult to type)

**Comment by PietroLiuzzo** [comment]
This is explained in the info modal and is fully documented. There was already an issue by dorothea about this which lead to make the keyboard activable only on clicking the keyboard button.

**Comment by eu-genia** [comment]
i am not sure this would be all that clear for an outside user

**Comment by PietroLiuzzo** [comment]
please provide a suggestion on how to make it more clear, I believe a full explanation and a button option are pretty much what one can expect but I am open to consider improvements of course!
