### ISSUE TITLE
Introduction to the Gospels etc - textparts vs IDs

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#459]
The Introduction has been reduced to textparts of LIT1560Gospel, but how do we now distinguish cases when the Four Gospels contain no Intro at all?
As in other similar cases I would say the Intro (as a whole) needs its own ID back (LIT2705Introd, possibly also LIT2706Introd as all optional parts must get independent IDs to be able to distinguish)
Also the Canon tables (see issue [https://github.com/SChAth/ScAthiop/issues/336] - now closed but not implemented as far as I can see) have not yet been promoted back, judging by the structure of LIT1560Gospel, and are still referred to by a derived ID everywhere in the mss

**Comment by thea-m** [comment]
Based on the introduction in Zuurmond's edition of the Gospel of Mark and our previous discussions, 
I would propose the following ID structuring for records related to the Four Gospels. Please correct me!

I am sorry for this lengthy and possibly confusing post, but I believe that it is important to close this issue according to our guidelines and apply the decision consistently to our records. We have already changed these records repeatedly and have then had to rewrite manuscript descriptions. Our manuscript descriptions currently reflect various stages of this discussion and are far from homogenous and complete. 

Individual IDs should be created for the following works which usually accompany the four gospels in varying order:

Introduction:

- Gəṣṣāwe śərʿat (LIT1548Gessaw)

- Introduction on the four Evangelists and their Symbols

- Note on the Original Language and Translation

- Maqdəma Wangel (its 7 chapters are textparts)

- Notes on the Stichometry (or should this be a textpart of Maqdema Wangel?)

- Short Note on the Symbol of the Four Evangelists (or should this be a textpart of Maqdema Wangel?)

- Note on the 72 Disciples

- Note on the Episcopal Sees of the Four Evangelists

- Introduction on the Reliability of the Gospels

Letter to Carpianus and Canon tables:

- The Letter of Eusebius to Carpianus (Generic record)

- The Eusebian Canons (generic record for mss where no further information is available)

- Letter to Carpianus and Eusebian Canons: 2 pages of letter + 8 pages of canons

- Letter to Carpianus and Eusebian Canons: 3 pages of letter + 7 pages of canons



Four Gospels:

- List of Tituli

- Records for each Gospel (Opening lines and stichometry at the end as textparts?)

- Biography of each evangelist

- Note on the Eusebian sections for each Gospel and on the number of sections and chapters in other traditions

- List of the tituli of each Gospel

- Postscript on the date of origin (መለአ...)

- Other Postscript (ተፈጸመት...)

We also should have IDs for those works which are perceived as forming a unit in the Ethiopian tradition:

- LIT2705Introd for the entire introduction in its varying length and structure, referring to its single components by their individual IDs

- LIT1560Gospel for mss containing the Four Gospels and the Introduction

- a record for the Four Gospels without Introduction

- records for each Gospel including the Biography, note on the Eusebian sections, tituli and postscript (the biography of Matthew could then be referred to by its individual ID and be nested depending on its location in the ms either within the introduction or the Gospel of Matthew)

**Comment by abausi** [comment]
Dear Dorothea, many thanks, this is a wonderful contribution! I think that if we stay with Zuurmond we might have a sound reference point. This does not exhaust all possible cases and we have definitely further variations, that should be treated "ad hoc", implementing the options, in case they occur. But it is the best possible starting point at this time.
