### ISSUE TITLE
Clarification on Zotero guidelines

### ISSUE THREAD

**Issue by SusanneHummel** [SChAth/ScAthiop#462]
The names of all authors, editors and translators must be provided - in full and as they appear on the book. Make sure that you enter editors as editors and authors as authors, not e.g. editors as authors in the mask.

Is not clear, see Bezold and Marassini (authors or editors?)
@eu-genia

**Comment by eu-genia** [comment]
Bezold is correct (as entered by Dorothea), Marrassini (as entered by Solomon) is not quite: should be ed/tr, please correct

**Comment by PietroLiuzzo** [comment]
Just to clarify. I edited the marrassini record which was correct to your version and guidelines. We also updated it which makes me think you might be out of sync with your zotero

**Comment by SusanneHummel** [comment]
This is really strange because I corrected the entry (we did not edit it before) synchronized it. therefore I closed the issue. Obviously, I did not save (?) it correctly. Thanks!!!!

**Comment by eu-genia** [comment]
it appeared wrong when the issue was opened by Susanne. it is correct now. (Marrassini as editor and as translator, not as author)

**Comment by PietroLiuzzo** [comment]
you in my post was Eugenia...
