### ISSUE TITLE
list of types of additions

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#47]
Donation note, Ownership note (for both cases; 1. the book belongs to an individual, 2. the book belongs to an institution),
Purchase note, Acquisition note,
Admonition to (AM),
Land grant issued by __,
Foundation charter,
Genealogy of (the family of) ___
Scribe’s signature,
(Short) supplication (for __) [subscriptiones go in Other details],
Doxology,
Exhortation (to the brethren/ to commemorate __ / to celebrate __ / to learn the religion __ etc./ on the importance of commemorating __/ on what is useful for the soul), Invocation against __/ against those who __ (not very much different from condemnation, s. below),
Inventory of __,
Transaction note,
(Scribe’s) note on commencing the work,
Note on ordering of the copying,
Note on commissioning of the writing,
(Scribe’s) note on completing the writing, on assigning of land, on bequeathing__,
Record concerning reconciliation, litigation, land or property transaction, distribution of land [NB: “Record” can be used for a note of a documentary, official character],
(Scribe’s) entreat to God for help during __,
List of guarantors, Record concerning guarantors,
Commemorative notice on __ (mainly for the Synaxarion),
Condemnation of those who __ (e.g., “who stole the book”),
(Protective) prayer,
Qǝne-poem, Sälam-poem (s. Synaxarions), ˁArke-poem,
Stamp (hardly discernible, of the owning institution, of the church….),
Calendaric note
Unclear note.

**Comment by PietroLiuzzo** [comment]
https://mail.google.com/mail/ca/u/0/#inbox/1545dad19beeadc3?projector=1

**Comment by PietroLiuzzo** [comment]
rimato si o no

**Comment by PietroLiuzzo** [comment]
anche per work, per testi. attributo con valore boleano

**Comment by PietroLiuzzo** [comment]
@MassimoVilla @eu-genia @DenisNosnitsin1970  I wonder if, since the values in `<desc/>` are already quite consistent, we should not use here autocompletion templates from oxygen instead of a type list. or both... what do you think?

**Comment by eu-genia** [comment]
if when adding type to additions I get the dropdown list to select from I am happy with that - i am not sure I understand what the alternative is

the list can be made more formal (the brackets give the explanation for the users):

```
DonationNote
OwnershipNote
PurchaseNote
AcquisitionNote
Admonition
LandGrant
FoundationCharter
Genealogy
ScribalSignature
Supplication
Doxology
Exhortation
Invocation 
Inventory
TransactionNote
ScribalNoteCommencing
ScribalNoteOrdering
ScribalNoteCommissioning
ScribalNoteCompleting
ScribalNoteAssigningLand
ScribalNoteBequeathing
Record
RecordReconciliation
RecordLitigation
RecordTransaction
ScribalSupplication
GuarantorsList
RecordGuarantors
CommemorativeNote
Condemnation
ProtectivePrayer
PoemQǝne
PoemSalam
PoemArke
Stamp/Exlibris
CalendaricNote
Unclear
```

**Comment by PietroLiuzzo** [comment]
I can update the list, no problem. what I mean is that this list allows you to enter an attribute in the desc element, like in the following example.

````
 <item xml:id="a1" >
    <locus target="40vb" n="30"/>
   <desc type="AcquisitionNote">Acquisition note. <ref target="#a10"/></desc>
   <q xml:lang="gez">አጥረይክዋ፡ አነ፡ ገበረ፡ መድኅን፡ በመን{ፈ}ሰ፡ ጥበብ፡</q>
   <q xml:lang="en">I acquired it (this book), Gäbrä Mädḫən, through the spirit of wisdom</q>
</item>
````
but there are in the list values like this "(Scribe’s) entreat to God for help during ..." where perhaps you don't want to type this sentence but keep the content homogeneous. 
You would need to type this
````
<desc type="ScribalSupplication">(Scribe’s) entreat to God for help during ...</desc>
````
the content can be autocompleted with a template like the one for entering characters. you will start that up, and get together with the characters and the date, also this sentence, you select it and oXygen enters the sentence so you only need to fill the dots.

**Comment by eu-genia** [comment]
sounds good - assuming this will be a separate list from the one with the characters?

**Comment by PietroLiuzzo** [comment]
I think you get only one list for autocompletion in oxygen, according t the
editor, thats why currentdate is together  with the letters

On 5 May 2016 at 12:57, eu-genia <notifications@github.com> wrote:

> sounds good - assuming this will be a separate list from the one with the
> characters?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/SChAth/ScAthiop/issues/47#issuecomment-217135994>
>



-- 
Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by eu-genia** [comment]
then i am rather against, as I sometimes would scroll rather than type...
what do you think @MassimoVilla ?

**Comment by MassimoVilla** [comment]
I think we need to be able to select the characters from the list for autocompletion as quick as possible (sometimes we need three, four or more characters for one single content, and we have no choice other than the autocompletion). So, the list for autocompletion cannot become too crowded. If the list of additions merge with the character list we'd perhaps better create a set of values (even a bit long, as for key="NewTestament", "OldTestament", "Poetry", etc.) and type the addition title.

**Comment by MassimoVilla** [comment]
I don't think typing the addition title will make us lose so much time. The important thing is to have the addition list "on hand" the first time in order not to type invalid values, but it is not a big deal: the same happens with the values for key, i.e.: `<keywords>
                    <term key="OldTestament"/>
                </keywords>`

**Comment by eu-genia** [comment]
just as i thought, I agree with Massimo - we leave the template for characters only

**Comment by MassimoVilla** [comment]
I was thinking we can leave this issue open to point out any additional value we may need, for instance excerpts (from biblical readings, Mäṣḥafä gәbrä ḥəmamat, etc.). I do not find any appropriate value from the list we have now at disposal, and even if we did not list this typology in the Ethio-SPaRe working rules we actually happened to encounter excerpts here and there. Can we add Excerpt?

**Comment by PietroLiuzzo** [comment]
@MassimoVilla  sure! excerpt added!

**Comment by MassimoVilla** [comment]
OXygen tells me something is wrong with the element **additions**: `<additions><list><item xml:id="a1">
                                    <desc type="OwnershipNote"/>
                                    etc...</item></list></additions>`

_Element "additions" missing required attribute "xml:id"_, but each item listed within `<list/>` has an id. What is missing?

**Comment by PietroLiuzzo** [comment]
Over regulated. If you give an xml id to additions it should be ok, but I
will relax that
Il 07/Mag/2016 15:12, "MassimoVilla" <notifications@github.com> ha scritto:

**Comment by PietroLiuzzo** [comment]
the schema is now fixed to require xml:id only for item not for additions, please update schema repo and validate locally to see immediately the change.

**Comment by eu-genia** [comment]
i also need
"Letter"
thanks!

**Comment by PietroLiuzzo** [comment]
Please open a new issue if a new value is needed. 

see #70 and email exchange for improvement proposed on how to handle addition types
