### ISSUE TITLE
new record creation

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#470]
Depending on how complicated it would be, could it be possible to have one button everywhere on the app for the creation of new records of all kinds? So that one could choose after clicking on the button whether to create a manuscript, person, etc. record and would not always have to open the corresponding page, which can occasionally take time.

**Comment by eu-genia** [comment]
another matter with the new records: 
now the first list values for persons (e.g. in nationality and occupation) seem to be automatically selected and inserted into the xml file, should be avoided.

**Comment by PietroLiuzzo** [comment]
if another matter, please make another issue! :) I am moving this last comment to a new one now.

**Comment by PietroLiuzzo** [comment]
I have interpreted your "everywhere" as "on every page which does not have it already". you will also have to select BEFORE and not after you click on new, from the select menu. ok?

**Comment by thea-m** [comment]
Great!
