### ISSUE TITLE
add alternative transliteration?

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#472]
Is it possible to add two transliterations of one work title?
I was working on LIT2335serata, for which the EAE transliteration is Śǝrʿāta gǝbǝr, but there are several articles on this work using the transliteration Śǝrʿāta gǝbr, so that it seems reasonable to expect that someone would search for the work using the latter transliteration.

**Comment by eu-genia** [comment]
there are many words that can be transcribed with or without schwa...

**Comment by PietroLiuzzo** [comment]
this is currently correctly encoded and viewed as expected. I see no harm in adding and for sure if the information is not there it will not be found.

**Comment by thea-m** [comment]
good, then it can stay like this. Only the record's title is now shown on the app (logically) as "Śǝrʿāta gǝbǝrŚǝrʿāta gǝbr" - could only the first transcription be shown, or a slash between them?
