### ISSUE TITLE
location of Dillmann columns

### ISSUE THREAD

**Issue by abausi** [SChAth/ScAthiop#473]
It would be very useful to have the possibility of knowing exactly where we are, in which column, when searching the (Dillmann) Lexicon: columns are marked in the text file and it should be possible to retrieve the infromation in a relatively easy way

**Comment by PietroLiuzzo** [comment]
moved to dillmann issues

**Comment by AndreasEllwardt** [comment]
If a column break is inside the lemma, both column numbers should be shown, in order to understand correctly Dillmann's interior references without having to consult the Word-file.
