### ISSUE TITLE
qh shown as tofu on the app

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#478]

**Comment by PietroLiuzzo** [comment]
sorry, without example this is incomprehensible to me. what is qh?

**Comment by thea-m** [comment]
q̲ - nicely available in the code templates

**Comment by PietroLiuzzo** [comment]
one example record where this is found please?

**Comment by thea-m** [comment]
ETH1244BetAqa

**Comment by PietroLiuzzo** [comment]
could q&#x332; be used instead? I have updated the file like this and seems to work correctly. Please, let me know if you have any objections or close the issue. I have not found other instances of this letter being used anywhere else.

**Comment by thea-m** [comment]
great!
