### ISSUE TITLE
types for places

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#48]
from the 165 abbreviated values we need a new list and mappings from the old to the new list to update the value of place/@type

current list 

wär.

reg.

settl.

arch. site

shrine

pl.n.

town

reg

wär

mon.

church

lake

area

riv.

mt.

peninsula

mosque

district

valley

Gondär

state

port

rel. site

Aks.

ethn.

settl

ruba

church/mon.

zone

country

Gulf of

post

qušät

pass

is.

cataract

ōr

kingdom

agär

ʿAdwa

anc.

fort

spring

plateau

forest

adm.

gulf

gate Har.

emirate

Har.

railway station

plain

rock art site

strait

volcano

geog.

city

awr.

säfär

falls

amba

church of Yosṭinos

sultanate

sea

mt

awr.town

sanctuary

arch. area

water holes

cape/reg.

king

wr.

town/reg.

arch.

bibl.

rapids

hill

dere

col.

chapel

lit.

zoba

wādī

pl.n

arch.site

hills

dam

Asmära quarter

well

reg./ethn.

awr./town

lang.

site

kätäma

reg., state

mt., reg.

oasis

riv town

quarter Asmära

riv

Maale chiefdom

Jesuit residence

kingdom/port

sett.

Cape

palace

reg. Wällo

sub-province

prov.

chiefdom

garden

tabot

guta

gorge

town/prov.

battle of

rock-hewn church

state / reg

distr.

rel.

cave

Strait of

town, reg.

wadi

pol.

geol.

prefecture

station

gov.

bot.

mil.

cathedral

waterfalls

custom post

market

temple town

ford

temple

planet

fortress

farm

mts.

land

desert

hospital

caves

ziyāra

ling.

territory

reg.site

Gulf

sch.

residence

water falls

Dahlak

Mt.

battle

inscr.

qäbäle

penins.

gate

castle

rock site

Bay of

**Comment by eu-genia** [comment]
"DELETE FROM LIST" = erroneous entry, ID and file to be deleted
"---" = zero
"SPLIT" = two values to be separated

*************

wär. = waradā

reg. = region

settl. = settlement

arch. site = archaeologicalSite

shrine = shrine

pl.n. = placeName

town = town

reg = region

wär = waradā

mon. = monastery

church = church

lake = lake

area = area

riv. = river

mt. = mountain

peninsula = peninsula

mosque = mosque

district = district

valley = valley

Gondär = ---

state = state

port = port

rel. site = religiousSite

Aks. = ---

ethn. DELETE FROM LIST

settl = settlement

ruba DELETE FROM LIST

church/mon. = church + monastery (SPLIT)

zone = zone

country = country

Gulf of = gulf

post DELETE FROM LIST

qušät = qušat

pass = pass

is. = island

cataract = cataract

ōr DELETE FROM LIST

kingdom = kingdom

agär = region

ʿAdwa = ---

anc. DELETE FROM LIST

fort = fort

spring = spring

plateau = plateau

forest = forest

adm. = administrativeUnit

gulf = gulf

gate Har. DELETE FROM LIST

emirate = emirate

Har. DELETE FROM LIST

railway station = station

plain = plain

rock art site = rockSite

strait = strait

volcano = volcano

geog. DELETE FROM LIST

city = city

awr. = awraǧǧā

säfär = district

falls = falls

amba = mountain (ambā)

church of Yosṭinos = church

sultanate = sultanate

sea = sea

mt = mountain

awr.town = awraǧǧā + town (SPLIT)

sanctuary = religiousSite

arch. area = archaeologicalSite

water holes DELETE FROM LIST

cape/reg. = cape + region (SPLIT)

king DELETE FROM LIST

wr. DELETE FROM LIST

town/reg. = town + region (SPLIT)

arch. = archaeologicalSite

bibl. DELETE FROM LIST

rapids = falls

hill = mountain

dere = district

col. DELETE FROM LIST

chapel = chapel

lit. DELETE FROM LIST

zoba = zoba

wādī = wādī

pl.n = placeName

arch.site = archaeologicalSite

hills = mountain

dam = dam

Asmära quarter = quarter

well = well

reg./ethn. = region

awr./town = awraǧǧā + town (SPLIT)

lang. DELETE FROM LIST

site = placeName

kätäma = katamā

reg., state = region + state (SPLIT)

mt., reg. = mountain + region (SPLIT)

oasis = oasis

riv town = river + town (SPLIT)

quarter Asmära = quarter

riv = river

Maale chiefdom DELETE FROM LIST

Jesuit residence = placeName

kingdom/port = kingdom + port (SPLIT)

sett. = settlement

Cape = cape

palace DELETE FROM LIST

reg. Wällo = region

sub-province = district

prov. = province

chiefdom DELETE FROM LIST

garden DELETE FROM LIST

tabot DELETE FROM LIST

guta DELETE FROM LIST

gorge = gorge

town/prov. = town + province (SPLIT)

battle of = placeName

rock-hewn church = church

state / reg = state + region (SPLIT)

distr. = district

rel. DELETE FROM LIST

cave = cave

Strait of = strait

town, reg. = town + region (SPLIT)

wadi = wādī

pol. DELETE FROM LIST

geol. DELETE FROM LIST

prefecture DELETE FROM LIST

station = station

gov. DELETE FROM LIST

bot. DELETE FROM LIST

mil. DELETE FROM LIST

cathedral = church

waterfalls = falls

custom post = post

market = market

temple town = town

ford DELETE FROM LIST

temple = temple

planet = planet

fortress = fort

farm = farm

mts. = mountain

land = region

desert = desert

hospital DELETE FROM LIST

caves = cave

ziyāra = religiousSite

ling. DELETE FROM LIST

territory = region

reg.site = region + site (SPLIT)

Gulf = gulf

sch. DELETE FROM LIST

residence = placeName

water falls = falls

Dahlak = ---

Mt. = mountain

battle = placeName

inscr. DELETE FROM LIST

qäbäle = qabale

penins. = peninsula

gate DELETE FROM LIST

castle = castle

rock site = rockSite

Bay of = bay

*************************

to add:

ṭabiya
dabr
gadam
gaṭar
