### ISSUE TITLE
infer ayn and alef in search for transcription with words starting with vowel

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#480]
from @thea-m 
searching for a word starting with a vowel should also point to results ʾ+vowel, if possible
"yekunno amlak" should point to Yǝkunno ʾAmlāk

**Comment by PietroLiuzzo** [comment]
http://betamasaheft.aai.uni-hamburg.de/search.html?query=yekunno+amlak
returns the expected result. please close if ok.

**Comment by eu-genia** [comment]
it should also work the other way around. searching for "enda" should get also "ʾƎndā" 
and if possible search for "mikael" should get "Mikāʾel"

**Comment by PietroLiuzzo** [comment]
the bahaviour has long been as follows:

enda already searches for 	enda ʾenda ʿenda ǝnda ēnda and ignores diacritics;
mikael  for mikael mikaǝl mikaēl and ignores diacritics ;
Mikāʾel for 	Mikāʾel Mikāʾǝl Mikāʾēl Mikāʿel Mikāʿǝl Mikāʿēl Mikāel Mikāǝl Mikāēl and ignores diacritics.

without a more precise rule I can't simply assume any vowel could be preceded by alef or ayn. 

If you could please specify a more precise rule I can add it. e.g. could it be when two vowels follow each other add alef or ayn in between?? it is also true that you could already make your search fuzzy.

**Comment by PietroLiuzzo** [comment]
this issue is also sorted by the possibility to run a fuzzy search, which will give the wanted results among others.

**Comment by PietroLiuzzo** [comment]
please, try http://betamasaheft.aai.uni-hamburg.de/search.html?query=enda
and http://betamasaheft.aai.uni-hamburg.de/search.html?query=enda~0.9
