### ISSUE TITLE
transliteration of names containing prepositions

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#482]
Does everyone agree with the following rule from our guidelines?

Prepositions are always separated by the following word by a hyphen. In the case of names, both the preposition and the following word are written with a capital letter:

kāhǝnāt wa-diyāqonāt 

Ba-Ḫayla Mikāʾel and not Baḫayla Mikāʾel

**Comment by abausi** [comment]
I think it would be more correct to give the name as it is, without any hyphen, for whatever preposition, genitive particle za- etc. So in this case Baḫayla Mikāʾel, and then Zamikāʾel ʾAragāwi (not Za-Mikāʾel ʾAragāwi), Naʾakkwǝto Laʾab (not La-ʾAb) etc. We are not tokenizing the names for a linguistic analysis, we are only giving them as they are

**Comment by thea-m** [comment]
thank you, I updated the guidelines
