### ISSUE TITLE
persons record

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#483]
I assumed the named entered in the form for the creation of new records would have been in geez, which does not seam to be the case. the example below produced by the form gives a blank in the preview because the desired element is there but is empty.

````xml 
<persName xml:lang="gez" xml:id="n1">Niqodimos</persName>
<persName xml:lang="gez" type="normalized" corresp="#n1"/>
````

from now on, the output of the app will be instead

````xml 
<persName xml:lang="gez" xml:id="n1"></persName>
<persName xml:lang="gez" type="normalized" corresp="#n1">Niqodimos</perName
````

Please could you confirm that this is ok? i.e. that in most cases you enter a transcription rather than the geez name? thanks

**Comment by thea-m** [comment]
I have become used quite well to entering the names in Geez. Anyway one has still to open the record and complete the information, so it makes no difference to me, transcriptions are fine.
