### ISSUE TITLE
element not visualized

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#486]
In LIT1882MarkGo, 
```xml
<editionStmt>
            <p>Digital text based on  <bibl><ptr target="bm:Zuurmond1989EvangeliumMarc"/></bibl>.</p>
         </editionStmt>
```
is not visualized at all in the app, if I see it correctly
(There was a problem with the zotero tag, but I corrected it)

**Comment by PietroLiuzzo** [comment]
This information is visualized under text 
http://betamasaheft.aai.uni-hamburg.de/text/LIT1882MarkGo

**Comment by thea-m** [comment]
I see! But for LIT4275ChronAmdS for instance, the information is viusalized under general description, though the encoding seems the same to me
