### ISSUE TITLE
referring to ff. without folio number

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#487]
In the case of manuscripts with leafs which have no folio number, should our locus indication follow the existing folio numbers or should we refer to these leafs by a numeration which differs from the existing foliation? 
For instance, BDLaethc2:  two folios (between f.66 and f.67) are so badly mutilated that only small corners containing a few fragments of letters are preserved. These two folios were not taken into account for the foliation. As the catalogue clearly states which text parts were originally contained by these two folios, I would like to be able to point to them. Should I point to `<locus target="#67">` and `<locus target="#68"> `and then shift the numeration of all ff. after them, so that the current f. 67 becomes f. 69? Or should I describe the situation and keep all loci in accordance to the foliation and Ullendorff's description? (This is what I have done initially in my record)

**Comment by DenisNosnitsin1970** [comment]
Better without shifting the existing foliation. You can assign to the leaves numbers by your own (a bcd, i, ii, iii, iv etc.).

**Comment by thea-m** [comment]
Thank you!
@PietroLiuzzo would it be possible to point to such an individual folio number? i.e., something like `<locus target="#66i">`?
(Maybe this is too much fuss - the leaves in question contain no own msitem, so my current description without `<locus>` could be enough)

**Comment by PietroLiuzzo** [comment]
please encode it in the correct way as suggested by @DenisNosnitsin1970  and we will then check if everthing works. a minimum error will be the inability to correctly calculate the collation.

**Comment by thea-m** [comment]
I updated BDLaethc2 - seems to work (no detailed information on collation is available here anyway)

**Comment by PietroLiuzzo** [comment]
please update guidelines and close issue
