### ISSUE TITLE
legends

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#489]
We could maybe briefly mention in the guidelines how legends of decorations should be encoded.
@MassimoVilla and I copied them in `<desc>` inside the corresponding `<decoNote>`:
```xml
       <decoNote type="engraving" xml:id="d2">
                          <locus target="#125v"/>
                          <desc>
                              <persName ref="PRS11251Erasmus">Saint Erasmus</persName> tortured and <persName ref="PRS11252Nicholas">saint Nicholas</persName>. 
                             Legend: <q xml:lang="gez">ኤጲስ፡ ቆጶስ፡ ዘሮማ፡</q>
                           </desc>
                       </decoNote>
```
Is it fine like this?

**Comment by PietroLiuzzo** [comment]
I have updated the guidelines to reflect this usage. https://github.com/SChAth/ScAthiop/wiki/guidelines#decoration-description
you will notice I have removed Legend: as this can be added by the transformation sparing you time and possible errors (Legend : , Legend, Legend etc.)
if ok, please close

**Comment by thea-m** [comment]
thank you
