### ISSUE TITLE
space before tagged entities 

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#492]
It seems that a space is inserted automatically on the app before a `<persName>` or `<placeName>` - this is a bit disrupting when the tagging occurs in a text, where `ዘ<persName ref="PRS5695John">ዮሓንስ፡</persName>` then becomes  ዘ ዮሓንስ፡

**Comment by PietroLiuzzo** [comment]
This should now be corrected. It was a problem in the construction of the links to the Dillmann app. 
I have also fixed a bit that, now it will launch a fuzzy search instead of a normal one and will not take in ፡or ።
