### ISSUE TITLE
link to MSS UM-045 etc.

### ISSUE THREAD

**Issue by abausi** [SChAth/ScAthiop#494]
I tried to open the links to some of the UM-MSS (the several bundles containing, among other texts, also collection of homilies from UM, such as UM-045, U-046 etc.), but I have got an error message for most of them: is all OK?

**Comment by PietroLiuzzo** [comment]
yes, ESum045 and many other ES manuscript records have been automatically imported last year, but only very few have been fixed after this process. in the case of ESum045 the problem is that there are empty tags breaking the xslt transformation for dimensions.

**Comment by PietroLiuzzo** [comment]
there was also an error in the use of the id, inherited from ethiospare, i.e. INS0017UQ instead of INS0017UM
