### ISSUE TITLE
<gap> not visualized

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#499]
`<gap>` seems not to be visualized on the app? (at least, with @reason "lost" and "ellipsis") - didn't we use to have [...] with the reason indicated on hovering?

**Comment by PietroLiuzzo** [comment]
there is no support for visualization of lost and ellipsis, because there is no specification. how should they look like in an edition? like omitted and illegible? @abausi is this distinction made in print editions of ethiopic texts? how should different gap types be visualized?

**Comment by PietroLiuzzo** [comment]
I have mapped these definitions to TEI and updated  https://github.com/SChAth/ScAthiop/wiki/guidelines#in-text
there will also be a page printing this out for users in BM.
