### ISSUE TITLE
citations in text

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#50]
how do we mark up Mark 1,1-5 and generally canonical references to edited texts?

`<ref cRef="urn:cts:greekLit:tlg0031.tlg002.perseus-lat1:1.1-5">`

CTS urn enable direct pointing to specified portion of text.

**Comment by eu-genia** [comment]
there has been a long long discussion on the TEI list as to quoting biblical texts and whether the canonical references http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SACR always work.

maybe a useful post in case you do not have it

> In the Saint Patrick's Confessio Project (confessio.ie) several thousand biblical references from an elaborate apparatus biblicus and other annotations have been encoded in the following manner, 
> 
> e.g.,
> <ref type="biblical" cRef="LXX" corresp="Ps49,15">Ps 49,15</ref>
> 
> or
> <ref type="biblical" cRef="VULG" corresp="Ps78,49">Ps 77,49</ref>
> 
> or
> <ref type="biblical" cRef="VULG" corresp="2Chr29,10">2 Par 29,10</ref>
> 
> or
> <ref type="biblical" cRef="sinaiticus" corresp="2Cor3,2-3">א</ref>
> 
> (abusing, not without reason, @cRef for indicating what is more likely to by attributed with @subtype, and slightly abusing @corresp for indicating what is more likley to be attributed with @cRef)
> 
> The TEI files are here:
> http://www.confessio.ie/more/downloads#
> 
> We had to deal with a great variety of bible versions; see:
> http://www.confessio.ie/more/auxiliary#2
> 
> For the web presentation all biblical references are transformed into hyperlinks pointing to online versions as provided by BibelServer (Vulgate, Septuagint, Hebrew Old Testament, German/Einheitsübersetzung, English/King James Version, Portugues/O Livro, Italian/Nuova Riveduta etc. ) or Perseus (Apocrypha) or to the list of abbreviations for further details.
> Cf. http://www.confessio.ie/etexts/confessio_latin#01
> 
> All scripts (and source files already available) are planned to be freely provided on Github before too long. 

Another one

**Comment by PietroLiuzzo** [comment]
sure, that's where the cRef suggestion was taken, but I suspect there are
not only biblical citations and perhaps we want to use a urn structure
which allows us to not just report the citation but also to point to the
passage.

On 3 May 2016 at 18:22, eu-genia <notifications@github.com> wrote:

> there has been a long long discussion on the TEI list as to quoting
> biblical texts and whether the canonical references
> http://www.tei-c.org/release/doc/tei-p5-doc/en/html/SA.html#SACR always
> work.
>
> maybe a useful post in case you do not have it
>
> In the Saint Patrick's Confessio Project (confessio.ie) several thousand
> biblical references from an elaborate apparatus biblicus and other
> annotations have been encoded in the following manner,
>
> e.g.,
> Ps 49,15
>
> or
> Ps 77,49
>
> or
> 2 Par 29,10
>
> or
> א
>
> (abusing, not without reason, @cRef <https://github.com/cRef> for
> indicating what is more likely to by attributed with @subtype, and slightly
> abusing @corresp for indicating what is more likley to be attributed with
> @cRef <https://github.com/cRef>)
>
> The TEI files are here:
> http://www.confessio.ie/more/downloads#
>
> We had to deal with a great variety of bible versions; see:
> http://www.confessio.ie/more/auxiliary#2
>
> For the web presentation all biblical references are transformed into
> hyperlinks pointing to online versions as provided by BibelServer (Vulgate,
> Septuagint, Hebrew Old Testament, German/Einheitsübersetzung, English/King
> James Version, Portugues/O Livro, Italian/Nuova Riveduta etc. ) or Perseus
> (Apocrypha) or to the list of abbreviations for further details.
> Cf. http://www.confessio.ie/etexts/confessio_latin#01
>
> All scripts (and source files already available) are planned to be freely
> provided on Github before too long.
>
> Another one
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SChAth/ScAthiop/issues/50#issuecomment-216602528>
>



-- 
Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by eu-genia** [comment]
we have not gotten yet to the many issues connected with editing texts (as this is when we shall need this sort of mark up). or do we already need this for ms descriptions? we have not had a discussion yet as to what is canonical for us... and in what language... Greek is in a somewhat different position there

**Comment by PietroLiuzzo** [comment]
since this issue has emerged and there are already viable options perhaps we can already take this simple decision. There are at least biblical citations in the manuscript descriptions and we could extend our behavior for them to any "canonicized" citation of latin, greek, etc. literature.

@MassimoVilla  had already some of this. using CTS urn we could then popup the exact bit of text of the cited work directly

````
<p>Excerpt from <title corresp="LIT1882MarkGo">Mark</title> <ref target="urn:cts:greekLit:tlg0031.tlg002.perseus-lat1:1.1-5">1, 1-5</ref></p>
```` 
the urn is taken from perseus catalogue which exposes them tlg0031 is the work, tlg002 the text, perseus-lat1 the version (in this example I am linking to their latin text) than after column we have the passage as in a normal citation. - is for ranges but one could point to the chapter only, as to a single word or string. 

When we will come to texts I would like to suggest to expose them in the same way, so that from a urn like

     urn:dts:ethiopianLit:bm4428.bm1252:1.1 

I can get to chapter 1 ot book 1 of the _Confessio Claudii_ a task which is certainly for the future!

**Comment by PietroLiuzzo** [comment]
DTS work continues and this method would be fine and very good in terms of support by an external api service implementation.

**Comment by PietroLiuzzo** [comment]
allowed cRef in schema to take urn value from perseus
