### ISSUE TITLE
blank pages

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#503]
blank leaves are indicated under `<extent>` - should blank pages (i.e. on a f. where there is text on the recto but not on the verso ) also be indicated here, or is this information not relevant?

**Comment by DenisNosnitsin1970** [comment]
If they are indicated in the catalogue, it is better to take over this information (even though, I did not see yet any explanation of a blank folio. If the folio has not text, but, for instance, two or three words 
of a recent crude secondary writing, is it still blank? Or blank folio should really be blank, as it is defined?)

**Comment by thea-m** [comment]
Ullendorff actually notes this relatively consistently, so that I added in <extent> only  instances of really blank folios
