### ISSUE TITLE
space after locus and ref

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#504]
A space is always inserted on the app after `<locus>` and `<ref>` - could this be removed?
`<ref type="work" corresp="LIT4300PrayerAzariah"/>,` becomes "Prayer of Azariah and the Song of the Three Holy Children  (work) ,"

**Comment by PietroLiuzzo** [comment]
should be solved, please check and close or report other examples

**Comment by thea-m** [comment]
thank you
