### ISSUE TITLE
relation for antigraph of printed work

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#509]
can we add a relation IsAntigraphOf (i see nothing corresponding in the schema), to describe the relation between a ms and a printed work (zotero tag)?

**Comment by PietroLiuzzo** [comment]
have you checked saws?

**Comment by thea-m** [comment]
would this be isAncestorOf?

**Comment by PietroLiuzzo** [comment]
I have added isAntigraphOf
