### ISSUE TITLE
are values of @condition printed in bold on purpose?

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#510]

**Comment by PietroLiuzzo** [comment]
in which element? what is in bold? it is for sure done "on purpose". let me know how you would like that this is printed oterways. could you please point to an example?

**Comment by thea-m** [comment]
I'm sorry, I had meant `<condition key="deficient"> ` - deficient, good etc. are always bold (for example, in BDLaethc2). Regular would seem fine to me, but if you prefer the bold, please keep it!
