### ISSUE TITLE
problems with BDLaethe1 in the app

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#511]
in BDLaethe1, ms_i2.11 to ms_i2.14 don't expand when clicking on them
also, for ms_i2.1 the title  `<title type="complete" ref="LIT1960Mashaf#Prayers"/>` is rendered as "Maṣḥafa qǝddāse, div Prayers " - why is "div" stated here? This is never printed for the other msitems

**Comment by PietroLiuzzo** [comment]
because probably in the other items you don't point to an anchor assigned to a div element in the Work record.

**Comment by PietroLiuzzo** [comment]
I have removed the name of the element where the id appears and fixed the linking in the msItems accordion
