### ISSUE TITLE
<sic> inside <persName>

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#513]
is it possibly to mark up a `<persName>` with `<sic>`? I have this case in BDLaethe4:
```xml
   <q xml:lang="gez">ዛቲ፡ ገድለ፡ ክርስቶስ፡ ሠምራ፡  ዘ<persName ref="PRS11682WaldaT" role="owner">
<choice><sic resp="PRS9622Ullendor">ወለደ፡ ትንኤሣ፡</sic> <corr resp="DR">ወልደ፡ ትንሣኤ፡</corr></choice></persName></q>
```
which is printed on the app like this: 
 ዛቲ፡ ገድለ፡ ክርስቶስ፡ ሠምራ፡ ዘWalda Tǝnśāʾe (owner)

**Comment by PietroLiuzzo** [comment]
it should be displaying better now, but unfortunately I cannot switch at the moment the resp in the popover on click. i.e. you can click the word to see the incorrect version but it will not display ullendorff
