### ISSUE TITLE
standardizing the names of common saints

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#518]
I have noticed that throughout our records, we have used different nomenclatures when referring to the names of Saints and Biblical figures. It would be preferable in my opinion if they were standardized (and in my experience, these names are among the first users might search for when trying out the website, so it would be nice if they could check what they should actually enter into the search to get the expected results). 
This pertains of course especially to the person records, but these names are also often mentioned in descriptions and in the titles of works ("Hymn to XY" and similar cases)
 
- should we use the Gəʿəz or the English version of the name? what should be n1 in the person record?
- we have used Saint, saint, St. and St and simply the name - what is the standard?
- when referring to Mary in the title of a work, we also have used a great variety of titles and names - Mary, Māryām, the Virgin, Our Lady etc. (often copied from the catalogues) - should this also be standardized?

**Comment by eu-genia** [comment]
for international saints the main name should clearly be the English one

we had, however, discussed, and agreed, that if the English is the direct correspondence of Ge'ez, they can both be in n1, and English marked as "main" and thus printed as the title (for the works, but the same should work for all other types)

as in Mary

`<persName xml:lang="gez" xml:id="n1"> ማርያም፡</persName>

<persName xml:lang="gez" type="normalized" corresp="#n1"> Māryām</persName>

<persName xml:lang="en" type="main" corresp="#n1"> Mary</persName>

<persName xml:id="Virgin">Holy Virgin</persName>

<persName xml:lang="gez" corresp="#Virgin">ድንግል፡</persName>

<persName xml:lang="gez" type="normalized" corresp="#Virgin">Dǝngǝl</persName>

<persName xml:id="n3">Madonna</persName>


-<persName xml:lang="gez" xml:id="Zion">

<addName type="epithet">ጽዮን፡</addName>

</persName>

<persName xml:lang="gez" corresp="#Zion">Ṣǝyon</persName>

<persName xml:lang="en" corresp="#Zion">Zion</persName>


-<persName xml:lang="gez" xml:id="Pearl">

<addName type="epithet">ባሕርይ፡</addName>

</persName>

<persName xml:lang="gez" corresp="#Pearl">Bāḥrǝy</persName>

<persName xml:lang="en" corresp="#Pearl">Pearl</persName>


-<persName xml:lang="gr" xml:id="Theotokos">

<addName type="epithet">Θεοτόκος</addName>

</persName>

<persName xml:lang="gez" corresp="#Theotokos">Theotokos</persName>

<persName xml:lang="en" corresp="#Theotokos">God-Bearer</persName>

<persName xml:lang="lat" corresp="#Theotokos">Mater Dei</persName>`

As long as the reference is correct you can use whichever name/epithet you have in your text (then use PRS6819#Virgin to refer to the Virgin etc.)

Saint should be Saint or St (capital, no dot in the abbreviation); we can also think whether we want "St" always printed in front of the name if the occupation (?) is specified as Saint or St

**Comment by thea-m** [comment]
I updated the guidelines regarding English names and "Saint".
The use of "main" in person records has been nowhere stated, therefore it is not yet visualized. Could you add this, @PietroLiuzzo ?
