### ISSUE TITLE
Checking of export results from Ethiospare files

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#52]
manuscript records have been transformed. 
Some revision of this result should be done to see if there are other things which can be automated or these files can be taken and carried over to the work in progress data.

**Comment by PietroLiuzzo** [comment]
https://github.com/SChAth/ScAthiop/tree/master/catalogueMyCore/valid

**Comment by PietroLiuzzo** [comment]
beware, most of these are NOT valid!

**Comment by PietroLiuzzo** [comment]
from email 

nelle descrizioni di mss trasformati da DomLib sono andati persi alcuni elementi.
 
P.e.
Number of columns
Number of lines
 
Copyist / scribe :
(comment) :
 
e pure
 
Colophon: translation / details
Additions: short content/ translation/details


(il colofone etiopico c’è ma non la traduzione)
 
lo stesso vale per le addizioni:


1)
Short Content :	
Fol. 15rb: Supplication for the commissioners and the scribe.

Addition :	
Fol. 15rb: ኦአኃውየ፡ ደቂቀ፡ ዛቲ፡ መቅደስ፡ ኢትርስኡነ፡ በጊዜ፡ አንበብክምዋ፡ ለዛቲ፡ መጽሐፍ፡ ለአግብርቲክሙ፡ ተስፋ፡ ጽዮን፡ መርደ፡ ክዮስ፡ ግደ፡ ማርያም፡ ወለጸሐፊሐ፡ ኃጥእ፡ ዘድንግል፡፡

Translation :	
Details :	Written in the main hand. 
The note mentions the names Täsfa Ṣəyon, Märdä Kəyos, Gədä Maryam and the name of the scribe zä-Dəngəl.
 
cioè ci vorrebbe il <desc> o il <title>, il testo etiopico , la traduzione (qui non c’è ma altrove sì) e poi un <note> – ora abbiamo solo il testo etiopico



“all data for fol. 4r” sta nel posto sbagliato


E se si aggiunge un po’ di data mining ancora si potrebbe avere una traduzione automatica della riga sotto Ruling che comincia con “Ruling pattern”?
Cioè dal
Ruling :	Pricking and ruling are visible. 
Ruling pattern: 1A-1A-1A1A/0-0/0-0/C.

**Comment by PietroLiuzzo** [comment]
from email


Abbreviations :	ፍ፡ for ፍቱሐ፡ (e.g., fols. 36ra, 36vb, 39ra) 
ይ፡ ሕ፡ for ይበል፡ ሕዝብ፡ (fol. 40va) 
ይ፡ ካ፡ for ይበል፡ ካሕን፡ (e.g., fols. 60vb, 61va, 68vb) 
ይ፡ ዲ፡ for ይበል፡ ዲያቆን፡ (e.g., fols. 60vb, 61rb, 68vb)
 
forse anche i campi che qui non sono riempiti devo controllare altri mss...

**Comment by PietroLiuzzo** [comment]
from email 

mancano anche le corrispettive per i campi che nel domlib erano si/no per filtrare più facilmente:
 
p.e. nel MR-023
 
Dated :	no
Palimpsest :	no
Composite :	no
Fragment :	no
Illuminated :	no
Additiones :	yes
Musical notation :	no
Autograph :	no
Printed part :	no
Incomplete :	no
Colophon :	yes
Restoration :	none

certo forse una parte sono superflui (come colophon e additiones, tanto si vede, e composite adesso si riconoscerebbe dai mspart multipli) ma p.e. “dated” è una categoria importante. la <date> della descrizione in questo caso è una “conjecture”.
 
********************
 
sempre controllando il MR-023:
msitem i1 (lo stesso chiaramente in tutti gli altri mss e msitem, qui uso MR-023 per illustrazione)
 
nel xml ora abbiamo
<incipit defective="false">
   <foreign xml:lang="en">And a big persecution happened in the Church of Christ…</foreign>
</incipit>
 
nell’originale però
-> Incipit :	
Fol. 2r: በስመ፡ʼʼ… ንጽሕፍ᎓ መጸሐፈ[sic]፡ ገድሉ፡ ለቅዱስ፡ ቂርቆስ᎓ ሰማዕት፡ወእሙ፡ ኢየሉጣ፡ ወካልአንሂ፡ ፻፻ወ፲፻ወ፬፻፴ወ፬ሰማዕት፡ እለ፡ ተከለሉ፡ በመዋዕለ፡ እስክንድሮስ፡ መኰንን። ጸሎቶሙ፡ወበረከቶሙ፡ የሀሉ፡ ምስለ፡ ኵልነ፡ ሰማዒ፡ ወአንባቢ፡ ለዓለመ፡ ዓለም፡ አሜ[ን፡] ወኮነ፡ ስደት፡ ዓቢይ፡ በቤተ፡ ክርስቲያን፡ ዘክርስቶስ፡…

translation :	
Fol. 2r: In the name of the Father and of the Son and of the Holy Spirit, one God. We write the book of the life of St. Cyricus, martyr, and of his mother Julitta  and of other 11,434 martyrs who were crowned during the time of the governor Alexander. May their prayer and blessing be with each of us, listener and reader.  Forever and ever. Amen.

And a big persecution happened in the Church of Christ…

 
cioè in etiopico, poi tradzione, con locus, rimasta solo l’ultima riga della traduzione
 
******************
<explicit defective="false">
   <foreign xml:lang="en"/>
</explicit>
 
vs.
 
-> Explicit :	
Fol. 43r, l.2 – l.11: ...ወሀሎ፡ ቅዱስ፡ ቂርቆስ፡ ወትረ: ይቀውም፡ በየማነ፡ መንበሩ፡ ለእግዚአብሔር፡ ወይተ[sic]ነብል፡ በእንቲአነ፡ ኀ[በ]፡ እግዚአብሔር፡ ንጉሥ፡ ዘዓለም፨ ወለዓለመ፡ ዓለም፡ አሜን፡ ወአሜን። ለይኩን፡ ለይኩን፡፨ በእንተ፡ ሥጋሁ፡ ወደሙ፡ ለክርስቶስ፡ ለይኩን፨

translation :	
Fol. 43r, l.2 – l.11: ... And St. Cyricus is always present, he stands on the right of the throne of the Lord and he intercedes for us to the Lord, King of the World. Forever and ever.  Amen. So be it, so be it. For the sake of body and blood of Christ, so be it.

 
sparito tutto

******************
come già notato
 
<msItem xml:id="coloph1" defective="false">
   <colophon>
      <locus/>justify;"&gt;Fol. 43r, l.13: መጽሐፈ፡ ገድሉ፡ ለቅዱስ፡ ቂርቆስ፡ ሰማዕት፡ ወእሙ፡ ኢየሉጣ፡ ዘሰሐሥሕሌ፡ ወ[ሐ]ብፀሊም፡ ዘተጽሕፈት፡ [ዘመ]ነ፡ ዮሐንስ፡ ወንጌላዊ፡ ወንጉሥነ፡ ዮሐንስ፡ ወጳጳጳስነ[sic]፡ አትናቴዎስ። [fol. 43v]ወለዓለመ፡ ዓለም። ታቦቱ፡ ካህናቱ፡ ዘመስጥሕ፡ ወጸሃፊሃ፡ አቡነ፡ ወልደ፡ ሙሴ።</colophon>
</msItem>
 
Colophon: 1
Content :	
Fol. 43r, l.13: መጽሐፈ፡ ገድሉ፡ ለቅዱስ፡ ቂርቆስ፡ ሰማዕት፡ ወእሙ፡ ኢየሉጣ፡ ዘሰሐሥሕሌ፡ ወ[ሐ]ብፀሊም፡ ዘተጽሕፈት፡ [ዘመ]ነ፡ ዮሐንስ፡ ወንጌላዊ፡ ወንጉሥነ፡ ዮሐንስ፡ ወጳጳጳስነ[sic]፡ አትናቴዎስ። [fol. 43v]ወለዓለመ፡ ዓለም። ታቦቱ፡ ካህናቱ፡ ዘመስጥሕ፡ ወጸሃፊሃ፡ አቡነ፡ ወልደ፡ ሙሴ።

Translation :	
Fol. 43r, l.13: The book of the life of St. Cyricus, martyr, and his mother Julitta, (is) of Säḥaśәḥle (and)  [Ḥa]bәḍälim, which was written in the time of  Yoḥannәs the Evangelist, and our  King Yoḥannәs and our Metropolitan ˀAtnatewos. Forever and ever. The tabot, the clergy (are) of Mäsṭәḥ. And its scribe was ˀabunä Wäldä Muse.

Details :

sparita la traduzione
 
***************
<additions>
                     <list>
                        <item xml:id="a1">
                           <locus target="#00" n="#"/>
                           <q xml:lang="gez"/>
                           <q xml:lang="en"/>
                           <p part="N"/>
                        </item>
                        <item xml:id="e1">- Crude recent notes in pen and in pencil throughout the manuscript, above and below the text (e.g. fols.: 1rv; 2r; 4r; 4v; 7r; 9v; 13v; 15v; 16r; 25v; 33v; 38v; 43rv; 44rv; 45rv).&#xD;
Crude drawings in pencil, mixed with crude notes, on fol. 45rv.</item>
                     </list>
                  </additions>
 
 
Additiones :
 
1)
Short Content :	
Fol. 1v: Short inventary of the church utensils (?).

Addition :	
Fol. 1v: መጽሐፈ፡ ግምጃ፡ ፃሕለ፡ ጽዋዕ፡ ዕርፈ፡ ዘመስቀል᎓ ቅራን᎓ መስቀል᎓ የሐብጸሊም᎓… የስሐሥሕሌ᎓… ቂርቆስ

Translation :	
Details :	Half-erased, mentioning Ḥabәḍälim and Säḥaśәḥle.
 
Varia :	- Crude recent notes in pen and in pencil throughout the manuscript, above and below the text (e.g. fols.: 1rv; 2r; 4r; 4v; 7r; 9v; 13v; 15v; 16r; 25v; 33v; 38v; 43rv; 44rv; 45rv). 
Crude drawings in pencil, mixed with crude notes, on fol. 45rv.
 
Quire marks :	no
 
Finding aids :	no
 
cioè sparito tutto trannè “varia” che sarebbero a2 e a3, a1 sparito completamente

**Comment by PietroLiuzzo** [comment]
translation in colophon fixed

**Comment by PietroLiuzzo** [comment]
copyist fixed (miss spelled element name)

**Comment by PietroLiuzzo** [comment]
additional/det fixed. BUT sometimes contains hardcoded <p>

**Comment by PietroLiuzzo** [comment]
layout desc for writtenLines and other info had to be split in multiple layout under layoutDesc.

**Comment by PietroLiuzzo** [comment]
added more analysis (reliable on the basis of contents) for ruling and pricking

**Comment by PietroLiuzzo** [comment]
@eu-genia abbreviations are usually encoded in the text. I have added a list with type abbreviation in the primary handNote and added abbr around the abbreviation and expand around the expanded world.

**Comment by PietroLiuzzo** [comment]
please, tell me if this is correct

Dated : no
can we use the info contained in origDate directly?

Palimpsest : no


Composite : no
we can get this from the presence/absence of more msPart

Fragment : no
we can get this from the presence/absence of msFrag 

Illuminated : no
we get this from presense/absence of decoration (or specific decoration types)
Additiones : yes
Musical notation : no
Autograph : no
Printed part : no
Incomplete : no
Colophon : yes
Restoration : none

**Comment by PietroLiuzzo** [comment]
incipit and explicit problems are again due to inconsistent presence of hardcoded html

**Comment by PietroLiuzzo** [comment]
in additions, the content of varia is encoded as extra in the tei file and will need to be changed by hand if incorrect.

**Comment by eu-genia** [comment]
everything can be corrected by hand if i can see it - main things is that no information gets lost
we do not work with texts at least for the moment so the abbreviations used by the scribe are treated as a feature of the scribal practice/manuscript making

**Comment by eu-genia** [comment]
as for dating: it is only when date evidence=manuscript that it is dated, often date evidence=conjecture and then it is not dated even if we know the date

**Comment by PietroLiuzzo** [comment]
is the list of abbreviations ok for you?

````
 <list type="abbreviations">
                           <item>
                              <abbr>ፍ፡</abbr> for <expan>ፍቱሐ፡ </expan> (e.g., fols. 36ra, 36vb, 39ra)</item>
                           <item>
                              <abbr>ይ፡ ሕ፡</abbr> for <expan>ይበል፡ ሕዝብ፡ </expan> (fol. 40va)</item>
                           <item>
                              <abbr>ይ፡ ካ፡</abbr> for <expan>ይበል፡ ካሕን፡ </expan> (e.g., fols. 60vb, 61va, 68vb)</item>
                           <item>
                              <abbr>ይ፡ ዲ፡</abbr> for <expan>ይበል፡ ዲያቆን፡ </expan> (e.g., fols. 60vb, 61rb, 68vb)</item>
                        </list>
````

**Comment by eu-genia** [comment]
perfect

**Comment by PietroLiuzzo** [comment]
I have uploaded this changes. I bet there are several other things to fix. please, have a look at some more files and let me know.

**Comment by eu-genia** [comment]
non c'è l'informazione sull'"owner"
(p.e. my-014 "Owner :	Gäbrä Mäsqäl Nǝguse (s. Additio 1).")


> Dated : no
> can we use the info contained in origDate directly?
> 

no we cannot: origDate is our conjecture, dated means the manuscript has the date (in the colophon etc)

**Comment by eu-genia** [comment]
got lost:

[Binding]
-> Decoration :	Blind tooled ornament on the reddish-brown leather cover (at least 4 tools were used: double line fillet, double circle, x-form, criss cross).

**Comment by eu-genia** [comment]
Blank folios :	
-> notes :	1, 2, 32v, 33, 34v

**Comment by eu-genia** [comment]
Number of quires :	5.0
-> notes :	A+4

(number of quires is there but not the notes, important, means actually 4 quires + protective quire)

**Comment by eu-genia** [comment]
"Details" under "Description of Context: Text" are lost, e.g. in my-014

```
-> Details :	
The text includes the following smaller textual units:

1)     Prayers on the clothes: The first prayer. Includes Our Father, reading from 1 Cor. 1:1-10, Trisagion, Mǝsbak (Ps. 84:11-12) and Gospel reading (Jn. 1:1-17) (fols. 3ra, l.10 – 6ra, l.15; Chaîne (ed.), 254 (text), 255 (transl.))

2)     The second prayer (fols. 6ra, l.15 – 6vb, l.7; Chaîne (ed.), 256 (text), 257 (transl.))

3)     The third prayer (fols. 6vb, l.7 – 8ra, l.2; Chaîne (ed.), 256 (text), 257 (transl.))

4)     The fourth prayer. Includes the prayer of Thanksgiving (fols. 8ra, l.3 – 9ra, l.10; Chaîne (ed.), 258 (text), 259 (transl.))

5)     The fifth prayer (fols. 9ra, l.10 – 10ra, l.4; Chaîne (ed.), 258 (text), 259 (transl.))

6)     Prayers on the bride and the bridegroom: the sixth prayer (fols. 10ra, l.4 – 11ra, l.6; Chaîne (ed.), 260 (text), 261 (transl.))

7)     Prayer, designated as “another prayer which is recited over the marriage”. Includes reading from Eph. 5:22-6:3, Qǝdmä Wängel (Ps. 18:6; 127:3), Gospel reading (Mt. 19:1-6) and the Creed (fols. 11ra, l.7 – 13ra, l.12; Chaîne (ed.), 260 (text), 261 (transl.))

8)     The seventh prayer (fols. 13ra, l.12 – 14vb, l.1). Corresponds to the second part of the seventh prayer in Chaîne (ed.), 262 (text), 263 (transl.)

9)     The eighth prayer, not numbered (fols. 14vb, l.1 – 15va, l.6; Chaîne (ed.), 264 (text), 265 (transl.))

10) The ninth prayer (fols. 15va, l.6 – 16vb, l.10; Chaîne (ed.), 264 (text), 265 (transl.))

11) The tenth prayer (fols. 16vb, l.11 – 21ra, l.16). Includes prayer over the ointment, not inscribed as such (fols. 18vb, l.1 – 21ra, l.16; Chaîne (ed.), 266 (text), 267 (transl.))

12) The eleventh prayer (fols. 21ra, l.17 – 21vb, l.9; Chaîne (ed.), 270 (text), 271 (transl.))

13) Anointing of the bridegroom and bride; putting on sacramental garments (fols. 21vb, l.9 – 24rb, l.9; Chaîne (ed.), 270 (text), 271 (transl.)). Incipit of the text not rubricated.

14) Prayer of the benediction, containing biblical passages referring to marriage (fols. 24rb, l.9 – 27rb, l.2; Chaîne (ed.), 274 (text), 275 (transl.))

15) Joining of the hands and blessing of the bridegroom and bride (fols. 27rb, l.2 – 30rb, l.16; Chaîne (ed.), 276 (text), 277 (transl.))

16) Order to be read to the bride and the bridegroom: Prayer (tǝˀǝzaz) over the crowns. Includes Ps. 50, reading from 1 Tim. 4:9-16 and Gospel reading (Jn. 1:14-17) (fols. 30rb, l.17 – 31va, l.15; Chaîne (ed.), 280 (text), 281(transl.))

17) Supplications for peace, for the metropolitan and the congregation, the Creed and the concluding prayers (fols. 31va, l.16 – 32rb, l.3; Chaîne (ed.), 282 (text), 283 (transl.)).
```

**Comment by eu-genia** [comment]
Some things have become <div> and are not visualized on transformation, e.g.

Additiones
```
<item xml:id="a1">
                           <locus/>
                           <div style="line-height: normal" org="uniform" sample="complete">Fol. 34r: Recent purchase note.</div>
```

these divs should probably be desc

**Comment by eu-genia** [comment]
info lost:

Quire marks :	yes
decorated	yes
 	Simply decorated quire marks are written in the middle of the upper margin of fols. 3r, 11r, 19r, 27r.
 
Finding aids :	no

**Comment by eu-genia** [comment]
```
<person><!--donor-->
                  <persName corresp="PRS0000">
```

not possible to add "donor" as role?

**Comment by eu-genia** [comment]
lots of divs are generated and seem to not be accepted by the schema

**Comment by eu-genia** [comment]
In Domlib - (e.g. dz-011):
Donor :	Commissioned by Täklä Maryam and Maḫdärä Qal (s. Additio 1).
Owner :	Mälkǝˀa Krǝstos, Täklä Maryam and Maḫdärä Qal (s. Additio 1).

in TEI now:

```
               <person><!--donor-->
                  <persName corresp="PRS0000">Commissioned by Täklä Maryam and Maḫdärä Qal (s. Additio 1).</persName>
```

the info on owners is lost

**Comment by eu-genia** [comment]
In DomLib (dz-011)
[Physical description]
Other details :	- Text I contains the embedded colophon (fol. 47rb) which states that the book was translated from Coptic and Arabic.
- Text III (different from the work Mäṣḥafä fäws mänfäsawi) is attested also in Mss. DZ-011, GMS-013, MHG-006.

lost in TEI

**Comment by eu-genia** [comment]
also lost
under Text 1
-> Details :	
The text is called here Mäṣḥafä ṭǝmqät. For this way of naming the text s. Mss. EMML nos. 432, 620 and 3107.
S. also EAE IV, 917.

**Comment by eu-genia** [comment]
in DomLib

> -> Type of script :	16th century (hand a).
> -> Hand writing :	Hand a: fine, irregular; hand b: mediocre; hand c: mediocre.
> -> Change of hand :	Hand a (fols. 3r-47r; quires I-VI): thin, broadly spaced letters. 
> Hand b (fols. 47v-68r; quires VI-IX): anqular letter shapes
> Hand c (fols. 70r-84v; X-XI)

in TEI

```
<handNote xml:id="h1" script="Ethiopic">
                        <ab type="script">Hand a: fine, irregular; hand b: mediocre; hand c: mediocre.</ab>
                        <seg type="ink">Black; red.</seg>
                        <date>16th century (hand a).</date>
                        <list type="abbreviations">
                           <item>ይ፡ካ፡ for ይብል፡ ካህን፡</item>
                           <item>ይ፡ዲ፡ for ይብል፡ ዲያቆን፡</item>
                           <item>ይ፡ሕ፡ for ይብል፡ ሕዝብ፡</item>
                        </list>
                     </handNote>
                     <handNote xml:id="h2" script="Ethiopic">thin, broadly spaced letters.  </handNote>
                     <handNote xml:id="h3" script="Ethiopic">anqular letter shapes</handNote>
                     <handNote xml:id="h4" script="Ethiopic"/>
```

the information in brackets is lost for all hands

**Comment by PietroLiuzzo** [comment]
*date as discussed: https://github.com/SChAth/ScAthiop/wiki/guidelines#origin

* blankfolios and quire A+4 added

* divs are, escaped, in the source unfortunately. They need to be cleaned up in the second stage of the conversion with lots of other html.

* quiremarks info added in `signatures` inside `collation`: ok? or in `foliation` ?

* otherdetails added in an msItem after the others divided in note elements. they will need to be moved to their specific item, removing the one in which the transformation puts them.

* details added 

* content in hand changes added back with a comment on cautionary tasks

further improvements

* references to manuscripts marked as `ref`s from domlib fields details and otherdetails
* more fol. indications marked in `locus`.

please wait for upload for a further revision

**Comment by eu-genia** [comment]
lost under "Text"
here ex. from AM-012

> -> Other important passages :
> 
> In the incipit the text is called Śərˁatä asirä mənkwəsənna.

**Comment by eu-genia** [comment]
physical descr. "other details" missing

> (e.g. amq-001
> Other details :	The "Golden Gospel" of ˁAddigrat Qirqos. The most part of the blank space including the margins is occupied by numerous Additiones, written in different recent hands, both in ink and pen.)

**Comment by eu-genia** [comment]
the order of msItems is reverse (e.g. amq-001 from what was 5 to what was 1)

**Comment by eu-genia** [comment]
`ab type="ruling" subtype="patter"`

should be "pattern"

**Comment by eu-genia** [comment]
`<binding contemporary="yes">`
should be "true" to comply with the schema

**Comment by PietroLiuzzo** [comment]
* the order was always mixed up, is now sorted by position
* other important passages is now in a note under msItem
* pattern and contemporary fixed

please wait for upload for a further revision

**Comment by PietroLiuzzo** [comment]
I have also split the locus information from folios when this is separated by ;. unfortunately this is not always the case and there are several instances in which a description is given in (). this will need hand fixing anyway.

**Comment by PietroLiuzzo** [comment]
@eu-genia new files ready for further checking.

**Comment by eu-genia** [comment]
i note that the "short content" which in particular for short descriptions is essential as is the only information about the content is lost - it should become `<summary>`
e.g.
MR-001

> Short content :	I) Täˀamrä Maryam “Miracles of Mary” (fols. 3ra-97rb)
> I-1) Mäṣḥafä śərˁat, Introductory rite of al-Muˁallaqah (fols. 3ra-6rb)
> I-2) Introductory exhortation (fols. 6rb-8va)
> I-3) ˀƎsäggəd läki wä-ˀəweddəsäki... "I worship Thee..." (fols. 8va-9rb)
> I-4) Täˀamrä Maryam "Miracles of Mary": 90 miracles (fols. 9va-77va, 82ra-89ra)
> I-5) ˀƎsäggəd lä-mäläkotəkä... "I worship Thy Godhead..." (fols. 95ra-97rb)
> II) Täˀamrä Mikaˀel “Miracles of Michael”: 3 miracles (fols. 77va-79vb)
> III) Täˀamrä Libanos “Miracles of Libanos”: 4 miracles (fols. 79vb-80vb)
> IV) Täˀamrä Gäbrä Mänfäs Qəddus “Miracles of Gäbrä Mänfäs Qəddus”: 2 miracles (fols. 80vb-81vb)
> V) Täˀamrä mädḫane ˁaläm “Miracles of the Saviour of the World”: 1 miracle (fols. 81vb-82ra)
> VI) Täˀamrä ˀIyasus “Miracles of Jesus”: 4 miracles (fols. 89ra-92ra)
> VII) Täˀamrä śəllase “Miracles of the Trinity”: 3 miracles (fols. 92ra-93rb)
> VIII) Sälam läki ḫoḫətä məśraq... “Salutation to you, Threshold of the East…” (fols. 93rb-94rb)

nothing in xml

**Comment by PietroLiuzzo** [comment]
done

**Comment by PietroLiuzzo** [comment]
Due to amount of postprocessing already performed is not anymore suitable to repeat this operation unless major issues arise. I thus close this issue and invite you all to report in a new issue minor corrections or major problems which might become visible later.
