### ISSUE TITLE
additions introduction

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#520]
Is the sentence "In this manuscript there are..." introducing additions on the app really necessary? In most cases, it doesn't agree with the number of the additions in question, and in cases of mss with only "extras" noted under additions it stops mid-sentence. I think that just listing the additions by type without introduction would be enough.

**Comment by PietroLiuzzo** [comment]
I have added this in a popup on demand, as it was in the initial requirements. so it is still there and does not disturb that much any more :)
