### ISSUE TITLE
name not displayed

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#522]
in BDLaethg12, the name of PRS11449WalattaD (in e2) is not displayed on the app. It seems as if it were loading but never appears

```xml
 <desc>The owners were  <persName ref="PRS11449WalattaD" role="owner">
<certainty locus="value" match="../@role" assertedValue="owner" cert="low"/></persName> and 
  <persName ref="PRS11450TaklaH" role="owner"><certainty locus="value" match="../@role" assertedValue="owner" cert="low"/></persName>. 
```

**Comment by thea-m** [comment]
Similarly, in BDLaethg19 the name of PRS5695John is not displayed in the title of ms_i1

**Comment by PietroLiuzzo** [comment]
this is due to spaces in persName, which should not be there.

**Comment by PietroLiuzzo** [comment]
also note that assertedValue is not the one you have actually given in role but the alternative candidate

**Comment by thea-m** [comment]
I corrected the space (and assertedValue...), but the name of PRS5695John in BDLaethg19 still isn't displayed - is there a different reason here?
