### ISSUE TITLE
keywords for main text only?

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#526]
Should the keywords added to ms records refer only to the main text(s), or also to the additions? They have not been used in the same way by all of us and this should be standardized

**Comment by PietroLiuzzo** [comment]
I personally see no need to standarize too much. we do need as many generic keywords as possible for the sake of search and browsing although. I would thus put as many as possible, so also those that are for the additions.

**Comment by DenisNosnitsin1970** [comment]
From my expierience, it will be simply unpractical and not as easy as it looks like.  There will be many cases with too many keywords, then we have to take care to assign the keywords in the same way. Therefore I would be in favour of some limits.

**Comment by thea-m** [comment]
I don't think that this would be unpractical - maybe the case was different in the Ethiospare database? The keywords actually aren't displayed anywhere in the records  on the app, but are only needed for the search. If we want to make sure that we use them in the same way, we can add more explanations and examples to their definitions in the schema and/or open issues about any cases we are unsure about or notice inconsistencies in our records.  
I believe that someone searching for, say, "magic" would be disappointed not to find the magical texts which are additions. The same is also valid for guest texts which users might expect to find under their respective keywords, regardless of when they were added to the manuscript.

**Comment by thea-m** [comment]
Testing the search has proven that it will be very helpful to assign keywords to all texts contained in a manuscript. Of course, using the keywords in the same way is important. In cases of doubt, a new issue should be opened to discuss the keywords assigned to a particular work, and at some point (in the review process?) the use of keywords should be checked systematically (also ensuring that the keywords used in a work record and the keywords referring to this work in a ms record are identical).
