### ISSUE TITLE
Encyclopaedia title

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#527]
some encyclopeadia articles in Zotero do not have the name of the encyclopaedia. e.g. I have just added it here
https://www.zotero.org/groups/358366/ethiostudies/items/itemKey/8E5RV9EB

I think we need to check that all have it, otherways instead of 
Zitelmann, T. 2007. ‘Illubabor’, Encyclopaedia Aethiopica, III (Wiesbaden: Harrassowitz Verlag, 2007), 124b – 126a .
we get
Zitelmann, T. 2007. ‘Illubabor’, III (Wiesbaden: Harrassowitz Verlag, 2007), 124b – 126a.

**Comment by FrancescaPanini** [comment]
Is there a way to know which ones lack the encyclopaedia title? If we can extract this information easily I can go through them and fix them. Otherwise I can do it one by one but it will be more time consuming.

Thanks

**Comment by PietroLiuzzo** [comment]
in the standalone zotero filter by entry type, that is the only good advise I can give you, then yes, you will have to browse one by one.

**Comment by FrancescaPanini** [comment]
Done and also did some housekeeping and fixed some author's names that were wrong.
