### ISSUE TITLE
scrollbars 

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#530]
I find the inactive scrollbars around each item in the textual units view to be a bit crowding - would it be possible to have them only when they are actually needed?
http://betamasaheft.aai.uni-hamburg.de/works/list
(Same for the scholars listed on the homepage)

**Comment by PietroLiuzzo** [comment]
sorry but I do not understand which "scrollbars" you mean, neither what inactive means. I see none at the link you provided and there isn't any in the homepage either.

**Comment by thea-m** [comment]
looks fine now
