### ISSUE TITLE
Set of values for relations between MSS

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#54]
We need to create a set of values for relations between MSS. For instance:
Let us assume that Ms. BAVaeth1 has been copied from ms. BAVaeth3. We may want to give this information as follows:
`<listBibl type="relations">
 <relation name="copyOf" active="#BAVaeth1" passive="#BAVaeth3"/></listBibl>`
This would work also for single items at various degrees (item ms_i1.1 is a copy of...).
The values we need are: copyOf, antigraphOf, relatedTo (or something similar when we have a textual proximity we are not able to further specify).

**Comment by PietroLiuzzo** [comment]
The schema should already have a series (70) of saws: relations.
the full list is here.
http://www.ancientwisdoms.ac.uk/media/ontology/doc/

Please let me know which one are missing and need to be added.
e.g.

saws:isRelatedTo

saws:isDirectCopyOf

saws:isAncestorOf

saws:hasUsed"

On 29 April 2016 at 15:49, MassimoVilla <notifications@github.com> wrote:

> We need to create a set of values for relations between MSS. For instance:
> Let us assume that Ms. BAVaeth1 has been copied from ms. BAVaeth3. We may
> want to give this information as follows:
>
>
> This would work also for single items at various degrees (item ms_i1.1 is
> a copy of...).
> The values we need are: copyOf, antigraphOf, relatedTo (or something
> similar when we have a textual proximity we are not able to further
> specify).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SChAth/ScAthiop/issues/54>
>



-- 
Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by PietroLiuzzo** [comment]
@MassimoVilla @eu-genia could you please check this list of values and let me know which one we actually need in the schema for relations between manuscripts works and narratives?
http://www.ancientwisdoms.ac.uk/media/ontology/doc/ 
thanks!

**Comment by eu-genia** [comment]
the "subject of" relationship now appears in the schema as

"saws:saws:P129i_is_subject_of" - is a bit weird with 2xsaws

**Comment by PietroLiuzzo** [comment]
typo, now fixed, please wait for updated version of schema.

**Comment by PietroLiuzzo** [comment]
schema is now updated

**Comment by PietroLiuzzo** [comment]
#18 #27 #16
