### ISSUE TITLE
List of mss LIT1011Abusak is mentioned in

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#542]
Why does it say in the record of LIT1011Abusak, "This Work is mentioned in Manuscript records 0 time"? The work is a msItem in BLadd16252 and is mentioned in an inventory in BNFet112

**Comment by PietroLiuzzo** [comment]
the first case appears now with another instance. only refs in mstems are selected. the ref in a q inside BNFet112 will not be displayed as a mss content in that box

**Comment by thea-m** [comment]
Great, thank you! But the the wording "This Work is mentioned in Manuscript records..." is a bit misleading (at least to me). Could it be changed to "This work is contained..."?
