### ISSUE TITLE
use of witness element

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#545]
We are somewhat inconsistent in our use of the witness element in work records. In some very elaborate records (LIT1931Mashaf, LIT2317Senodo), a lot of effort has been put into adding all known witnesses. However, all manuscripts containing the work are displayed in the app anyway, so this is somewhat redundant information. Maybe it would be better to reserve `<witness>` for those manuscripts which are actually used for the edition we are going to provide in the `<text>`

**Comment by PietroLiuzzo** [comment]
guidelines updated. https://github.com/SChAth/ScAthiop/wiki/guidelinesWork#witnesses

**Comment by PietroLiuzzo** [comment]
@eu-genia @DenisNosnitsin1970 @MassimoVilla @nafisa-valieva
