### ISSUE TITLE
witnesses in work records

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#547]
http://betamasaheft.aai.uni-hamburg.de/LIT1941Mashaf.xml
http://betamasaheft.aai.uni-hamburg.de/works/LIT1941Mashaf/main

shouldn't these witnesses have type external?

https://github.com/SChAth/ScAthiop/wiki/guidelinesWork#witnesses

**Comment by thea-m** [comment]
absolutely! I corrected it, thank you
