### ISSUE TITLE
@xml:id equal to work ids

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#549]
in LIT3186Meeraf I found this

````xml
<div type="textpart" xml:id="LIT1989mawadd"><label>Chants for the office of Sundays <foreign xml:lang="gez">መወድስ፡</foreign></label></div>
            <div type="textpart" xml:id="LIT1714Kestat"><label>Chants of the Revelation of ʾaryām<foreign xml:lang="gez">ክሥተት፡ ዘአርያም፡</foreign></label></div>
            <div type="textpart" xml:id="LIT2301Sebhat"><label>Chants for the office of the Morning Praise <foreign xml:lang="gez">ስብሐተ፡ ነግህ፡</foreign></label></div>
   `````
this is a wrong use of @xml:id. 
See: https://github.com/SChAth/ScAthiop/wiki/guidelinesWork#divs-edition-and-textparts
where the example which should apply here is the second and not the first. 
If there is need for more clarity in the guidelines, please, edit them.

**Comment by PietroLiuzzo** [comment]
@thea-m this is the reason why you get http://betamasaheft.aai.uni-hamburg.de/search.html?query=%E1%88%98%E1%8B%88%E1%8B%B5%E1%88%B5
and 
http://betamasaheft.aai.uni-hamburg.de/Dillmann/lemma/L22d57a7a38724c708992a8517946d00a

**Comment by MassimoVilla** [comment]
corrected. Thank you Pietro!
