### ISSUE TITLE
institutions id

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#55]
ids in ins files have been created in a different way from those into manuscript files. they need to be replaced.

**Comment by PietroLiuzzo** [comment]
#52

**Comment by MassimoVilla** [comment]
The numerical part INS0301 has been given twice: INS0301IV (Institut vostochnyh rukopisej) and INS0301HMML.
I just point it out in order to make you aware, in case we want to assign a new ID to one of them.

**Comment by PietroLiuzzo** [comment]
indeed we don't want double numbers. Please go ahead and fix this.

**Comment by MassimoVilla** [comment]
The Hill Museum and Manuscript Library is now identified as INS0004HMML. Please, update the reference if you have already used it.

**Comment by PietroLiuzzo** [comment]
This has been solved, please open new issues if needed for similar issues and assign them to people who would need to check their work
