### ISSUE TITLE
bibliographic reference on dimensions

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#562]
Where can I add a bibliographic reference on a manuscript's dimensions (if the values for the dimension aren't mentioned in the catalogue, but in a secondary source)? 
In BDLbruce88, I added a `<listBibl>` inside `<note>` in `<extent>`

**Comment by PietroLiuzzo** [comment]
I believe this is overencoding. Adding the bibliography inside extent does not add anything to the semantic unless the article or book does ONLY report the dimensions of the manuscript, and even in that case I would not understand why not to list it in the secondary bibliography about the manuscript with the rest. The reference, even when visualized would remain isolated. I would simply list this reference with the others about the manuscript or manuscript part.

**Comment by thea-m** [comment]
Thank you! I believe we might have been overencoding elsewhere as well then (partly also because people usually reading the records often point to a certain precise information and ask about its source.).
Maybe interesting for you as well @MassimoVilla
