### ISSUE TITLE
Gəʿəz or Gəʿz?

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#568]
Which transliteration do we use? Until now, we have Gəʿəz everywhere, but @DenisNosnitsin1970 now has been using Gəʿz (following M. Bulakh's article I suppose). 
The problem this poses is that when one uses the advanced search and filters by language,  both Gəʿəz and Gəʿz appear now in the list of languages, and when searching for example for "wəddāse" and filtering by "gəʿəz", IVefiopsk10 (which uses Gəʿz) doesn't appear in the result list (and vice versa). 
(I know I'm the only one who tries out such searches, but still...)

**Comment by abausi** [comment]
We have to follow: "Gəʿəz", which, irrespective of its validity or not, is acknowledged as the standard form to indicate the language. So those who use another form are kindly asked to correct as soon as possible. The remark is important and consistency of search has to be safeguarded.

**Comment by thea-m** [comment]
updated the guidelines and corrected the concerned record
