### ISSUE TITLE
Description of the quire structure

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#57]
Just one remark concerning the quire description. The following example is from ms. BAV et. 1, but it is valid for all the Ethio-SPaRe MSS:

` <item xml:id="q3">
<dim unit="leaf">8</dim>
<locus from="11r" to="18v"/>II(8/fols. 11r-18v)</item>`

I think we need to rationalize the unmarked information given as II(8/fols. 11r-18v): the Roman number is necessary because it indicates something different than the quire ID given in `<item xml:id="q3">`, but 8 duplicates the information given in `<dim unit="leaf">8</dim>` and /fols. 11r-18v duplicates the information given in `<locus from="11r" to="18v"/>`. So, we may leave the Roman number and insert within brackets any additional information, as it is tipically the case with stubs (many examples in the Ethio-SPaRe descriptions), or we may find another strategy.
Please tell me your opinion.

**Comment by PietroLiuzzo** [comment]
I fully agree. in the automated conversion to TEI of the ethiospare files
this could not be cleaned as it needs human check und understanding. I
would not duplicate data which is in other elements for the newly entered
manuscripts. if the information given by the roman numeral can be encoded
e.g. with a @n this would be easy to add and each item might not need
further data unless necessary to freely float in the item element

On 2 May 2016 at 18:30, MassimoVilla <notifications@github.com> wrote:

> Just one remark concerning the quire description. The following example is
> from ms. BAV et. 1, but it is valid for all the Ethio-SPaRe MSS:
>
> <item xml:id="q3">
> <dim unit="leaf">8</dim>
> <locus from="11r" to="18v"/>II(8/fols. 11r-18v)</item>
>
> I think we need to rationalize the information contained as a content of
> II(8/fols. 11r-18v): the Roman number is necessary because it indicates
> something different than the quire ID given in <item xml:id="q3">, but 8
> duplicates the information given in <dim unit="leaf">8</dim> and /fols.
> 11r-18v duplicates the information given in <locus from="11r" to="18v"/>.
> So, we may leave the Roman number and insert within brackets any additional
> information, as it is tipically the case with stubs (many examples in the
> Ethio-SPaRe description), or we may find another strategy.
> Please tell me your opinion.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SChAth/ScAthiop/issues/57>
>



-- 
Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by MassimoVilla** [comment]
For those who will deal with quire structure descriptions:
while describing BAVet1 I have formalized the Roman numbering as follows:
`<item xml:id="q26">
                      <dim unit="leaf">8</dim>
                      <locus from="195r" to="202v"/>
                      <note>XXV</note></item>`
`<item xml:id="q27">
                      <dim unit="leaf">3</dim>
                      <locus from="203r" to="205v"/>
                      <note>XXVI(s.l.: 3, stub before 1)</note></item>`
Both the Roman number and any peculiarity we might come across are encoded with @note.
Please comment if you deem a different element as more appropriate, or if you think we'd better mark the Roman number and the additional information separately.

**Comment by PietroLiuzzo** [comment]
I think the issue would remain unaltered using only the element note.
what about `<num value="19">XIX</num>` same would be usable for other types
of numerals. I don't know for example what these different numberation
tell, but we might want to distinguish.

in something like this

፳XXI(6; s.l.: 3, stub after 4; 4, stub after 3/fols. 157r-162v)

what is the difference between the first numeration and the second? which
kind of information do they give?

On 5 May 2016 at 14:59, MassimoVilla <notifications@github.com> wrote:

> For those who will deal with quire structure descriptions:
> while describing BAVet1 I have formalized the Roman numbering as follows:
> <item xml:id="q26">
> <dim unit="leaf">8</dim>
> <locus from="195r" to="202v"/>
> <note>XXV</note></item>
> <item xml:id="q27">
> <dim unit="leaf">3</dim>
> <locus from="203r" to="205v"/>
> <note>XXVI(s.l.: 3, stub before 1)</note></item>
> Both the Roman number and any peculiarity we might come across are encoded
> with @note <https://github.com/note>.
> Please comment if you deem a different element as more appropriate, or if
> you think we'd better mark the Roman number and the additional information
> separately.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/SChAth/ScAthiop/issues/57#issuecomment-217161959>
>



-- 
Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by MassimoVilla** [comment]
At the end I used @n, as you had previously suggested: `<item xml:id="q26" n="XXV">
                      <dim unit="leaf">8</dim>
                      <locus from="195r" to="202v"/>
                      </item>`
To be honest at this stage I can't predict the implications of adopting @n="19" or `<num value="19"/>`.
While numbering the quires, Ethio-SPaRe used to distinguish between the initial/final quires made of guard-leaves (quires with a rather exceptional status, labelled "A" and "B" respectively) and the quires of the main body of the codex (indicated with progressive Roman numbers). This is why a 20-quire MS is described as A+XVIII+B.
The Ethiopic number indicates the number assigned by the Ethiopian scribe to each quire and written on the first or last folio of the quire. This information was preserved by Ethio-SPaRe writing the Ethiopic character before or after the Roman number respectively: ፬IV or IV፬. Printed catalogues almost systematically disregard this information, but Ethio-SPaRe used to record it, so I think we might want to keep it.

**Comment by PietroLiuzzo** [comment]
I am ok with using `@n` but I would strongly recommend not to use roman numerals. we can display the value as roman numerals but they are much more complex to handle in the source file. as the total numbering is kept in the `@xml:id` we could still use A and B for guard-leaves in `@n`. the Ethiopian Scribe numeration would form part of the information and I would really tag it with `<num value=""></num>`

**Comment by PietroLiuzzo** [comment]
added this to guidelines.
