### ISSUE TITLE
work records not displayed

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#571]
LIT2083Octate and all records contained in it are not displayed on the app:

> HTTP ERROR 500
> 
> Problem accessing /exist/apps/BetMas/works/LIT2075Number/main. Reason:
> 
>     Server Error
> Caused by:
> 
> javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMas/works/LIT2075Number/main: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: app:printTitleID($id as xs:string) item()*. Expected cardinality: exactly one, got 2. [at line 1555, column 77, source: /db/apps/BetMas/modules/item.xqm]
> In function:
> 	app:printTitleID(xs:string) [1555:59:/db/apps/BetMas/modules/app.xqm]
> 	item:RestMss(item()*) [1634:31:/db/apps/BetMas/modules/item.xqm]
> 	item:RestSeeAlso(item()*, item()*) [1729:6:/db/apps/BetMas/modules/item.xqm]
> 	item:RestItem(item()*, item()*) [184:5:/db/apps/BetMas/modules/item.xqm]
> 	restItem:ITEM(item()*, item()*, item()*, xs:integer*, xs:integer*, xs:string*) [66:1:/db/apps/BetMas/modules/items.xql]
> 	restItem:getItem(xs:string*, xs:string*, xs:integer*, xs:integer*, xs:string*) [-1:-1:/db/apps/BetMas/modules/items.xql]
> 	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:378)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
> 	at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:171)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
> 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
> 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:459)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:524)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
> 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
> 	at java.lang.Thread.run(Thread.java:748)

...

**Comment by PietroLiuzzo** [comment]
the file is there indexed and text view accessible. Hint. A ms record
containing this texts might be broken or double

Am 14.08.2017 11:48 AM schrieb "thea-m" <notifications@github.com>:

**Comment by thea-m** [comment]
thank you! BLorient482 had a problem, I fixed it
