### ISSUE TITLE
problem with BDLbruce93

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#575]
There is a problem with BDLbruce93, whose source I couldn't find out (persists also with commenting practically everything out):

> HTTP ERROR 500
> 
> Problem accessing /exist/apps/BetMas/works/BDLbruce93/main. Reason:
> 
>     Server Error
> Caused by:
> 
> javax.servlet.ServletException: An error occurred while processing request to /exist/apps/BetMas/works/BDLbruce93/main: exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: app:clavisIds($doc as node()) item()*. Expected cardinality: exactly one, got 0. [at line 670, column 28, source: /db/apps/BetMas/modules/item.xqm]
> In function:
> 	app:clavisIds(node()) [670:13:/db/apps/BetMas/modules/app.xqm]
> 	item:RestItemHeader(item()*, item()*) [147:5:/db/apps/BetMas/modules/item.xqm]
> 	restItem:ITEM(item()*, item()*, item()*, xs:integer*, xs:integer*, xs:string*) [66:1:/db/apps/BetMas/modules/items.xql]
> 	restItem:getItem(xs:string*, xs:string*, xs:integer*, xs:integer*, xs:string*) [-1:-1:/db/apps/BetMas/modules/items.xql]
> 	at org.exist.http.urlrewrite.XQueryURLRewrite.service(XQueryURLRewrite.java:378)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1689)
> 	at de.betterform.agent.web.filter.XFormsFilter.doFilter(XFormsFilter.java:171)
> 	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
> 	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
> 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:459)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:524)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
> 	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
> 	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by PietroLiuzzo** [comment]
did you manage to solve this?
http://betamasaheft.eu/manuscripts/BDLbruce93/main

**Comment by thea-m** [comment]
Not really, as I didn't change anything, all I did was commenting out all possible sections, but the problem always persisted. I have no idea why it's fine now, but wonderful!
