### ISSUE TITLE
rules for change and bibl

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#58]
per @when in change, cerchiamo di usare format-date (il code template) oppure di scrivere la data nel formato data soltanto: 2016-03-21, non 2016-02-09-12:00 o 2016-02-09+2:00. dataTime per ora va bene, ma omologhero appena possibile.

per i ptr/@target che puntano alla bibliografia, dobbiamo cercare di attenerci alle linee guida oppur modificarle per riflettere la prassi. 

bibl con @corresp è per i manoscritti simili, non per record in Zotero.
bibl con ptr/@target lo usiamo per zotero con un id univoco che inizia con bm: 
bm:Grohmann1919Marien e non Grohmann1919Marien

questo non è un grosso problema, se l'id è comunque univoco, ma credo sia bene avere dati consistenti da questo punto di vista. 

inseriro comunque due test nello schema per forzare questi valori.

**Comment by MassimoVilla** [comment]
Ieri OXygen mi suggeriva di inserire il citedRange di un riferimento bibliografico come elemento anziché con @from e @to. Ho quindi corretto, per esempio, `<bibl><ptr target="bm:Dillmann1847BM"/><citedRange unit="page" from="2b" to="3a"/></bibl>` in `<bibl><ptr target="bm:Dillmann1847BM"/><citedRange unit="page">2b-3a</citedRange></bibl>`. Oggi il modo precedente è tornato accettabile, o meglio entrambi sono possibili. Per consistenza dell'informazione, è preferibile tornare al vecchio @from="" @to=""?

**Comment by PietroLiuzzo** [comment]
the change made is correct. the schema should complain when you use either `@from` or `@to` saying 

     Please, don't use @from and @to in citedRange, wirte the range into the element

what I tried to enforce in the schema is the adherence to the guidelines
https://github.com/SChAth/ScAthiop/wiki/guidelines#bibliographic-references
I have added also a line there to deprecate the use of from and to in citedRange.
