### ISSUE TITLE
guidelines institution tabot relation

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#60]
update guidelines as follows

[03/05/16, 15:46:04] eugenia sokolinski: a solo             <relation name="tabot" active="#INS0030AP">
               <desc>unidentified marble tabot</desc>
            </relation>
[03/05/16, 15:46:08] Pietro Liuzzo: volendo in Desc puoi anche mettere tutto il paragrafo di cui sopra
[03/05/16, 15:46:35] eugenia sokolinski: no ma gli altri hanno altri relation aspetta
[03/05/16, 15:47:09] Pietro Liuzzo: perché li metti uno per uno, ho capito.
[03/05/16, 15:47:26] Pietro Liuzzo: ma per questo per esempio The tabot of the local Ṣadǝqan (Righteous Ones) was not mentioned, probably by mistake.
[03/05/16, 15:47:31] Pietro Liuzzo: in desc puoi mettere tutta la frase
[03/05/16, 15:47:49] Pietro Liuzzo: e in passive immagino Ṣadǝqan

**Comment by eu-genia** [comment]
mi sembrerebbe più trasparente, forse
 
per esempio, sempre nell’INS0065AMQ
 
<ab type="tabot">
   <measure quantity="4"/>
   Tabots of <persName corresp="PRS3249Cyriacus">Qirqos</persName>, <persName corresp="PRS9684Uriel">Urael</persName>, <persName corresp="PRS6819Mary">Mary</persName>, <persName corresp="PRS10777Madhane">Madḫane ʿĀlam</persName>
</ab>
 
oppure anzi
 
<ab type="tabot">
   <measure quantity="4"/>
   <listPerson>
      <person>
         <persName corresp="PRS3249Cyriacus"/>
      </person>
      <person>
         <persName corresp="PRS9684Uriel"/>
      </person>
      <person>
         <persName corresp="PRS6819Mary"/>
      </person>
      <person>
         <persName corresp="PRS10777Madhane"/>
      </person>
   </listPerson>
</ab>
 
Tutti e due mi risultano validi nell’Oxygen.

**Comment by PietroLiuzzo** [comment]
è valido, certo, ma vogliamo usare un anonymous block per qualcosa di semanticamente caratterizzato e chiaro?

**Comment by eu-genia** [comment]
sotto Gunda Gunde ho fatto
```
            <relation name="tabot" active="#INS0005Gund" passive="#PRS6819Mary #PRS9162TaklaHa" ><desc>Tabots: reportedly, up to <num>30</num> tabots (also those brought from the deserted churches in the vicinity). Tabot of Mary in the upper church reserved for monks; tabot of Täklä Haymanot 
               in the lower church for the local people.</desc></relation>
```
ma sinceramente non mi convince, e poi la trasformazione nel <ab type="tabot"> forse potrebbe essere fatta anche automaticamente

**Comment by eu-genia** [comment]
nell'INS0030AP

```
            <relation name="tabot" active="#INS0030AP" passive="#PRS5684JesusCh"/>
               <relation name="tabot" active="#INS0030AP" passive="#PRS10775Trinity"/>
               <relation name="tabot" active="#INS0030AP" passive="#PRS6819Mary"/>
            <relation name="tabot" active="#INS0030AP">
               <desc>unidentified marble tabot</desc>
            </relation>
               <relation name="tabot" active="#INS0030AP" passive="#PRS4377Gabriel"/>
               <relation name="tabot" active="#INS0030AP" passive="#PRS10776Kidan"/>
            <relation name="tabot" active="#INS0030AP" passive ="#PRS7049Michael"/>
            <relation name="tabot" active="#INS0030AP" passive="#PRS10774Paraq"/>
            <relation name="tabot" active="#INS0030AP" passive="#PRS10773SadeqP" evidence="conjecture">
               <desc>The tabot of the local Ṣādǝqān (Righteous Ones) was not mentioned by the local priests, probably by mistake.</desc>
            </relation>
```
qui per esempio ho perso l'informazione del numero (8)

**Comment by PietroLiuzzo** [comment]
possiamo contare queste relation e vengono 8 valori per passive, ma 9 relation (c'è quindi anche quello not mentioned). si possono creare relazioni a partire da altro markup naturalmente, ma qui che ti interessa è la relazione tra il luogo e la persona/santo/epiteto, oppure solo l'informazione sui tabot? se non è la relazione tra le due cose che interessa marcare, un p o un ab vanno altrettanto bene altrove nel file come nel tuo primo esempio e se poi vorrete estrarre le relazioni le estrarremo altrimenti.

**Comment by PietroLiuzzo** [comment]
from email: Certo in quest’ultimo esempio la measure sembra superflua perché si vede che sono 4, ma nel caso di Gunda Gunde abbiamo “reportedly, up to 30 tabots”, e elencati sono due soli.

**Comment by eu-genia** [comment]
si stavo proprio scrivendo contare funziona nell'ultimo esempio ma non in quello di Gunda Gunde...

se possiamo definire per noi che i persName sotto ab del tipo tabot sono semanticamente identiche alle relazioni sarei per la prima o seconda variante

a me interessa che io posso filtrare e visualizzare tutte le chiese che hanno un tabot dedicato a XY, e quando visualizzo le persone (santi) anche li' posso vedere tutti gli altari dedicati a questo santo (importante per studi di venerazione)

se in una fase piu' avanzata possiamo anche vedere le distribuzioni geografiche (voglio vedere dove stanno tutte le chiese dedicate a un certo santo)

**Comment by PietroLiuzzo** [comment]
ok, allora metterei la prima variante che mi pare anche la più semplice
nelle guidelines. in #62 ho aggiunto il requisito per la trasformazione.
metto invece questo testo nei requisiti di ricerca


2016-05-03 22:12 GMT+01:00 eu-genia <notifications@github.com>:

> si stavo proprio scrivendo contare funziona nell'ultimo esempio ma non in
> quello di Gunda Gunde...
>
> se possiamo definire per noi che i persName sotto ab del tipo tabot sono
> semanticamente identiche alle relazioni sarei per la prima o seconda
> variante
>
> a me interessa che io posso filtrare e visualizzare tutte le chiese che
> hanno un tabot dedicato a XY, e quando visualizzo le persone (santi) anche
> li' posso vedere tutti gli altari dedicati a questo santo (importante per
> studi di venerazione)
>
> se in una fase piu' avanzata possiamo anche vedere le distribuzioni
> geografiche (voglio vedere dove stanno tutte le chiese dedicate a un certo
> santo)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SChAth/ScAthiop/issues/60#issuecomment-216666272>
>



-- 
Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by eu-genia** [comment]
mi è venuto nel frattempo un nuovo dubbio!
come si fa se la descrizione dei tabot dice p.e.
"The tabot of St Mary was brought by abbot Yeshaq"
qui avrei 2 persName, ma solo una è la dedica=relazione. aggiungere un roleName tabot?

**Comment by eu-genia** [comment]
oppure un type? <persName corresp="PRS5684JesusCh" type="tabot"> ?

**Comment by PietroLiuzzo** [comment]
possiamo aggiungere un valore a @role in persName: che valore metto?

On 4 May 2016 at 10:09, eu-genia <notifications@github.com> wrote:

> oppure un type? ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SChAth/ScAthiop/issues/60#issuecomment-216803560>
>



-- 
Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by PietroLiuzzo** [comment]
https://github.com/SChAth/ScAthiop/wiki/guidelinesPlace
