### ISSUE TITLE
groups of people

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#61]
gruppo di santi locali

how to record? separate special entity?

**Comment by PietroLiuzzo** [comment]
what about personGrp @eu-genia ? we could create a record all in all similar to person, but instead of persNames it will contain a personGrp and relations to records about individuals

**Comment by eu-genia** [comment]
how does it get around the fact that in some cases groups have no members, for example these Sadeqan - we do not know anything about the individuals. and in some cases the members fluctuate (Nine Saints: there is a core of 7 and the remaining 2 vary from case to case).

any suggestion concerning the epithets? 
> p.e. Madhane Alem = Salvatore del Mondo (i.e. Gesù, ma è una dedicazione a parte): qui creo PRS per l’epiteto e metto un rapporto? oppure io metto sotto Gesù tutti gli epiteti come <persName type=”alt” xml:id=”#n1”> con un id specifico e dalle istituzioni punto sull’id derivato PRS000111#n1? (la seconda soluzione è un po’ più difficile per lavorarci perché gli id derivati non li vedo nella lista Excel)

and the abstractions? (Kidana Mehrat = Il patto della misericordia (la promessa di Gesù a Maria))

**Comment by PietroLiuzzo** [comment]
For groups without members it is not a problem, the listPerson will contain
only the personGrp, and eventually description, no relations.

For fluctuant members we could simply use different relations. some will be
partOf, some maybePartOf the group.

for epithets I believe we discussed this, but it looks like it did not make
it to the guidelines. I would add to the record of the person with that
epithet an addName[@type='epithet']. If you want to specify the relations
to the level of those ids you can, of course, but what would be the use
case for that? which kind of relation would need to link to an epithet only
if this is already stored for each person which can have it? is this for
the tabot?

for abstractions, perhaps a person record with a special type "abstraction"
for this would suffice for analytical purposes. if then they become
thousands we might look for a better way to structure information about
this abstractions.



On 3 May 2016 at 17:35, eu-genia <notifications@github.com> wrote:

> how does it get around the fact that in some cases groups have no members,
> for example these Sadeqan - we do not know anything about the individuals.
> and in some cases the members fluctuate (Nine Saints: there is a core of 7
> and the remaining 2 vary from case to case).
>
> any suggestion concerning the epithets?
>
> p.e. Madhane Alem = Salvatore del Mondo (i.e. Gesù, ma è una dedicazione a
> parte): qui creo PRS per l’epiteto e metto un rapporto? oppure io metto
> sotto Gesù tutti gli epiteti come con un id specifico e dalle istituzioni
> punto sull’id derivato PRS000111#n1? (la seconda soluzione è un po’ più
> difficile per lavorarci perché gli id derivati non li vedo nella lista
> Excel)
>
> and the abstractions? (Kidana Mehrat = Il patto della misericordia (la
> promessa di Gesù a Maria))
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SChAth/ScAthiop/issues/61#issuecomment-216587260>
>



-- 
Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by eu-genia** [comment]
we discussed about epithets under persons yes, but not about epithets that have their own very specific circulation. a Church of the Saviour of the World is not the same as a Church of Jesus, there could even be two distinct tabots, one of the Saviour and another of Jesus.
same with the Virgin: there may be a tabot to Mary but also another one to e.g. Berhan (Pearl, an epithet of Mary).
so if we keep the epithets with the person we have to always look for the derived id...
if one ever adds the Islamic dimension to the project we have an even more complex situation with the 99 names of God...

**Comment by PietroLiuzzo** [comment]
I agree not to overcomplicate things. what is useful for you to know and
index? how often the tabot is attributed to the epithet only? I believe
there would be no harm in adding the "derived" ids to the google table for
the purpose of temporary lookup.

On 3 May 2016 at 18:42, eu-genia <notifications@github.com> wrote:

> we discussed about epithets under persons yes, but not about epithets that
> have their own very specific circulation. a Church of the Saviour of the
> World is not the same as a Church of Jesus, there could even be two
> distinct tabots, one of the Saviour and another of Jesus.
> same with the Virgin: there may be a tabot to Mary but also another one to
> e.g. Berhan (Pearl, an epithet of Mary).
> so if we keep the epithets with the person we have to always look for the
> derived id...
> if one ever adds the Islamic dimension to the project we have an even more
> complex situation with the 99 names of God...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SChAth/ScAthiop/issues/61#issuecomment-216607880>
>



-- 
Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by eu-genia** [comment]
yep it will be necessary to see all tabots dedicated e.g. to Mary but also in particular only those dedicated to Mary the Zion etc. Same will be in the Works e.g. we can have homilies in honour of Jesus Christ but also homilies in honour of the Saviour of the World etc. 
Ok we should then in the google table where we put name variants add the specific derived ids

**Comment by PietroLiuzzo** [comment]
from Eugenia 
PRS5684JesusCh - forse quando puoi lo guardi... e nel persongrp - dove metto i nomi del gruppo? ho provato con PRS10775Trinity ma non so dove metterli - nel persongrp non posso perché sembrano membri del gruppo... puoi correggere sul mio esempio

**Comment by PietroLiuzzo** [comment]
better frasing and example on how we could do this here https://github.com/SChAth/ScAthiop/wiki/guidelinesPerson#groups

**Comment by PietroLiuzzo** [comment]
and for epithets : https://github.com/SChAth/ScAthiop/wiki/guidelinesPerson#epithet

**Comment by eu-genia** [comment]
dagli esempi tei mi veniva l'impressione che di solito i membri di un persongrp sono elencati dentro del persongrp e poi sotto relations si descrivono i relazioni[](, http://www.tei-c.org/Vault/P5/3.0.0/doc/tei-p5-doc/de/html/examples-personGrp.html)

**Comment by PietroLiuzzo** [comment]
si, ma noi i person li abbiamo nei loro record, quindi bastano le relation e i persName nel personGrp li usiamo per i nomi del gruppo stesso. in questo modo secondo me evitiamo anche il problema di definire un gruppo standard. che tipo di distinzione vorresti fare inserendo i person anche qui?

**Comment by eu-genia** [comment]
no niente pensavo solo che l'elemento personGrp e' per nestare le persone (anche nei esempi tei le persone hanno i loro id fuori), se si puo' fare come dici tu per me non e' un problema, ieri mi sa non mi prendeva persName direttamente sotto personGrp, insisteva su person

**Comment by eu-genia** [comment]
no mi sbaglio certo persName ci andava ma pensavo ogni persName deve essere un membro del personGrp e non il suo nome

**Comment by eu-genia** [comment]
i per i molto lenti - PRS5684JesusCh e' giusto cosi' con l'epiteto o no? e come esattamente punto su viaf:id, puoi fare un esempio?

**Comment by PietroLiuzzo** [comment]
secondo me cosi puo andare bene. ho aggiornato di conseguenza le guidelines.
