### ISSUE TITLE
tabots in institution

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#62]
Forse sarebbe inoltre possibile fare un data mining ulteriore e trasformare le righe sotto ab history che cominciano con la parola Tabot o Tabots nel ab tabot in tutte le institutions

**Comment by eu-genia** [comment]
si sarebbe perfetto era proprio quello che intendevo sotto la possibilita' di una trasformazione automatica - anche perquesto sarei per la variante con ab tabot
