### ISSUE TITLE
autocomplete template

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#68]
could we possibly rename the characters in the template so that they all start with the "base" letter? would help to scroll and to autocomplete too.
i.e.
instead of "long a" --> "a long" ; "affricated c" ---> "c affricated" etc.

**Comment by MassimoVilla** [comment]
and, since we are improving the code template, we could also fix pharzngeal --> pharyngeal

**Comment by PietroLiuzzo** [comment]
ma'z'be...

On 10 May 2016 at 19:08, MassimoVilla <notifications@github.com> wrote:

> and, since we are improving the code template, we could also fix
> pharzngeal --> pharyngeal
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SChAth/ScAthiop/issues/68#issuecomment-218224940>
>



-- 
Pietro Maria Liuzzo
cel (EN): (+44)7529495584
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by PietroLiuzzo** [comment]
codetemplates updated. note that you might need to hand delete the old ones if they are not replaced by oXygen. 
https://github.com/SChAth/ScAthiop/wiki/Project-Workplace-Setup#special-characters-and-letters-with-diacritics
