### ISSUE TITLE
auth files for art themes

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#70]
it could possibly be useful to create a still another set of auth. files for art themes in order to 
1) standardize the descriptions of decorated mss and
2) create a repertory of motives in art
(e.g. Crucifixion
Presentation at the Temple
Ancient of Days
etc)
3) then in the auth file one could e.g. define that Crucifixion is a depiction of Jesus, and when one looks for miniatures with Jesus one also finds those with Crucifixion etc.

of course it also makes the work even more complex... ideas? @MassimoVilla @DenisNosnitsin1970

**Comment by PietroLiuzzo** [comment]
I have created a minimal record for Crucifixion. Perhaps the better solution to this includes also a taxonomy, which we can use to present the entities, but also to disambiguate the ids from those of manuscripts. this taxonomy may contain only the ids organized as wished and will not impact the ability to keep them flexible, it will just be a way of presenting them. if in future we decide to opt for xinclude for interoperability purposes we might do this as well.

**Comment by eu-genia** [comment]
to add to the taxonomy of additional texts:
MagicFormula
MagicText

**Comment by PietroLiuzzo** [comment]
done

**Comment by PietroLiuzzo** [comment]
Dear all, please see the stub at this entities in the Authority-files repo and let me know what you think. We might also discuss this in more details in the next meeting.

**Comment by MassimoVilla** [comment]
As to the repertory of art motives, I remember there is an index of art themes at the end of:
Stanislaw Chojnacki, _Major Themes in Ethiopian Painting_. Aethiopistische. Forschungen, 10. Wiesbaden, 1983.
The book is in Vita and Susanne's room, behind Vita's desk. I am not in Hamburg, so I can't check it, but I think it might be useful for enriching our list of art motives.

**Comment by PietroLiuzzo** [comment]
a new controlled list of records for feasts is going to be also provided by @eu-genia

**Comment by PietroLiuzzo** [comment]
please update Authority-files repo. Taxonomy is not edited, please modify that file for hierarchy. Definitions and relations would also be nice here, IMHO.

**Comment by PietroLiuzzo** [comment]
https://github.com/SChAth/ScAthiop/wiki/taxonomies
