### ISSUE TITLE
way to see all work IDs used

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#72]
is it possible to create a visualization for all works that have been linked to? with links to the mss / persons etc from where they are linked?

**Comment by PietroLiuzzo** [comment]
for content check purpose or in the final app?

**Comment by eu-genia** [comment]
for content check purpose

**Comment by PietroLiuzzo** [comment]
please check this temporarely.
https://github.com/SChAth/ScAthiop/blob/master/utility/result/list.html
 however this is created on local copies of the repo as the collection() function stables upon a .DS_store file which is system generated in the git folders.

**Comment by eu-genia** [comment]
looks good - probably just shelfmarks/ids for mss would be better than titles
is there a trick how to open the html clicking the link directly and not from the local copy folder?

**Comment by eu-genia** [comment]
best would be
work title (work id)
quoted in
ms id/shelfmark
person id/title
place id/title
