### ISSUE TITLE
Content in non-Ethiopic writing

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#74]
How to insert a string in non-Ethiopic (and non-Latin) characters?
In particular, I need to quote the content of an addition in Arabic. The same might occur, for instance, with Coptic marginalia.

**Comment by PietroLiuzzo** [comment]
I would simply type in the text with an arabic / coptic keyboard, although
I have never used one and I have no suggestions my self. eugenia certainly
has ideas!

On 24 May 2016 at 04:31, MassimoVilla <notifications@github.com> wrote:

> How to insert a string in non-Ethiopic (and non-Latin) characters?
> In particular, I need to quote the content of an addition in Arabic. The
> same might occur, for instance, with Coptic marginalia.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/SChAth/ScAthiop/issues/74>
>



-- 
Pietro Maria Liuzzo
cel (DE): +49 (0) 176 61 000 606
Skype: pietro.liuzzo (Quingentole)
https://uk.linkedin.com/in/pietroliuzzo

**Comment by MassimoVilla** [comment]
My problem is that the Arabic script is not shown on oXygen. However, if I copy and paste the whole passage from an external source (.word, for instance), it still does not appear on oXygen (not even as empty squares), but it is correctly visualized on the preview. So, no big deal: perhaps it is a matter of fixing my oXygen options ("Preferences"?).

**Comment by PietroLiuzzo** [comment]
Potrebbe essere il font che stai utilizzando. Prova cosi: In preferences
cerca font e cambia con un altro che abbia copertura anche per l'arabo
Il 24/Mag/2016 08:52, "MassimoVilla" <notifications@github.com> ha scritto:

**Comment by eu-genia** [comment]
sì infatti abbiamo messo Ludolfus che non ha l'arabo
prendiamo qualcos'altro tipo Ethiopic Unicode

**Comment by eu-genia** [comment]
o Titus
