### ISSUE TITLE
langUsage

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#75]
Some texts might be written in Latin (e.g., in the Vatican MSS). Allowed values for langUsage are: "am", "ar", "cop", "en", "fa", "geo", "gez", "grc", "he", "hy", "it", "syr", "ti", "tu". 
At present ` <langUsage>
        <language ident="lat">Latin</language>
      </langUsage>` is invalid. I think we might add "lat" for latin.

**Comment by eu-genia** [comment]
the value for Latin should be "la" (http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry)

**Comment by DenisNosnitsin1970** [comment]
i also now have a note in Georgian so "ka" should also be possible

**Comment by PietroLiuzzo** [comment]
update, wait for schema update
