### ISSUE TITLE
EthioSPaRe mss and composite mss issues

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#79]
- outer dimensions are still in cm not mm - or we can say we leave cm (or inches where we have inches) and only recalculate in mm for visualization?

-   `<dimensions type="margin">` has no unit specified (should be `<dimensions type="margin" unit="mm">`)

- how do we deal with the cases when one quire includes the ff. numbered as follows: 92, 93, 94, 99
(i.e. putting `<locus from="92r" to="99v"/>` would be wrong as ff. 95 to 98 are not included)

- how to show that an msPart is not attached after but is inserted inside another msPart?

- how to show that in a ms that has 2 msParts, several texts in msPart 1 and one text in msPart 2, this latter text (in the second msPart) belongs to the first textblock in msPart 1?

e.g. in mr-001 we have:

> Summary:
> I) Taʾāmra Māryām “Miracles of Mary” (fols. 3ra-97rb)
>                      I-1) Maṣḥāfä śǝrʿāt, Introductory rite of al-Muʿallaqah (fols. 3ra-6rb)
> I-2) Introductory exhortation (fols. 6rb-8va)
> I-3) ʾƎsaggǝd laki wa-ʾǝweddǝsaki... "I worship Thee..." (fols. 8va-9rb)
> I-4) Taʾāmra Māryām "Miracles of Mary": 90 miracles (fols. 9va-77va, 82ra-89ra)
> I-5) ʾƎsaggǝd la-malakotǝka... "I worship Thy Godhead..." (fols. 95ra-97rb)
> II) Taʾāmra Mikāʾel “Miracles of Michael”: 3 miracles (fols. 77va-79vb)
> III) Taʾāmra Libānos “Miracles of Libanos”: 4 miracles (fols. 79vb-80vb)
> IV) Taʾāmra Gabra Manfas Qǝddus “Miracles of Gäbrä Mänfäs Qǝddus”: 2 miracles (fols. 80vb-81vb)
> V) Taʾāmra madḫāne ʿālam “Miracles of the Saviour of the World”: 1 miracle (fols. 81vb-82ra)
> VI) Taʾāmra ʾIyāsus “Miracles of Jesus”: 4 miracles (fols. 89ra-92ra)
> VII) Taʾāmra śǝllāse “Miracles of the Trinity”: 3 miracles (fols. 92ra-93rb)
> VIII) Salām laki ḫoḫǝta mǝśrāq... “Salutation to you, Threshold of the East…” (fols. 93rb-94rb)

the text mentioned here under I-5) is actually in msPart 2, if I split the description in 2 msParts I lose this info (?)

**Comment by eu-genia** [comment]
what is now converted in all E-S mss as `<rubric>` should be `<decoNote type="rubrication">` and moved to physDesc (rubrics are headers, we here have the information about the use of red ink)
(or maybe the tag rubrication can be created as it is listed here: http://cds.library.brown.edu/conferences/tei10/tei10.papers/gartner.html)
by the way possibly the information that the script is Ethiopic should be not a handNote but a scriptNote

**Comment by eu-genia** [comment]
what now appears in all E-S mss in collation as the number of leafs (unit="leaf") is actually the number of bifolia (double leaves), should be changed throughout

```
<collation>
                              <list>
                                 
                                 <item xml:id="q12">
                                    <dim unit="**leaf**">2</dim>
                                    
                                    <locus from="95r" to="98v"/>XI</item>
                              </list>
                           </collation>
```

**Comment by eu-genia** [comment]
how do we treat, in mss that consist of several msparts, information that belongs to the whole ms? (e.g. history/binding etc.)? I now created an extra msPart around the two nested ones but this does not jump to me as the best solution. barnard seems to suggest an additional mssstmt element as child of sourceDesc see http://users.ox.ac.uk/~lou/wip/MS/appx1.sgm http://users.ox.ac.uk/~lou/wip/MS/msextns.htm

since they (http://users.ox.ac.uk/~lou/wip/MS/index.htm) approached a similar task as ours maybe we can copy something... 

interesting also the `<collation>` with additional subtags:

```
<COLLATION>
<QUIREFORMULA>
<QUIREGROUP RANGE="fols. 1-13">
<QUIRESEQUENCE LEAVES="12+1" N="1">1st leaf added, fol. 
1</QUIRESEQUENCE>
</QUIREGROUP>

<QUIREGROUP RANGE="fols. 14-25">
<QUIRESEQUENCE LEAVES="6" RANGE="fols. 14-19" 
N="II"></QUIRESEQUENCE>
<QUIRESEQUENCE LEAVES="4" RANGE="fols. 20-23" 
N="III"></QUIRESEQUENCE>
<QUIRESEQUENCE LEAVES="2" RANGE="fols. 24-25" 
N="IV"></QUIRESEQUENCE>
</QUIREGROUP>

<QUIREGROUP RANGE="fols. 26-91">
<QUIRESEQUENCE LEAVES="8" RANGE="fols. 26-89" N="V-
XII"></QUIRESEQUENCE>
<QUIRESEQUENCE LEAVES="2" RANGE="fols. 90-91" 
N="XIII"></QUIRESEQUENCE>
</QUIREGROUP>

<QUIREGROUP RANGE="fols. 92-184">
<QUIRESEQUENCE LEAVES="8" RANGE="fols. 92-123" N="XIV-
XVII"></QUIRESEQUENCE>
<QUIRESEQUENCE LEAVES="4" RANGE="fols. 124-127" 
N="XVIII"></QUIRESEQUENCE>
<QUIRESEQUENCE LEAVES="8" RANGE="fols. 128-175" N="XIX-
XXIV"></QUIRESEQUENCE>
<QUIRESEQUENCE LEAVES="10-1" RANGE="fols> 176-184" N="XXV">10th leaf 
cancelled, after fol. 184</QUIRESEQUENCE>
</QUIREGROUP>

</QUIREFORMULA>

<EVIDENCE>
<MARKINGS SCOPE="quire" FORM="catchword"><P>a trace of a catchword survives 
at fol. 127v</P></MARKINGS>
</EVIDENCE>

</COLLATION>
```

**Comment by eu-genia** [comment]
```
                  <persName role="donor" corresp="PRS0000">A number of individuals are mentioned in the Ms., Ramḥā Śǝllāse (s. miniature, fol. 2v); ʿƎquba Libānos, Lāhǝya Dǝngǝl, Walda Tǝnśāʾe (in the supplication formulas, e.g., fol. 9va, 10vb); elsewhere Gǝrma Yoḥānnǝs, Walatta Mikāʾel (fol. 14vb); Gabra Ḥǝywat, ʾābuna Walda Yoḥānnǝs (fol. 41va); Salomon (fol. 42ra), and others.
Mss. MR-009 and MR-016 were commissioned by the same donors.</persName>
                  <!--ACHTUNG! This is actually paragraphic information identifying the donor. 
                                        Person/persName should only contain the person name, not all the paragraph.-->
               </person>
```
now transformed to

```
            <listPerson>
               <person>
                  <persName role="donor" corresp="PRS0000">Ramḥā Śǝllāse (<note>s. miniature <locus target="#2v">2v</locus></note>) </persName>
                  <persName role="donor" corresp="PRS0000">ʿƎquba Libānos (<note>in the supplication formulas, e.g., <locus target="#9va">9va</locus>, <locus target="#10vb">10vb</locus></note>) </persName>
                  <persName role="donor" corresp="PRS0000">Lāhǝya Dǝngǝl (<note>in the supplication formulas, e.g., <locus target="#9va">9va</locus>, <locus target="#10vb">10vb</locus></note>) </persName>
                  <persName role="donor" corresp="PRS0000">Walda Tǝnśāʾe (<note>in the supplication formulas, e.g., <locus target="#9va">9va</locus>, <locus target="#10vb">10vb</locus></note>) </persName>
                  <persName role="donor" corresp="PRS0000">Gǝrma Yoḥānnǝs (<locus target="#14vb">14vb</locus>)</persName>
                  <persName role="donor" corresp="PRS0000">Walatta Mikāʾel (<locus target="#14vb">14vb</locus>)</persName>
                  <persName role="donor" corresp="PRS0000">Gabra Ḥǝywat (<locus target="#41va">41va</locus>)</persName>
                  <persName role="donor" corresp="PRS0000"><roleName type="title">ʾābuna</roleName> Walda Yoḥānnǝs (<locus target="#41va">41va</locus>)</persName>
                  <persName role="donor" corresp="PRS0000">Salomon (<locus target="#42ra">42ra</locus>)</persName>
                  <note>Mss. <ref type="mss" corresp="ESmr009">MR-009</ref> and <ref type="mss" corresp="ESmr016">MR-016</ref> were commissioned by the same donors</note>
               </person>
               <person>
                  <persName corresp="PRS10788WaldaMuse" role="scribe">Walda Muse</persName>
               </person>

            </listPerson>
```

is this ok with the notes or where to put the information?

**Comment by PietroLiuzzo** [comment]
- [ ] rubric
- [ ] unit in collation
- [ ] quire structure https://github.com/SChAth/ScAthiop/wiki/GUI15, includes schema revision
- [ ] persons

**Comment by PietroLiuzzo** [comment]
for persons, I have updated a bit ESmr001.xml.
please note:
* a person element can contain several persName of that person, but each person should have its own persName. I believe those in the example are different persons, so I have added a person element for each
* locus with text inside will be rendered with that text, if you want to have f. or ff. it will need to be there. otherwise, please omit the content and the xslt will add those in the preview
* if the brackets around note are part of the desired layout, please omit them and let me know so I can handle them this way in the preview or alternatively move them inside the element.

now the preview takes into account note in this position.

**Comment by PietroLiuzzo** [comment]
@eu-genia this rubric and rubrication is tricky IMHO. I would have to move information from a msItem to a handNote, where we usually record this with ab[@type='rubrication'] instead of creating a decoDesc type rubrication containing this mixed extracted info. Nevertheless I wonder if, beside the name of the element, this information is better related to the msItem or to the hand. in the first case I could change rubric to ab[@type='rubrication'] but leave it where it is. in the second case I would instead name it so, but move it to the first handNote sibling.

**Comment by PietroLiuzzo** [comment]
needs the opinion of @eu-genia

**Comment by eu-genia** [comment]
well as a rule rubrication (in the sense of use of red) is a feature of the entire codicological unit so belongs to the physical description (may be not under the hand but somewhere else in the physdesc part); the rubrics (in the sense of structuring with subheadings in whichever way) are a feature of msitem, so we need the two distinct elements.

**Comment by eu-genia** [comment]
see also how e-codices use rubric/rubrication:
under msItem:
`<title>de motu argumenti</title>`
`<rubric>De motu argumenti in una die inveniendo</rubric>`
(i.e. rubric is the subheading of the msItem)
rubrication here is a decoNote, ie part of physDesc, cp http://www.e-codices.unifr.ch/en/description/ubb/F-III-0025/HAN

**Comment by PietroLiuzzo** [comment]
I have modified the ES files **only** moving what is now in rubric to a `decoNote[@type='rubrication']`
I have also updated the guidelines.

Currently it is possible to use `rubric` within `msItem`. `seg[@type='rubrication']` in `handNote` and this decoNote as well. It would be nice to confirm and describe the distinction in use we will adhere to in the guidelines if you could @eu-genia .

I have update the preview accordingly.

**Comment by eu-genia** [comment]
confirmed:
rubric == heading/subheading of a text
decoNote type='rubrication' == the use of red ink for headings / names etc.

**Comment by PietroLiuzzo** [comment]
I am adding these two short definitions in guidelines
