### ISSUE TITLE
works in other traditions

### ISSUE THREAD

**Issue by PietroLiuzzo** [SChAth/ScAthiop#85]
https://github.com/SChAth/ScAthiop/wiki/NAV17

to extract information about other traditions there needs to be a defined way to encode this

**Comment by PietroLiuzzo** [comment]
@eu-genia @MassimoVilla about the different traditions of an abstract work / textual unit / work (opera), I think we don't want a record for each language in which this has been translated, unless the translation is actually a distinct work, which will get its ID. Please check the link above to see if the description of what the Clavis should look like is ok. 

* To assign different traditions to a text, I would base our computational knowledge on the `@xml:lang` of each title element in titleStmt and require a xml:id for each of this which corresponds to a tradition. If a given title is simply another entry for our consumption, in e.g. normalized ge'ez or english, that will not get a xml:id as it does not currently by the guidelines, it will if it is the title in a different tradition. Thus a reference to a specific tradition will be a pointer like LIT2650CanonsNicaea1#t2. If it is useful for this id to be a bit more speaking, we can relax the schema here not to match t+ a digit, but allow for example values for these ids like t2latin t3coptic. I would also force the use of `@xml:lang` in title for works, with a test in the schema if you agree.

* eventually witnesses will be manuscripts of one or the other tradition. I would force with a test the use of `@xml:lang` also in `witness`, although this is a bit forcing, as we use this element empty and we would thus assume that language of the manuscript we point to is e.g. latin. This does not seem to me a big problem.

* bibliography could then use the ids given to titles or eventually witnesses by using `@corresp` in `bibl` as we currently do for `bibl`s in catalogues pointing to items of the listBibl[@type='mss']. a reference to BHG could be given as a bibl in listBibl[@type='catalogues'] with a @corresp to the greek `title`
 
* relations will be anyway in use to determin relations e.g. of  LIT2650CanonsNicaea1 to LIT1226Canons.

I do believe somebody should take special care of the works as a side task, as there are already plenty of ids without actual records

**Comment by PietroLiuzzo** [comment]
````
<idno type="URI">http://syriaca.org/work/270</idno>
<idno type="BHS">49</idno>
<idno type="BHO">772</idno>
````
this is what syriaca.org uses, and we might consider this option as well.

**Comment by PietroLiuzzo** [comment]
@antobrita might also help us here.

**Comment by eu-genia** [comment]
i am not sure the syriaca way is the best - it gives so to say the text id in other collections/databases but does not specify language traditions and probably does not offer a possibility to add things that may be missing in BHS/BHO etc - besides for some traditions we may have no standard repositories but very well have parallel texts

**Comment by eu-genia** [comment]
on checking syriaca - their pointers are not to other traditions but to the very same syriac work in repertories, so does not apply to our case

**Comment by PietroLiuzzo** [comment]
proposal from 22.9 meeting is to use `bibl` normally with a pointer to the printed clavis or publication we refer to and enter the id in the `citedRange[@unit='item']`

**Comment by PietroLiuzzo** [comment]
proposal from 22.9 meeting

* if a subpart of a work needs ist bibliography this can be given in the `div[@type='textpart']`
* if a subpart without independent circulation in the Ethiopic tradition needs to reference the work independently in other traditions titles will be added and referenced in the appropriate `div[@type='textpart']`

**Comment by PietroLiuzzo** [comment]
We would definitely need to work on an example.

**Comment by thea-m** [comment]
How to encode relations such as the Vorlage of 1) only parts of works, not whole works (therefore it will make no sense to add a title for the Vorlage) and/or 2) works which have no reference number?
 
For an example, see LIT4018Mashafa#Introduction3:

```xml
<div type="textpart" subtype="chapter" xml:lang="gez" xml:id="Introduction3">
                  <label>Introduction, chapter 3: ነገር፡ ዘከመ፡ እፎ፡ ይደሉ፡ ለዐቃቤ፡ ሥራይ፡ አእምሮ፡</label>
                  <desc> The third chapter contains the translation of the treatise faṣl fī-mā yaǧib ʿalā ṭ-ṭabīb maʿrifatihī ʾaʿnī muʿallim al-iʿtirāf.
                     <listBibl type="editions">
                        <bibl><ptr target="bm:Cöln1908Nomokanon3"/><citedRange unit="page">210-217</citedRange></bibl> <!--Arabic-->
                     </listBibl>
                  </desc>
               </div>
```

**Comment by MassimoVilla** [comment]
I came across a similar problem: BAVet2 contains the Latin translation of Canon 37 of the Canons of the Council of Nicaea II. So, I need to encode the t2latin (type=translated) of the following textpart: "LIT2688CanonsNicaea2#Canon37".

**Comment by thea-m** [comment]
It could work to encode the different titles of a textpart within a <head> element:
``` xml
<div type="textpart" subtype="chapter" xml:lang="gez" xml:id="Introduction3">
                  <head><title xml:id="t3">Introduction, chapter 3: ነገር፡ ዘከመ፡ እፎ፡ ይደሉ፡ ለዐቃቤ፡ ሥራይ፡ አእምሮ፡</title>
                     <title xml:id="t3arabic">faṣl fī-mā yaǧib ʿalā ṭ-ṭabīb maʿrifatihī ʾaʿnī muʿallim al-iʿtirāf</title></head>
``` 
What do you think @MassimoVilla ? Would this work for your case? (We should maybe use another nomenclature to differentiate the titles of textparts from the main titles)

**Comment by MassimoVilla** [comment]
I think it can work, but some aspects of the issue have to be assessed:

- Since BAVet2 contains the Latin translation of Canon 37 of the Canons of Nicaea II, this particular item would be encoded, according to our current guidelines, as `<title ref="LIT2688CanonsNicaea2#Canon37#t2latin"/>`, a value which is not accepted as it contains two ##. How can we solve this problem?

- We usually deal with (mostly Arabic) versions which are Vorlagen of the Ethiopic text. In my case the Ethiopic textpart is indeed the Vorlage of a Latin translation. I believe that, whenever we encode the title of a textpart existing in other traditions, we might need a relation (nested within `<div type="textpart" subtype="chapter" xml:lang="gez" xml:id="Canon37"></div>`) which clearly defines what is active and what is passive.

**Comment by PietroLiuzzo** [comment]
#225

**Comment by PietroLiuzzo** [comment]
need to update guidelines and xslt for  these cases.

**Comment by PietroLiuzzo** [comment]
CPG ids and corresponding Clavis we use the bibl. the work list should print the values of the bibl with a corresp to a #t in another tradition and provide the id which is given in the citedRange...

**Comment by PietroLiuzzo** [comment]
in a work inside sourceDesc there will be this. updating guidelines accordingly
````xml
<listBibl type="clavis">
               <bibl corresp="#t1" type="CC"><ptr target="bm:CPG"/><citedRange unit="item">123</citedRange></bibl>
               <bibl corresp="#t1" type="CPG"><ptr target="bm:CPG"/><citedRange unit="item">123</citedRange></bibl>
               <bibl corresp="#t1" type="BHO"><ptr target="bm:BHO"/><citedRange unit="item">123</citedRange></bibl>
               <bibl corresp="#t1" type="CANT"><ptr target="bm:CANT"/><citedRange unit="item">123</citedRange></bibl>
               <bibl corresp="#t1" type="CAVT"><ptr target="bm:CAVT"/><citedRange unit="item">123</citedRange></bibl>
               <bibl corresp="#t1" type="BHL"><ptr target="bm:BHL"/><citedRange unit="item">123</citedRange></bibl>
               <bibl corresp="#t1" type="syriaca"><ptr target="bm:syriaca"/><citedRange unit="item">123</citedRange></bibl>
            </listBibl>
````
