### ISSUE TITLE
ruling and pricking order

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#89]
`<ab type="pricking">Pricking and ruling are visible.</ab>
                              <ab type="ruling" subtype="pattern"> 1A-1A-1A1A/0-0/0-0/C(or B!)</ab>
                              <ab type="pricking"> Primary pricks are visible.</ab>
                              <ab type="pricking"> Ruling pricks are visible.</ab>
                              <ab type="ruling"> The upper line is written above the ruling.</ab>
                              <ab type="ruling"> The bottom line is written above the ruling.</ab>
                              <ab type="punctuation">
                                 <list>
                                    <item xml:id="div1">Chain of black and red dots (<locus target="80vb">80vb</locus>)</item>
                                 </list>
                              </ab>`

is visualized as 

> **Ruling of p1**
> (Subtype: pattern) 1A-1A-1A1A/0-0/0-0/C(or B!)
> The upper line is written above the ruling.
> The bottom line is written above the ruling.
> **Pricking of p1**
> Pricking and ruling are visible.
> Primary pricks are visible.
> Ruling pricks are visible.
> **Other of p1**
> pricking : Pricking and ruling are visible.
> ruling (Subtype: pattern) : 1A-1A-1A1A/0-0/0-0/C(or B!)
> pricking : Primary pricks are visible.
> pricking : Ruling pricks are visible.
> ruling : The upper line is written above the ruling.
> ruling : The bottom line is written above the ruling.
> punctuation : Chain of black and red dots (80vb)

Should be Punctuation instead of Other and then only the content of punctuation, the rest is repeated

**Comment by eu-genia** [comment]
for distinct msParts it would be better to structure the description in Codicological units and not repeat "of p1" etc. (see here http://www.e-codices.unifr.ch/en/description/ubb/F-III-0025/HAN)

**Comment by PietroLiuzzo** [comment]
I have fixed the first point and moved to the requirement for manuscript view the second comment.
