### ISSUE TITLE
filiation not shown in preview

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#93]
in BNFet1, whiile the ms's relation is shown in the preview the describing paragraph is not seen

`     <filiation> The manuscript is a direct copy of <ref type="mss" corresp="BSLet169">BSLet169</ref>, on which <persName ref="PRS3562Dillmann">Dillmann</persName> 
                        based his edition <bibl>
                        <ptr target="bm:Dillmann1853Octateuch"/>
                     </bibl>
                       <listBibl type="relations">
                        <bibl/>
                        <relation name="saws:isDirectCopyOf"
                           active="#ms_i1"
                           passive="BSLet169"/>
                     </listBibl></filiation>`

is shown as

> Relations of this Entity with other entities Subject 	Relation 	Object
> #ms_i1 	saws:isDirectCopyOf 	BSLet169
> Authors

**Comment by PietroLiuzzo** [comment]
I am not sure that I can reproduce this issue. Copying in the file the example give I get the following result.
![schermata 2016-06-16 alle 12 00 23](https://cloud.githubusercontent.com/assets/508012/16112947/04cfef98-33ba-11e6-8a0c-9220ccab6247.png)

**Comment by thea-m** [comment]
Ah yes, thank you
