### ISSUE TITLE
missing bibliography 

### ISSUE THREAD

**Issue by thea-m** [SChAth/ScAthiop#94]
In BNFet2, 
````
 <item xml:id="a6" >
                  <desc type="Comment"> At the end of the <ref target="#ms_i4.4">Book of Ruth</ref>, after  <ref target="#coloph1"/>
                  gloss by <persName ref="PRS10036Wansleb">Wansleben</persName>   </desc>
                  <quote xml:lang="la">Hic est ille <persName ref="PRS6525Mahdanta">Mahzente-Marjam</persName> qui subscripsit carmini abissinico quod <persName ref="PRS10129Wemmers">P. Jacobus Wemmers</persName> 
                    lexico suo abissinico praemisit, quod fuit impressum <placeName ref="LOC5374Rome">Romae</placeName> a <date>1638</date> in Congreg. de Prop. fide</quote>
                  <bibl>
                    <ptr target="bm:Wemmers1638Lexicon"></ptr>
                  </bibl>
                </item>
````
is shown as 

>  At the end of the Book of Ruth (ms_i4.4), after n. coloph1 gloss by Wansleben (Type: Comment)
> 
> (la) Hic est ille Mahzente-Marjam qui subscripsit carmini abissinico quod P. Jacobus Wemmers lexico suo abissinico praemisit, quod fuit impressum Romae a 1638 in Congreg. de Prop. fide 

the link to the bibliographical entry for the lexicon, bm:Wemmers1638Lexicon, is shown nowhere

**Comment by PietroLiuzzo** [comment]
should this be listed as a bibliography with items or only appear as a link in the text? if the first is true, please simply wrap the bibl into a listBibl.

**Comment by thea-m** [comment]
Thank you!
