### ISSUE TITLE
Book of Hours

### ISSUE THREAD

**Issue by MassimoVilla** [SChAth/ScAthiop#97]
I see that a new record for the Book of Hours has been created in the drive:
LIT3197Saatat.

But a record is already existing, and I have used it for ms. BAVet1:
LIT1961Mashaf --> Mäṣḥafä säʿatat // Horologium

**Comment by thea-m** [comment]
Thank you, I deleted it and changed the reference in BNFet9. Will the numeration of the new works added after the wrong record  (LIT3198Prayer-LIT3205Introd) now be changed?

**Comment by PietroLiuzzo** [comment]
no, please, never reassign numbers. even if the file has not been created. Thanks!
