### ISSUE TITLE
double/triple view

### ISSUE THREAD

**Issue by eu-genia** [SChAth/ScAthiop#98]
in MR-001 the information on rubrication appears 3 times, and the decoNotes of msPart1 and msPart2 appear under each part

btw: decoNotes without locus are now signalled as errors and they should not be (e.g. rubrication is throughout, there is no specific locus possible)

**Comment by PietroLiuzzo** [comment]
This is due to the transformation of the file to move information from rubric to a decoNote type rubrication. The text is shown three times because is three times in the file.

**Comment by PietroLiuzzo** [comment]
schema updated

**Comment by eu-genia** [comment]
it is now once but still shows three times:
i have one decoNote for the entire ms (rubrication), and one each (harag) for each of the msParts;
I get the visualisation of all three together both for the ms, for msPart 1, and for msPart 2

> Decoration of p2
> In this manuscript there are 1 notes about rubrication and 2 notes about band.
> Rubrication
> rubrication: Nomina sacra; names of the protagonists; names of the donors; groups of lines (alternating with black lines) in the incipit page of Texts I-1 and I-4; incipits of miracles and their numbers; incipit of Text I-5; elements of the punctuation signs and quire marks; elements of Ethiopic numerals. the incipit; nomina sacra; names; elements of the punctuation signs and quire marks; elements of Ethiopic numerals
> Other decorations
> band: Simple, crude ornamental bands (haräg): ff. 3r , 81vb , 82ra .
> Other decorations
> band: f. 95r Simple, crude ornamental band.
